USE 
	SUPERTODO
SELECT
	CODIGO,CODBARRAS,DESCRIPCIO,COSTO_ING,HABILITADO AS HABILITADO,PRODTER AS COMERCIAL,MATPRIMA AS COMPRAS 
FROM 
	MtMercia
WHERE
	CODIGO NOT LIKE 'A-%' AND CODIGO NOT LIKE 'B-%' AND CODIGO NOT IN ('A12501','A10735','12179','001') AND PRODTER='1'