USE SUPERTODO
select m.codigo,
m.CODBARRAS,a.CODBARRAS AS NUEVO_CODBARRAS,case when m.CODBARRAS=a.CODBARRAS then 'TRUE' else 'FALSE' end as SonIgualesCod,m.DESCRIPCIO,a.DESCRIPCIO AS NUEVA_DESCRIP,
CASE WHEN m.DESCRIPCIO = a.DESCRIPCIO THEN 'TRUE' ELSE 'FALSE' END AS SonIgualesDesc,
m.CODLINEA,a.CODLINEA AS NUEVO_CODLINEA,m.CODSBLIN,a.CODSBLIN AS NUEVO_CODSBLIN
From MtMercia m
Inner Join SUPERTODO.dbo.AAAHoja1$ a ON a.CODIGO=m.CODIGO

/*update m
set 
	m.CODBARRAS = a.CODBARRAS,
	m.DESCRIPCIO = a.DESCRIPCIO,
	m.CODLINEA = a.CODLINEA,
	m.CODSBLIN = a.CODSBLIN
From MtMercia m
Inner Join SUPERTODO.dbo.AAAHoja1$ a ON a.CODIGO=m.CODIGO*/