USE SUPERTODO
select A.NRODCTO,B.NRODCTO_NUEVO,A.HORA,B.HORA,A.TIPODCTO,B.NCF_Fijo,A.NOTA,B.NOTA_NUEVA,A.FECHA,B.fecha
from 
	Trade A
INNER JOIN
	AAATRADERNY2$ B ON B.NRODCTO_NUEVO=A.NRODCTO AND A.TIPODCTO=B.NCF_Fijo

/*update A
Set A.HORA=B.HORA ,A.NOTA=B.NOTA_NUEVA
from Trade A
INNER JOIN
	AAATRADERNY2$ B ON B.NRODCTO_NUEVO=A.NRODCTO AND A.TIPODCTO=B.NCF_Fijo*/