USE BESTPRICE
update a
set
    a.CTAAII=b.CTAAII,
    a.CTACOM=b.CTACOM,
    a.CTACOMDEV=b.CTACOMDEV,
    a.CTACOMDIVA=b.CTACOMDIVA,
    a.CTACOMDRTE=b.CTACOMDRTE,
    a.CTACOMIVA=b.CTACOMIVA,
    a.CTACOMRTE=b.CTACOMRTE,
    a.CTAVTA=b.CTAVTA,
    a.CTAVTADEV=b.CTAVTADEV,
    a.CTAVTADIVA=b.CTAVTADIVA,
    a.CTAVTADRTE=b.CTAVTADRTE,
    a.CTAVTAIVA=b.CTAVTAIVA,
    a.CTAVTARTE=b.CTAVTARTE,
    a.CTDRIRCCOM=b.CTDRIRCCOM,
    a.CTDRIRCVTA=b.CTDRIRCVTA,
    a.CTDRIRSCOM=b.CTDRIRSCOM,
    a.CTRIRCCOM=b.CTRIRCCOM,
    a.CTRIRCVTA=b.CTRIRCVTA,
    a.CTRIRSCOM=b.CTRIRSCOM,
    a.DESC_LAR=b.DESC_LAR
FROM MtMercia a
CROSS JOIN MtMercia b
WHERE b.CODIGO = 'A-13251' AND
a.CODIGO IN ('A-18258')