use SUPERTODO
/*ACTUALIZA CUENTAS CONTABLES ERROR QUE GENERA "NO COINCIDE LOS TIPOS" VAR CON INT
UPDATE MtMercia
SET
    CTACOM      = CASE WHEN CTACOM      = ' ' THEN '0' ELSE CTACOM END,
    CTACOMDEV   = CASE WHEN CTACOMDEV   = ' ' THEN '0' ELSE CTACOMDEV END,
    CTACOMDIVA  = CASE WHEN CTACOMDIVA  = ' ' THEN '0' ELSE CTACOMDIVA END,
    CTACOMDRTE  = CASE WHEN CTACOMDRTE  = ' ' THEN '0' ELSE CTACOMDRTE END,
    CTACOMIVA   = CASE WHEN CTACOMIVA   = ' ' THEN '0' ELSE CTACOMIVA END,
    CTACOMRTE   = CASE WHEN CTACOMRTE   = ' ' THEN '0' ELSE CTACOMRTE END,
    CTAVTA      = CASE WHEN CTAVTA      = ' ' THEN '0' ELSE CTAVTA END,
    CTAVTADEV   = CASE WHEN CTAVTADEV   = ' ' THEN '0' ELSE CTAVTADEV END,
    CTAVTADIVA  = CASE WHEN CTAVTADIVA  = ' ' THEN '0' ELSE CTAVTADIVA END,
    CTAVTAIVA   = CASE WHEN CTAVTAIVA   = ' ' THEN '0' ELSE CTAVTAIVA END,
    CTDRIRCCOM  = CASE WHEN CTDRIRCCOM  = ' ' THEN '0' ELSE CTDRIRCCOM END,
    CTRIRCCOM   = CASE WHEN CTRIRCCOM   = ' ' THEN '0' ELSE CTRIRCCOM END;*/

--QRY VISUALIZAR PRODUCTOS QUE ESTAN EN NULL VACIOS, EN MTMERCIA
USE SUPERTODO
SELECT 
CODIGO,CTACOM, CTACOMDEV, CTACOMDIVA, CTACOMDRTE, CTACOMIVA, CTACOMRTE, CTAVTA, CTAVTADEV, 
CTAVTADIVA, CTAVTADRTE, CTAVTAIVA, CTAVTARTE, CTDRIRCCOM, CTDRIRCVTA, CTDRIRSCOM, CTRIRCCOM

FROM MtMercia
WHERE CTACOM = ' '
   OR CTACOMDEV = ' '
   OR CTACOMDIVA = ' '
   OR CTACOMDRTE = ' '
   OR CTACOMIVA = ' '
   OR CTACOMRTE = ' '
   OR CTAVTA = ' '
   OR CTAVTADEV = ' '
   OR CTAVTADIVA = ' '
   OR CTAVTAIVA = ' '
   OR CTDRIRCCOM = ' '
   OR CTRIRCCOM = ' ';

