USE BESTPRICE
--TAR2
UPDATE a
SET 
a.CTACOM      = b.CTACOM,
a.CTACOMDEV   = b.CTACOMDEV,
a.CTACOMDIVA  = b.CTACOMDIVA,
a.CTACOMDRTE  = b.CTACOMDRTE,
a.CTACOMIVA   = b.CTACOMIVA,
a.CTACOMRTE   = b.CTACOMRTE,
a.CTAVTA      = b.CTAVTA,
a.CTAVTADEV   = b.CTAVTADEV,
a.CTAVTADIVA  = b.CTAVTADIVA,
a.CTAVTADRTE  = b.CTAVTADRTE,
a.CTAVTAIVA   = b.CTAVTAIVA,
a.CTAVTARTE   = b.CTAVTARTE,
a.CTDRIRCCOM  = b.CTDRIRCCOM,
a.CTDRIRCVTA  = b.CTDRIRCVTA,
a.CTDRIRSCOM  = b.CTDRIRSCOM,
a.CTRIRCCOM   = b.CTRIRCCOM
FROM MtMercia a
OUTER APPLY (	
    SELECT TOP 1 
b.CTACOM, b.CTACOMDEV, b.CTACOMDIVA, b.CTACOMDRTE, b.CTACOMIVA, b.CTACOMRTE, b.CTAVTA, b.CTAVTADEV, 
b.CTAVTADIVA, b.CTAVTADRTE, b.CTAVTAIVA, b.CTAVTARTE, b.CTDRIRCCOM, b.CTDRIRCVTA, b.CTDRIRSCOM, b.CTRIRCCOM
	FROM MtMercia b
    WHERE b.CODTARIVA = 'TAR2'
	AND b.CODIGO='A-15907'--CAMBIAR REFERENCIA LO QUE QUIERA REPLICAR
) b
WHERE a.CODTARIVA = 'TAR2' AND a.CODIGO like 'A-%' OR a.CODIGO like 'B-%';