USE SUPERTODO
--REVISA QUE COINCIDA LOS TARIVA DE LAS REFERENCIAS
SELECT CODTARIVA,IVA,CODIGO
FROM MtMercia
WHERE CODTARIVA = 'TAR2'
  AND IVA <> 18;

SELECT CODTARIVA,IVA,CODIGO
FROM MtMercia
WHERE CODTARIVA = 'TAR1'
  AND IVA <> 16;

SELECT CODTARIVA,IVA,CODIGO
FROM MtMercia
WHERE CODTARIVA = 'TAR0'
  AND IVA <> 0;

--ACTUALIZA IVA REFERENCIAS CODTARIVA Y IVA
UPDATE MtMercia
SET IVA = '18'
WHERE CODTARIVA = 'TAR2'
  AND IVA <> '18';
UPDATE MtMercia
SET IVA = '16'
WHERE CODTARIVA = 'TAR1'
  AND IVA <> '16';
UPDATE MtMercia
SET IVA = '0'
WHERE CODTARIVA = 'TAR0'
  AND IVA <> '0';
--NOVEDAD 2 TAR DIFERENTES ENTRE BD
USE SUPERTODO
select CODTARIVA,IVA,CODIGO,PASSWORDIN,FECING from MtMercia where CODIGO='A-18405'
USE BESTPRICE
select CODTARIVA,IVA,CODIGO,PASSWORDIN,FECING from MtMercia where CODIGO='A-18405'

USE SUPERTODO
select CODTARIVA,IVA,CODIGO,PASSWORDIN,PASSWORDMO,FECING,FECMOD from MtMercia where CODIGO='A-18267'
USE BESTPRICE
select CODTARIVA,IVA,CODIGO,PASSWORDIN,PASSWORDMO,FECING,FECMOD from MtMercia where CODIGO='A-18267'