USE BESTPRICE
select * from MtMedPag
select BANCO,CODBANCO,MEDIOPAG,DCTO,TIPODCTO,VALOR,FECING from MvCuadre where MEDIOPAG='01'

select BANCO,CODBANCO,MEDIOPAG,DCTO,TIPODCTO,VALOR,FECING,PASSWORDIN from MvCuadre where DCTO='91099' and TIPODCTO='B2'

update mvcuadre set BANCO ='11050501', CODBANCO='11', MEDIOPAG='01' where DCTO='91099' and TIPODCTO='B2'