USE SUPERTODO
select NRODCTO,NOTA,FECHA,MEDIOPAG from Trade where TIPODCTO IN ('R1','R2') AND  MEDIOPAG='R4' AND PASSWORDIN='SUPER'
select * from MvCuadre where TIPODCTO IN ('R1','R2') AND  PASSWORDIN like'%CAROLINA%'

update Trade
set MEDIOPAG='R11'
where TIPODCTO IN ('R1','R2') AND MEDIOPAG='R4' AND PASSWORDIN='SUPER'
