USE SUPERTODO
select A.NRODCTO,A.MEDIOPAG,A.FECHA,B.DCTO,B.MEDIOPAG,A.TIPODCTO,B.TIPODCTO from Trade A
INNER JOIN MvCuadre B ON DCTO=NRODCTO WHERE FECHA BETWEEN '05-02-2026' AND '19-02-2026' AND A.TIPODCTO IN ('R1','R2','R4') AND B.MEDIOPAG NOT IN('97','01')
ORDER BY FECHA DESC

update A
set A.MEDIOPAG=B.MEDIOPAG
from Trade A
INNER JOIN MvCuadre B ON DCTO=NRODCTO
WHERE FECHA BETWEEN '05-02-2026' AND '19-02-2026' AND A.TIPODCTO IN ('R1','R2','R4') AND B.MEDIOPAG NOT IN('97','01')


select * from Trade WHERE FECHA BETWEEN '05-02-2026' AND '19-02-2026' AND TIPODCTO IN ('R1','R2','R4')
select * from MvCuadre WHERE FECING BETWEEN '05-02-2026' AND '19-02-2026' AND TIPODCTO IN ('R1','R2','R4') AND MEDIOPAG NOT IN('97','01')

SELECT 
    B.DCTO,B.TIPODCTO AS TipoMvcuadre,A.TIPODCTO AS TipoTrade,A.PASSWORDIN,B.FECING
FROM Trade AS A
INNER JOIN MvCuadre AS B ON B.DCTO = A.NRODCTO AND A.FECHA=B.FECING AND B.TIPODCTO<>A.TIPODCTO
ORDER BY B.DCTO DESC;


SELECT COUNT(*)
FROM Trade A
INNER JOIN MvCuadre B 
    ON B.DCTO = A.NRODCTO
WHERE 
    A.FECHA BETWEEN '05-02-2026' AND '19-02-2026'
    AND A.TIPODCTO IN ('R1','R2','R4')
    AND B.MEDIOPAG NOT IN ('97','01');


	SELECT 
    A.NRODCTO,
    A.MEDIOPAG AS MEDIOPAG_ACTUAL,
    B.MEDIOPAG AS MEDIOPAG_NUEVO
FROM Trade A
INNER JOIN MvCuadre B 
    ON B.DCTO = A.NRODCTO
WHERE 
    A.FECHA BETWEEN '05-02-2026' AND '19-02-2026'
    AND A.TIPODCTO IN ('R1','R2','R4')
    AND B.MEDIOPAG NOT IN ('97','01');