USE SUPERTODO
select m.codigo,
case when m.CODBARRAS=a.CODBARRAS then 'TRUE' else 'FALSE' end as SonIgualesCod,m.DESCRIPCIO,a.DESCRIPCIO AS NUEVA_DESCRIP,m.CODLINEA,a.CODLINEA AS NUEVO_CODLINEA,m.CODSBLIN,a.CODSBLIN AS NUEVO_CODSBLIN,
CASE WHEN m.DESCRIPCIO = a.DESCRIPCIO THEN 'TRUE' ELSE 'FALSE' END AS SonIguales
From MtMercia m
Inner Join Hoja1$ a ON a.CODIGO=m.CODIGO

/*update m
set 
	m.DESCRIPCIO = a.DESCRIPCIO,
	m.CODLINEA = a.CODLINEA,
	m.CODSBLIN = a.CODSBLIN
From MtMercia m
Inner Join Hoja1$ a ON a.CODIGO=m.CODIGO*/