USE BESTPRICE
select BANCO,CODBANCO,DCTO,TIPODCTO,VALOR,PASSWORDIN,MEDIOPAG,* from MvCuadre 
where DCTO='9106' AND TIPODCTO='F2'

--update MvCuadre set BANCO='11050501', CODBANCO='11', MEDIOPAG='01' where DCTO='9106' AND TIPODCTO='F2' AND MEDIOPAG='04'