USE SUPERTODO
--select NRODCTO,TIPODCTO,((BRUTO+IVABRUTO)-DESCUENTO),NIT AS TOTAL, PASSWORDIN,HORA,FECHA,* from Trade where ((BRUTO+IVABRUTO)-DESCUENTO)='2210'
select NRODCTO,TIPODCTO,((BRUTO+IVABRUTO)-DESCUENTO) AS TOTAL, PASSWORDIN,HORA,FECHA,* from Trade where NRODCTO='52934'
select DCTO,TIPODCTO,VALOR,PASSWORDIN,BANCO,CODBANCO,MEDIOPAG,FECING,* from MvCuadre where DCTO='52934'

select * from MtMedPag
select * from MvCuadre where MEDIOPAG='13' ORDER BY FECING DESC

--update MvCuadre set BANCO='13350502', CODBANCO='13', MEDIOPAG='13' where DCTO='52654' AND TIPODCTO='B2' AND MEDIOPAG='13'

SELECT 
    A.DCTO,B.TIPODCTO AS TipoTrade,A.TIPODCTO AS TipoMvCuadre,A.VALOR,A.PASSWORDIN,B.FECING
FROM MvCuadre AS A
INNER JOIN Trade AS B ON A.DCTO = B.NRODCTO AND B.FECHA=A.FECING AND B.TIPODCTO<>A.TIPODCTO
ORDER BY A.DCTO DESC;
--ACTUALIZA
/*UPDATE A
SET A.TIPODCTO = B.TIPODCTO
FROM MvCuadre AS A
INNER JOIN Trade AS B ON A.DCTO = B.NRODCTO AND B.FECHA=A.FECING AND A.TIPODCTO <> B.TIPODCTO
*/
--update MvCuadre set BANCO='11050501', CODBANCO='11', MEDIOPAG='01' where DCTO='9106' AND TIPODCTO='F2' AND MEDIOPAG='04'