use COLNOTEXSA
update 
	MTMERCIA
set 
	MTMERCIA.FECHA_ING = (select CAST(FECHAING AS VARCHAR) from V_ULTIMA_FECHAING
where 
	MTMERCIA.CODIGO = V_ULTIMA_FECHAING.PRODUCTO)
where 
	MTMERCIA.CODIGO in (select V_ULTIMA_FECHAING.PRODUCTO from V_ULTIMA_FECHAING)

	USE COLNOTEXSA;

SELECT 
    M.CODIGO,
    M.FECHA_ING AS FECHA_ING_ACTUAL,
    V.FECHAING AS FECHA_ING_NUEVA
FROM 
    MTMERCIA M
INNER JOIN 
    V_ULTIMA_FECHAING V
    ON M.CODIGO = V.PRODUCTO;


use COLNOTEXSA
UPDATE
	ABONOS
SET
	NIT = NITSUCUR
WHERE
	(NIT = ' ')