
use TOSCANAZL
select name, physical_name from sys.database_files


select @@version


ALTER DATABASE TOSCANAZL
MODIFY FILE
(
NAME = TOSCANAZL_Dat,
FILENAME = '\\TOSCANAZLNT02\OFIMATICA\OFIMAENTERPRISE\DATOS-REALES\TOSCANAZL\TOSCANAZL.Mdf',
SIZE = 20240MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 10%
)
GO