USE [COLNOTEXSA]
GO

/****** Object:  View [dbo].[v_movimiento_inv]    Script Date: 26/02/2024 14:58:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[v_movimiento_inv]
AS
SELECT     TR.TIPOMVTO, MVTO.DESCRIPCIO AS MOVIMIENTO, (LTRIM(RTRIM(TR.TIPODCTO)) + '-' + LTRIM(RTRIM(TR.NRODCTO))) AS DOC_FINAL, 
                      TR.NRODCTO AS NRODCTO, MV.CONSECUT AS CONSECUTIVO, TR.DCTOPRV AS DOCUMENTO, TR.FECHA, (LTRIM(RTRIM(TR.NIT)) 
                      + ' / ' + LTRIM(RTRIM(CLI.NOMBRE))) AS TERCERO, MV.BODEGA, MV.PRODUCTO AS CODIGO, MV.NOMBRE AS PRODUCTO, 
                      MV.UNDVENTA AS UNIDAD, MV.NIT AS DET_TERCERO, MV.CANVENTA AS CANTIDAD, 
                      VLR_UNIT = CASE WHEN TR.TIPOMVTO = 'SMT' THEN 0 ELSE MV.VALORUNIT END, 
                      VLR_TOTAL = CASE WHEN TR.TIPOMVTO = 'SMT' THEN 0 ELSE MV.CANVENTA * MV.VALORUNIT END, TR.NOTA AS OBSERVACIONES,
					  MV.NOTA, MV.ORDENNRO, MV.ORDENPRV, MV.CODUBICA 
FROM         TRADE AS TR JOIN
                      MVTRADE AS MV ON TR.NRODCTO = MV.NRODCTO AND TR.ORIGEN = MV.ORIGEN AND TR.TIPOMVTO = MV.TIPOMVTO AND 
                      TR.TIPODCTO = MV.TIPODCTO JOIN
                      TIPOMVTO AS MVTO ON TR.TIPOMVTO = MVTO.TIPOMVTO JOIN
                      MTPROCLI AS CLI ON TR.NIT = CLI.NIT
WHERE     TR.ORIGEN = 'INV'

GO


