--consulata Informe Estado de Pedidos DC FACTURA
SELECT MVTRADE.NPEDIDO, MVTRADE.NRODCTO, MVTRADE.FECHA, MVTRADE.NROORDEN
FROM COLNOTEXSA.dbo.MVTRADE MVTRADE
WHERE (MVTRADE.TIPODCTO in ('FA','FR')) AND (MVTRADE.FECHA>=getdate() -180)
ORDER BY MVTRADE.FECHA DESC, MVTRADE.NRODCTO DESC
--consulata Informe Estado de Pedidos DC NOTA CEDI
SELECT CUMPLIPED.CONSEC, CUMPLIPED.FECHAING, CUMPLIPED.OBSERVA, CUMPLIPED.NRODCTO
FROM COLNOTEXSA.dbo.CUMPLIPED CUMPLIPED
where cumpliped.fechaing >= getdate() -180
order by cumpliped.consec desc
--consulata Informe Estado de Pedidos DC PEDIDOS
SELECT     A.NRODCTO, A.AUTORIZA, A.TIPOVTA, C.DESCRIPCIO, A.NIT, B.NOMBRE, A.CODVEN, D.NOMBRE , A.FECHA, F.FECHAAUT, E.FECENT, 
                      F.HHORAAUT, E.PRODUCTO, E.NOMBRE , E.CANTORIG, E.CANTIDAD , E.CANVENTA , 
                      E.CANTORIG - E.CANVENTA , E.CANTORIG - (E.CANTORIG - E.CANVENTA) , E.VLRVENTA, 
                      E.CANTORIG * E.VLRVENTA , (E.CANTORIG - E.CANVENTA) * E.VLRVENTA , A.NOTA, A.PASSWORDIN, A.HORA, A.FECMOD
FROM         TRADE A INNER JOIN
                      MTPROCLI B ON A.NIT = B.NIT INNER JOIN
                      TIPOVTA C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
                      VENDEN D ON A.CODVEN = D.CODVEN INNER JOIN
                      MVTRADE E ON A.TIPODCTO = E.TIPODCTO AND A.NRODCTO = E.NRODCTO INNER JOIN
                     TRADEMAS F ON A.NRODCTO = F.NRODCTO AND A.ORIGEN = F.ORIGEN AND A.TIPODCTO = F.TIPODCTO
WHERE     (A.TIPODCTO = 'PD') AND (a.FECHA>=getdate() -180)
AND A.TIPOVTA IN ('0-020','0-025','0-027','16','28','0-027','0-028')
AND a.nota not like '%anula%'
ORDER BY E.FECENT DESC, D.NOMBRE
--consulata Informe Estado de Pedidos DC PEDNOAUT
SELECT PEDNOAUT.CONSEC, PEDNOAUT.NRODCTO, PEDNOAUT.OBSERVA
FROM COLNOTEXSA.dbo.PEDNOAUT PEDNOAUT
ORDER BY PEDNOAUT.CONSEC DESC

------ FIN CONSULATAS SQL DE Informe Estado de Pedidos DC
------INICIA QUERYS INFORME Cartera x Und. Negocio Textil Decoracion
--consulata InformeCartera x Und. Negocio Textil Decoracion Conexion
SELECT MTPROCLI.NIT, MTPROCLI.NOMBRE
FROM COLNOTEXSA.dbo.MTPROCLI MTPROCLI
WHERE (MTPROCLI.ESCLIENTE='s')
ORDER BY MTPROCLI.NIT
--consulata InformeCartera x Und. Negocio Textil Decoracion Datos
SELECT vReporteCartera.Cliente, vReporteCartera.Cod_Alterno, vReporteCartera.Canal, vReporteCartera.Nombre_Cliente, vReporteCartera.T_Dcto, vReporteCartera.Documento, vReporteCartera.F_Expedic, vReporteCartera.F_Vencim, vReporteCartera.Tipo_Venta, vReporteCartera.Nombre_Tipo_Venta, vReporteCartera.Nombre_Vendedor, vReporteCartera.Telefono_1, vReporteCartera.Plazo, vReporteCartera.Cupo_Credito, vReporteCartera.Direccion_Cliente, vReporteCartera.Deuda, vReporteCartera.Pagado, vReporteCartera.Saldo
FROM COLNOTEXSA.dbo.vReporteCartera vReporteCartera
------ FIN CONSULATAS SQL DE Cartera x Und. Negocio Textil Decoracion
------INICIA QUERYS INFORME Creacion de Referencias Deko
-----consulata Informe Creacion de Referencias Deko TIPOINV
SELECT TIPOINV.CODIGO, TIPOINV.NOMBRE
FROM COLNOTEXSA.dbo.TIPOINV TIPOINV
-----consulata Informe Creacion de Referencias Deko MTLINEA
SELECT MTLINEA.CODLINEA, MTLINEA.NOMBRE
FROM COLNOTEXSA.dbo.MTLINEA MTLINEA
-----consulata Informe Creacion de Referencias Deko MTSBLIN
SELECT MTSBLIN.CODSBLIN, MTSBLIN.NOMBRE
FROM COLNOTEXSA.dbo.MTSBLIN MTSBLIN
-----consulata Informe Creacion de Referencias Deko MTGRUINV
SELECT MTGRUINV.CODGRUPO, MTGRUINV.NOMBRE
FROM COLNOTEXSA.dbo.MTGRUINV MTGRUINV
-----consulata Informe Creacion de Referencias Deko MTMERCIA
SELECT MTMERCIA.CODIGO, MTMERCIA.CODBARRAS, MTMERCIA.TIPOINV, MTMERCIA.CODLINEA, MTMERCIA.CODSBLIN, MTMERCIA.CODGRUPO, MTMERCIA.CODSUMIN, MTMERCIA.DESCRIP2, MTMERCIA.DESCRIPCIO, MTMERCIA.DESC_LAR, MTMERCIA.DESCRIPCIO, MTMERCIA.REFERPROV
FROM COLNOTEXSA.dbo.MTMERCIA MTMERCIA
-----consulata Informe Creacion de Referencias Deko MTUNIDAD
SELECT MTUNIDAD.NOMBRE, MTUNIDAD.UNIDAD
FROM COLNOTEXSA.dbo.MTUNIDAD MTUNIDAD
-----consulata Informe Creacion de Referencias Deko MTSUMINI
SELECT MTSUMINI.CODSUMIN, MTSUMINI.NOMBRE
FROM COLNOTEXSA.dbo.MTSUMINI MTSUMINI
------ FIN CONSULATAS SQL DE Informe Creacion de Referencias Deko
----INICIA QUERYS INFORME Informe de Clientes Decoracion
-----consulata Informede Clientes Decoracion Resumen
SELECT distinct  a.NIT, a.NOMBRE,a.vendedor,d.nombre, c.nombre, a.DIRECCION,  a.EMAIL, a.TEL1, a.TEL2
FROM COLNOTEXSA.dbo.mtprocli a , COLNOTEXSA.dbo.trade b ,ciudad c, VENDEN D
WHERE b.nit =a.nit
and b.TIPOVTA  In ('0-020','0-025','16','28')
and c.CODCIUDAD= a.ciudad
and a.VENDEDOR=d.CODVEN
AND a.HABILITADO='S' AND a.ESCLIENTE='S'
------ FIN CONSULATAS SQL DE Informe Clientes Decoracion
----INICIA QUERYS Informe de Ordenes de Compra
SELECT     A.NRODCTO,a.DCTOPRV, B.BODEGA, A.TIPODCTO, A.NIT, C.NOMBRE, A.FECHA, A.FECING, B.FECENT, A.AUTORIZA, B.PRODUCTO, B.NOMBRE , 
                      B.CANTIDAD, B.CANTORIG , B.CANVENTA , B.VALORUNIT, B.CANTORIG * B.VALORUNIT , b.nota AS NOTA_MV, A.NOTA
FROM         TRADE A INNER JOIN
                      MTPROCLI C ON A.NIT = C.NIT INNER JOIN
                      MVTRADE B ON A.NRODCTO = B.NRODCTO AND A.TIPODCTO = B.TIPODCTO
WHERE     (A.ORIGEN = 'COM') AND (A.TIPODCTO = 'OR') AND (B.BODEGA IN ('02.TL.DECO'))
AND A.FECHA >= getdate() - 180
ORDER BY A.nrodcto DESC
---FIN CONSULATAS SQL DE Informe de Ordenes de Compra
----INICIA QUERYS Ecxel Informe de Preventa DC
-----consulata Informe de Preventa DC FACTURA
SELECT MVTRADE.NPEDIDO, MVTRADE.NRODCTO, MVTRADE.FECHA, MVTRADE.NROORDEN
FROM COLNOTEXSA.dbo.MVTRADE MVTRADE
WHERE (MVTRADE.TIPODCTO='FA') AND (MVTRADE.FECHA>= GETDATE() -180)
ORDER BY MVTRADE.FECHA DESC, MVTRADE.NRODCTO DESC
-----consulata Informe de Preventa DC PEDIDOS
SELECT     A.NRODCTO, A.AUTORIZA, A.TIPOVTA, C.DESCRIPCIO, A.NIT, B.NOMBRE, A.CODVEN, D.NOMBRE , A.FECHA, S.FECHAAUT, E.FECENT, 
                      S.HHORAAUT, E.PRODUCTO, E.NOMBRE , E.CANTORIG, E.CANTIDAD , E.CANVENTA , 
                      E.CANTORIG - E.CANVENTA , E.CANTORIG - (E.CANTORIG - E.CANVENTA) , E.VLRVENTA, 
                      E.CANTORIG * E.VLRVENTA , (E.CANTORIG - E.CANVENTA) * E.VLRVENTA , A.NOTA, A.PASSWORDIN
FROM         TRADE A INNER JOIN
                      MTPROCLI B ON A.NIT = B.NIT INNER JOIN
                      TIPOVTA C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
                      VENDEN D ON A.CODVEN = D.CODVEN INNER JOIN
                      MVTRADE E ON A.TIPODCTO = E.TIPODCTO AND A.NRODCTO = E.NRODCTO INNER JOIN
					  TRADEMAS S ON A.NRODCTO = S.NRODCTO

WHERE     (A.TIPODCTO = 'PD') AND (A.FECHA >= GETDATE() -180)
AND A.TIPOVTA IN ('0-091')
ORDER BY A.FECHA DESC, D.NOMBRE
-----consulata Informe de Preventa DC PEDNOAUT
SELECT PEDNOAUT.CONSEC, PEDNOAUT.NRODCTO, PEDNOAUT.OBSERVA
FROM COLNOTEXSA.dbo.PEDNOAUT PEDNOAUT
---FIN CONSULATAS SQL DE Ecxel Informe Preventa DC 
----INICIA QUERYS Ecxel Informe de Separacion x Tercero
----consulata Informe de Separacion x Tercero MTCAMBIO
SELECT     FECHA, VALOR
FROM         MTCAMBIO MTCAMBIO
WHERE     (FECHA BETWEEN DATEADD(yy, DATEDIFF(yy, 0, GETDATE()), 0) AND DATEADD(ms, - 3, DATEADD(mm, DATEDIFF(m, 0, GETDATE()) + 1, 0)))
----consulata Informe de Separacion x Tercero Datos Detallados
SELECT A.NIT, C.NOMBRE, A.CODIGO, B.DESCRIPCIO, B.CODGRUPO, D.NOMBRE, B.CODLINEA, E.NOMBRE, B.TIPOINV, F.NOMBRE, A.ICANTIDAD, A.OCANTIDAD, (ICANTIDAD-OCANTIDAD) AS 'SALDO'
FROM COLNOTEXSA.dbo.saldoinv A, COLNOTEXSA.dbo.MTMERCIA B, COLNOTEXSA.dbo.MTPROCLI C, COLNOTEXSA.dbo.MTGRUINV D, COLNOTEXSA.dbo.MTLINEA E, COLNOTEXSA.dbo.TIPOINV F
WHERE A.NIT = C.NIT AND A.CODIGO = B.CODIGO AND ((B.CODGRUPO=D.CODGRUPO) AND (B.CODLINEA=E.CODLINEA) AND (B.TIPOINV=F.CODIGO) AND ((ICANTIDAD-OCANTIDAD)<>'0'))
ORDER BY A.NIT, A.CODIGO
----consulata Informe de Separacion x Tercero Datos Resumidos
SELECT A.NIT, C.NOMBRE, A.CODIGO, B.DESCRIPCIO, B.CODGRUPO, D.NOMBRE, B.CODLINEA, E.NOMBRE, B.TIPOINV, F.NOMBRE, Sum(A.ICANTIDAD-A.OCANTIDAD) AS 'SALDO', C.VENDEDOR, G.NOMBRE, B.COSTO_ING, B.COSTO_USDR, B.FACTORR, B.COSTO_UFR
FROM COLNOTEXSA.dbo.saldoinv A, COLNOTEXSA.dbo.MTMERCIA B, COLNOTEXSA.dbo.MTPROCLI C, COLNOTEXSA.dbo.MTGRUINV D, COLNOTEXSA.dbo.MTLINEA E, COLNOTEXSA.dbo.TIPOINV F, COLNOTEXSA.dbo.VENDEN G
WHERE A.NIT = C.NIT AND A.CODIGO = B.CODIGO 
AND ((A.BODEGA In ('06.TL.SEPA','18.CLIENTES','50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA')) 
AND (B.CODGRUPO=D.CODGRUPO) 
AND (B.CODLINEA=E.CODLINEA)
 AND (B.TIPOINV=F.CODIGO) 
AND ((ICANTIDAD-OCANTIDAD)<>'0') 
AND (C.VENDEDOR=G.CODVEN))
GROUP BY A.NIT, C.NOMBRE, A.CODIGO, B.DESCRIPCIO, B.CODGRUPO, D.NOMBRE, B.CODLINEA, E.NOMBRE, B.TIPOINV, F.NOMBRE, C.VENDEDOR, G.NOMBRE, B.COSTO_ING, B.COSTO_USDR, B.FACTORR, B.COSTO_UFR
HAVING (Sum(A.ICANTIDAD-A.OCANTIDAD)<>0)
ORDER BY A.NIT, A.CODIGO
----consulata Informe de Separacion x Tercero Datos x Mov
SELECT     A.BODEGA, A.TIPOMVTO, A.NIT, C.NOMBRE, A.FECHA, A.PRODUCTO, A.NOMBRE , A.CANTIDAD, a.nrodcto, B.NOTA
FROM         MVTRADE A INNER JOIN
                      TRADE B ON A.NRODCTO = B.NRODCTO INNER JOIN
                      MTPROCLI C ON A.NIT = C.NIT AND A.TIPODCTO = B.TIPODCTO AND A.TIPOMVTO = B.TIPOMVTO
WHERE     (A.BODEGA IN ('06.TL.SEPA','18.CLIENTES','50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA')) 
AND (a.FECHA BETWEEN DATEADD(yy, DATEDIFF(yy, 0, GETDATE()), 0) 
AND DATEADD(ms, - 3, DATEADD(mm, DATEDIFF(m, 0, GETDATE()) + 1, 0)))
----consulata Informe de Separacion x Tercero Notas
SELECT TRADE.NRODCTO, Max(TRADE.FECHA), TRADE.NOTA
FROM COLNOTEXSA.dbo.TRADE TRADE
WHERE (TRADE.TIPOMVTO In ('est')) AND (trade.FECHA BETWEEN DATEADD(yy, DATEDIFF(yy, 0, GETDATE()), 0) 
AND DATEADD(ms, - 3, DATEADD(mm, DATEDIFF(m, 0, GETDATE()) + 1, 0)))
GROUP BY TRADE.NRODCTO, TRADE.NOTA
ORDER BY TRADE.NRODCTO
---FIN CONSULATAS SQL DE Ecxel Informe de Separacion x Tercero
----INICIA QUERYS Ecxel Informe de Ventas por Ciudad - Cliente - Vendedor DC
----consulata Informe de Ventas por Ciudad - Cliente - Vendedor DC 2021, 2022 ETC
SELECT distinct a.FECHA,DATENAME ( month , a.FECHA ) as Mes, a.TIPOVTA, b.DESCRIPCIO, a.TIPODCTO, a.NRODCTO, d.CIUDAD,f.nombre, a.NIT, d.NOMBRE AS 'CLIENTE', a.CODVEN, c.NOMBRE, a.BRUTO, 
((A.BRUTO-A.DESCUENTO)/1000) AS 'SUBT', e.UNDBASE, e.CANVENTA,e.producto,e.nombre,e.valorunit,(e.CANVENTA*e.valorunit) AS 'vlrtotal'
FROM COLNOTEXSA.dbo.trade a, 
COLNOTEXSA.dbo.tipovta b, 
COLNOTEXSA.dbo.venden c, 
COLNOTEXSA.dbo.mtprocli d, 
COLNOTEXSA.dbo.mvtrade e,
COLNOTEXSA.dbo.ciudad f

WHERE (a.NRODCTO=e.nrodcto) AND (a.TIPODCTO=e.tipodcto 
And a.TIPODCTO Not In ('P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12','14','15','16','17','18','19','20','21','AJ')) 
AND (a.ORIGEN='FAC') AND (a.NIT=d.nit) AND (a.TIPOVTA=b.tipovta 
And a.TIPOVTA In ('0-020','0-025','16','28')) 
AND (c.CODVEN=a.codven) 
AND (d.CIUDAD=f.codciudad) 
AND (a.FECHA>'01/01/2022' And a.FECHA<='31/12/2022')


ORDER BY a.FECHA DESC, b.DESCRIPCIO DESC, a.TIPODCTO, a.NRODCTO
---FIN CONSULATAS SQL DE Ecxel Informe de Ventas por Ciudad - Cliente - Vendedor DC
----INICIA QUERYS Ecxel Informe Documentos NC - H5 - R2
select a.tipodcto,a.fecha,year(a.fecha)as año,a.nrodcto,a.nit,c.nombre as cliente, a.Nota, a.TRANSPORTA,b.producto,b.nombre,b.detalle,b.cantidad,A.ORIGEN
from trade a, mvtrade b, mtprocli c
where a.tipodcto ='nc' and b.tipodcto ='nc'
and a.nit = c.nit
and a.nrodcto =b.nrodcto
AND (a.fecha>= '01-01-2022')
AND A.ORIGEN='fac'
order by año desc, a.nrodcto desc
---FIN CONSULATAS SQL DE Ecxel Informe Documentos NC - H5 - R2
---INICIA QUERYS Ecxel Informe Facturacion Decoracion Detallado
SELECT A.FECHA, month(A.FECHA) AS 'mes', A.TIPODCTO, A.NRODCTO, A.REMISION AS 'PEDIDO', A.NIT, D.NOMBRE AS 'CLIENTE', I.NOMBRE AS 'CIUDAD', A.TIPOVTA, B.DESCRIPCIO, C.NOMBRE AS 'VENDEDOR', E.PRODUCTO, E.NOMBRE, E.CANTIDAD, E.VALORUNIT, (E.CANTIDAD*E.VALORUNIT) AS 'TOTALVTA'
FROM COLNOTEXSA.dbo.TRADE A, COLNOTEXSA.dbo.TIPOVTA B, COLNOTEXSA.dbo.VENDEN C, COLNOTEXSA.dbo.MTPROCLI D, COLNOTEXSA.dbo.MVTRADE E, COLNOTEXSA.dbo.MTCAMBIO F, COLNOTEXSA.dbo.MTMERCIA G, COLNOTEXSA.dbo.MTGRUINV H, COLNOTEXSA.dbo.CIUDAD I
WHERE I.CODCIUDAD = D.CIUDAD AND ((A.ORIGEN='FAC' And A.ORIGEN=E.ORIGEN) 
AND (A.TIPODCTO Not In ('P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12',
'14','15','16','17','18','19','20','21','AJ','EP','CT','OP','OR','OF','OT','OM') And A.TIPODCTO=E.TIPODCTO) 
AND (A.FECHA Between '01/01/2023' And '31/12/2023' And A.FECHA=F.FECHA) AND (A.NRODCTO=E.NRODCTO) 
AND (A.TIPOVTA=B.TIPOVTA And A.TIPOVTA In ('0-020','0-025','16','28')) AND (E.PRODUCTO=G.CODIGO) 
AND (G.CODGRUPO=H.CODGRUPO) AND (A.NIT=D.NIT) AND (A.CODVEN=C.CODVEN) AND (E.CANTIDAD>0))
ORDER BY A.FECHA, A.NRODCTO
---FIN CONSULATAS SQL DE Ecxel Informe Facturacion Decoracion Detallado
---INICIA QUERYS Ecxel Informe Gerencial DC 2023
----consulata Informe Gerencial DC 2023 ClientesCiudad
SELECT        A.NIT, A.NOMBRE, A.CIUDAD, B.NOMBRE AS Expr1
FROM            MTPROCLI AS A INNER JOIN
                         CIUDAD AS B ON A.CIUDAD = B.CODCIUDAD
WHERE        (A.ESCLIENTE = 'S')
----consulata Informe Gerencial DC 2023 Datos
SELECT a.FECHA, a.TIPODCTO, a.TIPOVTA, b.DESCRIPCIO, c.NOMBRE, a.BRUTO, ((A.BRUTO-A.DESCUENTO)/1000) AS 'SUBT'
FROM COLNOTEXSA.dbo.trade a, COLNOTEXSA.dbo.tipovta b, COLNOTEXSA.dbo.venden c
WHERE (a.ORIGEN='FAC') AND (a.TIPOVTA=b.tipovta And a.TIPOVTA In ('0-020','0-025','16','28')) AND (c.CODVEN=a.codven) AND (a.TIPODCTO Not In ('P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12','14','15','16','17','18','19','20','21','AJ','EP','CT','OP','OR','OF','OT','OM')) AND (a.FECHA>'01/01/2023' And a.FECHA<='31/12/2023')
ORDER BY a.TIPODCTO
----consulata Informe Gerencial DC 2023 Datoscliente
SELECT     a.FECHA, a.TIPODCTO, d.NOMBRE, a.TIPOVTA, b.DESCRIPCIO, c.NOMBRE , a.BRUTO, ((a.BRUTO - a.DESCUENTO)/1000) 
FROM         TRADE a INNER JOIN
                      TIPOVTA b ON a.TIPOVTA = b.TIPOVTA INNER JOIN
                      VENDEN c ON a.CODVEN = c.CODVEN INNER JOIN
                      MTPROCLI d ON a.NIT = d.NIT
WHERE     (a.ORIGEN = 'FAC') AND (a.TIPODCTO Not In ('P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12','14','15','16','17','18','19','20','21','AJ','EP','CT','OP','OR','OF','OT','OM')) AND (a.FECHA  BETWEEN '01/01/2023' AND '31/12/2023')
AND A.TIPOVTA IN ('0-020','0-025','16','28')
ORDER BY    a.FECHA
----consulata Informe Gerencial DC 2023 DatosProd
SELECT A.FECHA, A.TIPODCTO, A.NRODCTO, D.NOMBRE, A.TIPOVTA, B.DESCRIPCIO, C.NOMBRE, E.PRODUCTO, E.NOMBRE, E.CANTIDAD, E.VALORUNIT, (E.CANTIDAD*E.VALORUNIT) AS 'TOTALVTA', G.COSTO_ING, G.COSTO_USD, G.FACTOR, F.VALOR, E.DESCUENTO
FROM COLNOTEXSA.dbo.TRADE A, COLNOTEXSA.dbo.TIPOVTA B, COLNOTEXSA.dbo.VENDEN C, COLNOTEXSA.dbo.MTPROCLI D, COLNOTEXSA.dbo.MVTRADE E, COLNOTEXSA.dbo.MTCAMBIO F, COLNOTEXSA.dbo.MTMERCIA G, COLNOTEXSA.dbo.MTGRUINV H
WHERE (A.ORIGEN='FAC' And A.ORIGEN=E.ORIGEN)
AND (A.TIPODCTO Not In ('P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12','14','15','16','17','18','19','20','21','AJ','EP','CT','OP','OR','OF','OT','OM') 
And A.TIPODCTO=E.TIPODCTO) 
AND (A.FECHA Between '01/01/2023' And '31/12/2023' And A.FECHA=F.FECHA) 
AND (A.NRODCTO=E.NRODCTO) 
AND (A.TIPOVTA=B.TIPOVTA 
And A.TIPOVTA In ('0-020','0-025','16','28')) 
AND (E.PRODUCTO=G.CODIGO) 
AND (G.CODGRUPO=H.CODGRUPO) 
AND (A.NIT=D.NIT) AND (A.CODVEN=C.CODVEN) 
AND (E.CANTIDAD>0)
ORDER BY A.FECHA, A.NRODCTO
---FIN CONSULATAS SQL DE Ecxel Gerencial DC 2023
---INICIA QUERYS Ecxel Informe solicitudes SP y SM
----consulata Informe solicitudes SP y SM Datos J9
SELECT     A.NRODCTO, B.DCTOPRV, E.DESCRIPCIO, A.FECHA, MONTH(A.FECHA) , B.NIT, C.NOMBRE, D.NOMBRE , A.PRODUCTO, 
                      A.NOMBRE , A.CANTIDAD, B.BRUTO - B.DESCUENTO, A.tipodcto, B.NOTA, A.CANTORIG
FROM         MVTRADE A INNER JOIN
                      TRADE B ON A.NRODCTO = B.NRODCTO AND A.TIPODCTO = B.TIPODCTO INNER JOIN
                      MTPROCLI C ON B.NIT = C.NIT INNER JOIN
                      CIUDAD D ON C.CIUDAD = D.CODCIUDAD INNER JOIN
                      TIPOVTA E ON B.TIPOVTA = E.TIPOVTA
WHERE     (A.ORIGEN = 'inv') AND (A.TIPODCTO in ('J1','J9','i8')) AND (A.FECHA >= getdate()-180)
ORDER BY A.FECHA, A.NRODCTO
----consulata Informe solicitudes SP y SM Datos SM
SELECT     A.NRODCTO, E.DESCRIPCIO, A.FECHA, MONTH(A.FECHA) , B.NIT, C.NOMBRE, D.NOMBRE , A.PRODUCTO, 
                      A.NOMBRE , A.CANTORIG, B.BRUTO - B.DESCUENTO, A.tipodcto, B.NOTA
FROM         MVTRADE A INNER JOIN
                      TRADE B ON A.NRODCTO = B.NRODCTO AND A.TIPODCTO = B.TIPODCTO INNER JOIN
                      MTPROCLI C ON B.NIT = C.NIT INNER JOIN
                      CIUDAD D ON C.CIUDAD = D.CODCIUDAD INNER JOIN
                      TIPOVTA E ON B.TIPOVTA = E.TIPOVTA
WHERE     (A.ORIGEN = 'inv') AND (A.TIPODCTO in ('SM','SP')) AND (A.FECHA >= getdate()-180)
AND A.CODCC = '0126'
ORDER BY A.FECHA DESC, A.NRODCTO
---FIN CONSULATAS SQL DE Ecxel solicitudes SP y SM
---INICIA QUERYS Ecxel Inventario Decoracion
----consulata Informe Inventario Decoracion DatosOR
SELECT     A.PRODUCTO, B.DESCRIPCIO, A.FECENT, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.CODGRUPO, F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN, H.DCTOPRV, I.NOMBRE
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO INNER JOIN
                      TRADE H ON A.NRODCTO = H.NRODCTO AND A.TIPODCTO = H.TIPODCTO INNER JOIN
                      MT2CLAF I ON B.CLASIFICA2 = I.CODIGO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB',
'18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI',
'51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2',
'62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO','71.BONDEOPT','72.BONDEOMP'))
AND (A.TIPODCTO IN ('OR')) 
AND B.TIPOINV IN ('TL020','TL025','TL026','TL027')
AND  A.FECHA >= '1/1/2022'  
AND A.NRODCTO LIKE '8%'
AND A.NOTA <> 'CEDI'
ORDER BY A.PRODUCTO
----consulata Informe Inventario Decoracion Inv. Fisico
SELECT     A.BODEGA, E.NOMBRE, D.NOMBRE, B.CODGRUPO, C.NOMBRE, A.CODIGO, B.DESCRIPCIO, SUM(A.ICANTIDAD - A.OCANTIDAD) 
FROM         SALDOINV A INNER JOIN
                   MTMERCIA B ON A.CODIGO = B.CODIGO INNER JOIN
                   MTGRUINV C ON B.CODGRUPO = C.CODGRUPO INNER JOIN
                   MTSBLIN D ON B.CODSBLIN = D.CODSBLIN  INNER JOIN
                  MT2CLAF E ON B.CLASIFICA2 = E.CODIGO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB',
'18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI',
'50. VT. SEPA','51. DC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2',
'62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO','71.BONDEOPT','72.BONDEOMP'))
AND B.TIPOINV IN ('TL020','TL025','TL026','TL027')

GROUP BY A.BODEGA, E.NOMBRE, D.NOMBRE, B.CODGRUPO, C.NOMBRE, A.CODIGO, B.DESCRIPCIO
ORDER BY C.NOMBRE, B.DESCRIPCIO
----consulata Informe Inventario Decoracion Pedidos
SELECT     BODEGA, PRODUCTO, SUM(CANVENTA) 
FROM         MVTRADE
WHERE     (TIPODCTO = 'PD')  and  (BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB',
'18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI',
'50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2',
'62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO','71.BONDEOPT','72.BONDEOMP'))
AND (CANVENTA >= '0')
AND FECHA >'01-01-2021'
GROUP BY BODEGA, PRODUCTO, CANVENTA
ORDER BY BODEGA, PRODUCTO, CANVENTA
---FIN CONSULATAS SQL DE Ecxel Informe Inventario Decoracion
---INICIA QUERYS Ecxel NC Decoracion
select TRADE.NRODCTO,TRADE.TIPODCTO,TIPOVTA.DESCRIPCIO,TRADE.FECHA,TRADE.NIT,MTPROCLI.NOMBRE,
VENDEN.NOMBRE AS VENDEDOR,MVTRADE.NOMBRE,MVTRADE.CANTIDAD,MVTRADE.VLRVENTA,TRADE.NOTA
from trade trade , MVTRADE MVTRADE ,MTPROCLI MTPROCLI,VENDEN VENDEN,TIPOVTA tipovta
where TRADE.tipodcto ='NC' and TRADE.fecha > '01-01-2022'
AND TRADE.NRODCTO=MVTRADE.NRODCTO AND TRADE.TIPODCTO=MVTRADE.TIPODCTO
and MTPROCLI.NIT=TRADE.NIT
AND VENDEN.CODVEN= TRADE.CODVEN
and tipovta.tipovta=trade.tipovta
and trade.tipovta in ('0-020','0-025','16','28')
order by TRADE.FECHA desc
---FIN CONSULATAS SQL DE Ecxel NC Decoracion
---INICIA QUERYS EcxelSeguimiento Anticipos V2
----consulata Informe Seguimiento Anticipos V2 query uno
SELECT v_seguimiento_anticipos.nrodcto, v_seguimiento_anticipos.fecha_exp, v_seguimiento_anticipos.fecha_ven, v_seguimiento_anticipos.cliente, v_seguimiento_anticipos.deuda, v_seguimiento_anticipos.pagado, v_seguimiento_anticipos.saldo, v_seguimiento_anticipos.RESPONSABLE, v_seguimiento_anticipos.nota
FROM COLNOTEXSA.dbo.v_seguimiento_anticipos v_seguimiento_anticipos
----consulata Informe Seguimiento Anticipos V2 query dos
SELECT v_seguimiento_anticipos.nrodcto, v_seguimiento_anticipos.fecha_exp, v_seguimiento_anticipos.fecha_ven, v_seguimiento_anticipos.cliente, v_seguimiento_anticipos.deuda, v_seguimiento_anticipos.pagado, v_seguimiento_anticipos.saldo, v_seguimiento_anticipos.RESPONSABLE, v_seguimiento_anticipos.nota
FROM COLNOTEXSA.dbo.v_seguimiento_anticipos v_seguimiento_anticipos
---FIN CONSULATAS SQL DE Ecxel Informe Seguimiento Anticipos
---INICIA QUERYS Ecxel Informe Rotacion Inv. Consignacion Exito
----consulata Informe Rotacion Inv. Consignacion Exito DATOS2021
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('46.CONSEXITO'))
AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG','SRM'))
AND (B.TIPOINV IN ('PT005')) 
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','PD','OR','FR')) 
AND  A.FECHA >= '1/1/2021'  AND  A.FECHA <= '31/12/2021' 

ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Consignacion Exito DATOS2022
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('46.CONSEXITO'))
AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG','SRM'))
AND (B.TIPOINV IN ('PT005')) 
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','PD','OR','FR')) 
AND  A.FECHA >= '1/1/2022'  AND  A.FECHA <= '31/12/2022' 

ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Consignacion Exito DATOS2023
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('46.CONSEXITO'))
AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG','SRM'))
AND (B.TIPOINV IN ('PT005')) 
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','PD','OR','FR')) 
AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 

ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Consignacion Exito Maestro_Mercancias
SELECT MTMERCIA.CODIGO, MTMERCIA.DESCRIPCIO, MTMERCIA.COSTO_ING
FROM COLNOTEXSA.dbo.MTMERCIA MTMERCIA
WHERE (MTMERCIA.TIPOINV='PT005')
----consulata Informe Rotacion Inv. Consignacion Exito TIPOMVTO
SELECT TIPOMVTO.TIPOMVTO, TIPOMVTO.CODINT, TIPOMVTO.ENTRADA, TIPOMVTO.DESCRIPCIO, TIPOMVTO.TRASLADO
FROM COLNOTEXSA.dbo.TIPOMVTO TIPOMVTO
---FIN CONSULATAS SQL DE Ecxel Informe Rotacion Inv. Consignacion Exito
---INICIA QUERYS Ecxel Informe Rotacion Inv. Cortineria
----consulata Informe Rotacion Inv. Cortineria 01. Datos
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB','18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI','50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2','62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO'))

AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG')) 
AND (B.TIPOINV IN ('TL025')) 
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','PD','OR','RE')) 
AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 
ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Cortineria 02. Datos_Fh_Ingreso
SELECT         A.PRODUCTO, A.NOMBRE, A.FECHA
FROM            MVTRADE AS A INNER JOIN
                         TRADE AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO INNER JOIN
                         MTMERCIA AS C ON A.PRODUCTO = C.CODIGO
WHERE        (A.FECHA >= '01/01/2000') AND (A.TIPODCTO = 'A3')
AND C.TIPOINV IN ('TL025')

ORDER BY A.FECHA DESC
----consulata Informe Rotacion Inv. Cortineria 03. Datos Pedidos
SELECT   A.NRODCTO, A.FECHA, A.NIT, B.BODEGA, B.PRODUCTO, SUM(B.CANVENTA) 
FROM         MVTRADE B, TRADE A
WHERE     (B.TIPODCTO = 'PD') AND (B.BODEGA = ('02.TL.DECO')) AND (B.CANVENTA >= '0')
AND A.FECHA >= getdate()-60
AND A.NRODCTO = B.NRODCTO
AND A.TIPODCTO = B.TIPODCTO
GROUP BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA
ORDER BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA
----consulata Informe Rotacion Inv. Cortineria Datos1
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB','18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI','50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2','62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO'))

AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG')) 
AND (B.TIPOINV IN ('TL025')) 
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','RE','PD','OR')) 
AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 
ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Cortineria Tipomvto
SELECT TIPOMVTO.TIPOMVTO, TIPOMVTO.CODINT, TIPOMVTO.ENTRADA, TIPOMVTO.DESCRIPCIO, TIPOMVTO.TRASLADO
FROM COLNOTEXSA.dbo.TIPOMVTO TIPOMVTO
---FIN CONSULATAS SQL DE Ecxel Informe Rotacion Inv. Cortineria
---INICIA QUERYS EcxelInforme Rotacion Inv. Dispositivos Medicos
----consulata Informe Rotacion Inv. Dispositivos Medicos 01. Datos
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('85.MPTAP.CUA','86.MPTAP.APR','87.MPTAP.RECH','88.PPTAP.APR','89.PTTAP.CUA','90.PTTAP.APR','91.PTTAP.RECH','92.TELASBIOS','94.PTTAP.DESP'))
AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG')) 
AND (B.TIPOINV IN ('TPB00','PT040')) 
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','PD','OR','RE','OP')) 
AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 
ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Dispositivos Medicos 02. Datos_Fh_Ingreso
SELECT         A.PRODUCTO, A.NOMBRE, A.FECHA
FROM            MVTRADE AS A INNER JOIN
                         TRADE AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO INNER JOIN
                         MTMERCIA AS C ON A.PRODUCTO = C.CODIGO
WHERE        (A.FECHA >= '01/01/2000') AND (A.TIPODCTO = 'A3')
AND C.TIPOINV IN ('TL025')

ORDER BY A.FECHA DESC
----consulata Informe Rotacion Inv. Dispositivos Medicos 03. Datos Pedidos
SELECT   A.NRODCTO, A.FECHA, A.NIT, B.BODEGA, B.PRODUCTO, SUM(B.CANVENTA) 
FROM         MVTRADE B, TRADE A
WHERE     (B.TIPODCTO = 'PD') AND (B.BODEGA = ('92.TELASBIOS')) AND (B.CANVENTA >= '0')
AND A.FECHA >= getdate()-60
AND A.NRODCTO = B.NRODCTO
AND A.TIPODCTO = B.TIPODCTO
GROUP BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA
ORDER BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA
----consulata Informe Rotacion Inv. Dispositivos Medicos Datos1
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('85.MPTAP.CUA','86.MPTAP.APR','87.MPTAP.RECH','88.PPTAP.APR','89.PTTAP.CUA','90.PTTAP.APR','91.PTTAP.RECH','92.TELASBIOS','94.PTTAP.DESP'))
AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG')) 
AND (B.TIPOINV IN ('TPB0025','PT040')) 
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','RE','PD','OR','OP')) 
AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 
ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Dispositivos Medicos Tipomvto
SELECT TIPOMVTO.TIPOMVTO, TIPOMVTO.CODINT, TIPOMVTO.ENTRADA, TIPOMVTO.DESCRIPCIO, TIPOMVTO.TRASLADO
FROM COLNOTEXSA.dbo.TIPOMVTO TIPOMVTO
---FIN CONSULATAS SQL DE Ecxel Informe Rotacion Inv. Dispositivos Medicos
---INICIA QUERYS Ecxel Informe Rotacion Inv. Fibras y Plumas
----consulata Informe Rotacion Inv. Fibras y Plumas Datos 1
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB','18.CLIENTES','13.FIBRAS','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI','49.CUARENTENA','50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2','62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO','71.BONDEOPT','72.BONDEOMP','76.FIBRASCD'))

AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG','SRM'))

AND (B.TIPOINV IN ('FB001')) 

AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','PD','OR','RE')) 

AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 

ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Fibras y Plumas 02. Datos_Fh_Ingreso
SELECT         A.PRODUCTO, A.NOMBRE, A.FECHA
FROM            MVTRADE AS A INNER JOIN
                         TRADE AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO INNER JOIN
                         MTMERCIA AS C ON A.PRODUCTO = C.CODIGO
WHERE        (A.FECHA >= '01/01/2000') AND (A.TIPODCTO = 'A3')
AND (C.TIPOINV IN ('FB001')) 
ORDER BY A.FECHA DESC
----consulata Informe Rotacion Inv. Fibras y Plumas 03. Datos Pedidos
SELECT   A.NRODCTO, A.FECHA, A.NIT, B.BODEGA, B.PRODUCTO, SUM(B.CANVENTA) 
FROM         MVTRADE B, TRADE A
WHERE     (B.TIPODCTO = 'PD') AND (B.BODEGA in ('13.FIBRAS','76.FIBRASCD')) AND (B.CANVENTA >= '0')
AND A.FECHA >= getdate()-60
AND A.NRODCTO = B.NRODCTO
AND A.TIPODCTO = B.TIPODCTO
GROUP BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA
ORDER BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA
----consulata Informe Rotacion Inv. Fibras y PlumasDatos1
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB','18.CLIENTES','13.FIBRAS','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI','50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2','62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO','71.BONDEOPT','72.BONDEOMP','76.FIBRASCD'))
AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG','SRM'))
AND (B.TIPOINV IN ('FB001')) 
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','RE','PD','OR')) 
AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 
ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Fibras y Plumas Tipomvto
SELECT TIPOMVTO.TIPOMVTO, TIPOMVTO.CODINT, TIPOMVTO.ENTRADA, TIPOMVTO.DESCRIPCIO, TIPOMVTO.TRASLADO
FROM COLNOTEXSA.dbo.TIPOMVTO TIPOMVTO
---FIN CONSULATAS SQL DE Ecxel Informe Rotacion Inv. Fibras y Plumas
---INICIA QUERYS Ecxel Informe Rotacion Inv. Genero Colchon
----consulata Informe Rotacion Inv. Genero Colchon 01. Datos
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB','18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI','50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2','62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO'))

AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG')) 
AND (B.TIPOINV IN ('TL035')) 
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','PD','OR','RE')) 
AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 
ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Genero Colchon 02. Datos_Fh_Ingreso
SELECT         A.PRODUCTO, A.NOMBRE, A.FECHA
FROM            MVTRADE AS A INNER JOIN
                         TRADE AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO INNER JOIN
                         MTMERCIA AS C ON A.PRODUCTO = C.CODIGO
WHERE        (A.FECHA >= '01/01/2000') AND (A.TIPODCTO = 'A3')
AND C.TIPOINV = 'TL035'

ORDER BY A.FECHA DESC
----consulata Informe Rotacion Inv. Genero Colchon 03. Datos Pedidos
SELECT   A.NRODCTO, A.FECHA, A.NIT, B.BODEGA, B.PRODUCTO, SUM(B.CANVENTA) 
FROM         MVTRADE B, TRADE A
WHERE     (B.TIPODCTO = 'PD') AND (B.BODEGA = ('01.TL.GENE')) AND (B.CANVENTA >= '0')
AND A.FECHA >= getdate()-60
AND A.NRODCTO = B.NRODCTO
AND A.TIPODCTO = B.TIPODCTO
GROUP BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA
ORDER BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA
----consulata Informe Rotacion Inv. Genero Colchon Datos1
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB','18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI','50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2','62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO'))

AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG')) 
AND (B.TIPOINV IN ('TL035')) 
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','RE','PD','OR')) 
AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 
ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Genero Colchon Tipomvto
SELECT TIPOMVTO.TIPOMVTO, TIPOMVTO.CODINT, TIPOMVTO.ENTRADA, TIPOMVTO.DESCRIPCIO, TIPOMVTO.TRASLADO
FROM COLNOTEXSA.dbo.TIPOMVTO TIPOMVTO
---FIN CONSULATAS SQL DE Ecxel Informe Rotacion Inv. Genero Colchon
---INICIA QUERYS Ecxel Informe Rotacion Inv. Genero Estampado DI
----consulata Informe Rotacion Inv. Genero Estampado DI 01. Datos
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB','18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI','50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2','62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO'))

AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG','SAT','EPT'))
AND (B.TIPOINV IN ('TL005')) 
AND B.CLASIFICA1 IN ('TGE02')
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','PD','OR','RE')) 
AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 
ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Genero Estampado DI 02. Datos_Fh_Ingreso
SELECT         A.PRODUCTO, A.NOMBRE, A.FECHA
FROM            MVTRADE AS A INNER JOIN
                         TRADE AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO INNER JOIN
                         MTMERCIA AS C ON A.PRODUCTO = C.CODIGO
WHERE        (A.FECHA >= '01/01/2000') AND (A.TIPODCTO = 'A3')
AND C.TIPOINV = 'TL005'

ORDER BY A.FECHA DESC
----consulata Informe Rotacion Inv. Genero Estampado DI 03. Datos Pedidos
SELECT   A.NRODCTO, A.FECHA, A.NIT, B.BODEGA, B.PRODUCTO, SUM(B.CANVENTA) 
FROM         MVTRADE B, TRADE A
WHERE     (B.TIPODCTO = 'PD') AND (B.BODEGA = ('01.TL.GENE')) AND (B.CANVENTA >= '0')
AND A.FECHA >= getdate()-60
AND A.NRODCTO = B.NRODCTO
AND A.TIPODCTO = B.TIPODCTO
GROUP BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA
ORDER BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA
----consulata Informe Rotacion Inv. Genero Estampado DI Datos1
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB','18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI','50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2','62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO'))

AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG','SAT','EPT'))
AND (B.TIPOINV IN ('TL005')) 
AND B.CLASIFICA1  IN ('TGE02')
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','RE','PD','OR')) 
AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 
ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Genero Estampado DI  Tipomvto
SELECT TIPOMVTO.TIPOMVTO, TIPOMVTO.CODINT, TIPOMVTO.ENTRADA, TIPOMVTO.DESCRIPCIO, TIPOMVTO.TRASLADO
FROM COLNOTEXSA.dbo.TIPOMVTO TIPOMVTO
---FIN CONSULATAS SQL DE Ecxel Informe Rotacion Inv. Genero Estampado DI
---INICIA QUERYS Ecxel Informe Rotacion Inv. Genero Estampado PT
----consulata Informe Rotacion Inv. Genero Estampado PT 01. Datos
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB','18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI','50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2','62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO'))
AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG','SAT','EPT'))
AND (B.TIPOINV IN ('TL005')) 
AND B.CLASIFICA1 NOT IN ('TGE02')
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','PD','OR','RE')) 
AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 
ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Genero Estampado PT02. Datos_Fh_Ingreso
SELECT         A.PRODUCTO, A.NOMBRE, A.FECHA
FROM            MVTRADE AS A INNER JOIN
                         TRADE AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO INNER JOIN
                         MTMERCIA AS C ON A.PRODUCTO = C.CODIGO
WHERE        (A.FECHA >= '01/01/2000') AND (A.TIPODCTO = 'A3')
AND C.TIPOINV = 'TL005'
ORDER BY A.FECHA DESC
----consulata Informe Rotacion Inv. Genero Estampado PT 03. Datos Pedidos
SELECT   A.NRODCTO, A.FECHA, A.NIT, B.BODEGA, B.PRODUCTO, SUM(B.CANVENTA) 
FROM         MVTRADE B, TRADE A
WHERE     (B.TIPODCTO = 'PD') AND (B.BODEGA = ('01.TL.GENE')) AND (B.CANVENTA >= '0')
AND A.FECHA >= getdate()-60
AND A.NRODCTO = B.NRODCTO
AND A.TIPODCTO = B.TIPODCTO
GROUP BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA
ORDER BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA
----consulata Informe Rotacion Inv. Genero Estampado PT Datos1
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB','18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI','50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2','62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO'))

AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG','SAT','EPT'))
AND (B.TIPOINV IN ('TL005')) 
AND B.CLASIFICA1  NOT IN ('TGE02')
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','RE','PD','OR')) 
AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 
ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Genero Estampado PT Tipomvto
SELECT TIPOMVTO.TIPOMVTO, TIPOMVTO.CODINT, TIPOMVTO.ENTRADA, TIPOMVTO.DESCRIPCIO, TIPOMVTO.TRASLADO
FROM COLNOTEXSA.dbo.TIPOMVTO TIPOMVTO
---FIN CONSULATAS SQL DE Ecxel Informe Rotacion Inv. Genero Estampado PT
---INICIA QUERYS Ecxel Informe Rotacion Inv. Genero Unicolor DI
----consulata Informe Rotacion Inv. Genero 01. Datos
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB','18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI','50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2','62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO'))

AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG','SAT','EPT'))
AND (B.TIPOINV IN ('TL010')) 
AND B.CLASIFICA1 IN ('TGU02')
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','PD','OR','RE')) 
AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 
ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Genero Unicolor DI 02. Datos_Fh_Ingreso
SELECT         A.PRODUCTO, A.NOMBRE, A.FECHA
FROM            MVTRADE AS A INNER JOIN
                         TRADE AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO INNER JOIN
                         MTMERCIA AS C ON A.PRODUCTO = C.CODIGO
WHERE        (A.FECHA >= '01/01/2000') AND (A.TIPODCTO = 'A3')
AND C.TIPOINV = 'TL010'

ORDER BY A.FECHA DESC
----consulata Informe Rotacion Inv. Genero Unicolor DI 03. Datos Pedidos
SELECT   A.NRODCTO, A.FECHA, A.NIT, B.BODEGA, B.PRODUCTO, SUM(B.CANVENTA) 
FROM         MVTRADE B, TRADE A
WHERE     (B.TIPODCTO = 'PD') AND (B.BODEGA = ('01.TL.GENE')) AND (B.CANVENTA >= '0')
AND A.FECHA >= getdate()-60
AND A.NRODCTO = B.NRODCTO
AND A.TIPODCTO = B.TIPODCTO
GROUP BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA
ORDER BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA

----consulata Informe Rotacion Inv. Genero Unicolor DI Datos1
SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB','18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI','50. VT. SEPA','51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2','62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO'))

AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG','SAT','EPT'))
AND (B.TIPOINV IN ('TL010')) 
AND B.CLASIFICA1  IN ('TGU02')
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','RE','PD','OR')) 
AND  A.FECHA >= '1/1/2023'  AND  A.FECHA <= '31/12/2023' 
ORDER BY A.PRODUCTO
----consulata Informe Rotacion Inv. Genero Unicolor DI Tipomvto
SELECT TIPOMVTO.TIPOMVTO, TIPOMVTO.CODINT, TIPOMVTO.ENTRADA, TIPOMVTO.DESCRIPCIO, TIPOMVTO.TRASLADO
FROM COLNOTEXSA.dbo.TIPOMVTO TIPOMVTO
---INICIA QUERYS Ecxel Informe Gerencial
----consulata Informe Gerencial Conexión1
SELECT     a.FECHA, a.TIPODCTO, d.NOMBRE, a.TIPOVTA, b.DESCRIPCIO, c.NOMBRE , a.BRUTO, ((a.BRUTO - a.DESCUENTO)/1000) 
FROM         TRADE a INNER JOIN
                      TIPOVTA b ON a.TIPOVTA = b.TIPOVTA INNER JOIN
                      VENDEN c ON a.CODVEN = c.CODVEN INNER JOIN
                      MTPROCLI d ON a.NIT = d.NIT
WHERE     (a.ORIGEN = 'FAC') AND (a.TIPODCTO Not In ('P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12','14','15','16','17','18','19','20','21','AJ','EP','CT','OP','OR','OF','OT','OM','CP')) 
AND (a.FECHA  BETWEEN '01/01/2023' AND '31/12/2023')

 and  a.nrodcto not in ('89716')
ORDER BY    a.FECHA
----consulata Informe Gerencial Consulta desde ColnotexSA
SELECT TIPOVTA.TIPOVTA, TIPOVTA.DESCRIPCIO
FROM COLNOTEXSA.dbo.TIPOVTA TIPOVTA
----consulata Informe Gerencial Consulta desde ColnotexSA1
SELECT MTPROCLI.CODALTERNO, MTPROCLI.NIT, MTPROCLI.NOMBRE
FROM COLNOTEXSA.dbo.MTPROCLI MTPROCLI
----consulata Informe Gerencial Datos
SELECT a.FECHA, a.TIPODCTO, a.TIPOVTA, b.DESCRIPCIO, c.NOMBRE, a.BRUTO, ((A.BRUTO-A.DESCUENTO)/1000) AS 'SUBT'
FROM COLNOTEXSA.dbo.trade a, COLNOTEXSA.dbo.tipovta b, COLNOTEXSA.dbo.venden c
WHERE (a.ORIGEN='FAC') AND (a.TIPOVTA=b.tipovta) 
AND (c.CODVEN=a.codven) 
AND (a.TIPODCTO Not In ('P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12','14','15','16','17','18','19','20','21','AJ','EP','CT','OP','OR','OF','OT','OM','CP'))
 AND (a.FECHA>='01/01/2023' And a.FECHA<='31/12/2023')
 and  a.nrodcto not in ('89716')
ORDER BY a.TIPODCTO
----consulata Informe Gerencial Datos1
SELECT a.FECHA, a.TIPODCTO, a.TIPOVTA, b.DESCRIPCIO, c.NOMBRE, a.BRUTO, ((A.BRUTO-A.DESCUENTO)/1000) AS 'SUBT'
FROM COLNOTEXSA.dbo.trade a, COLNOTEXSA.dbo.tipovta b, COLNOTEXSA.dbo.venden c
WHERE (a.ORIGEN='FAC') AND (a.TIPOVTA=b.tipovta) 
AND (c.CODVEN=a.codven) 
AND (a.TIPODCTO Not In ('P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12','14','15','16','17','18','19','20','21','AJ','EP','CT','OP','OR','OF','OT','OM','CP','EM')) 
AND (a.FECHA>='01/01/2023' And a.FECHA<='31/12/2023')
and  a.nrodcto not in ('89716')
ORDER BY a.TIPODCTO
----consulata Informe Gerencial DatosProd
SELECT A.FECHA, A.TIPODCTO, A.NRODCTO, D.NOMBRE, A.TIPOVTA, B.DESCRIPCIO, C.NOMBRE, E.PRODUCTO, E.NOMBRE, E.CANTIDAD, E.VALORUNIT, (E.CANTIDAD*E.VALORUNIT) AS 'TOTALVTA', G.COSTO_ING, G.COSTO_USD, G.FACTOR, F.VALOR, E.DESCUENTO
FROM COLNOTEXSA.dbo.TRADE A, COLNOTEXSA.dbo.TIPOVTA B, COLNOTEXSA.dbo.VENDEN C, COLNOTEXSA.dbo.MTPROCLI D, COLNOTEXSA.dbo.MVTRADE E, COLNOTEXSA.dbo.MTCAMBIO F, COLNOTEXSA.dbo.MTMERCIA G, COLNOTEXSA.dbo.MTGRUINV H
WHERE (A.ORIGEN='FAC' And A.ORIGEN=E.ORIGEN) 
AND (A.TIPODCTO Not In ('P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12','14','15','16','17','18','19','20','21','AJ','EP','CT','OP','OR','OF','OT','OM','CP') 
And A.TIPODCTO=E.TIPODCTO) 
AND (A.FECHA Between '01/01/2023' And '31/12/2023' And A.FECHA=F.FECHA) 
AND (A.NRODCTO=E.NRODCTO) AND (A.TIPOVTA=B.TIPOVTA)
 and  a.nrodcto not in ('89716')
AND (E.PRODUCTO=G.CODIGO) AND (G.CODGRUPO=H.CODGRUPO) AND (A.NIT=D.NIT) AND (A.CODVEN=C.CODVEN) AND (E.CANTIDAD>0)
ORDER BY A.FECHA, A.NRODCTO

--- query para sacar informe de ventas por vendedor
SELECT  
DATENAME(MONTH, DATEADD(MONTH,MONTH(T.FECHA) - 1, '1900-01-01')) AS MESLETRA,
T.FECHA,
YEAR(T.FECHA) AS AÑO,
MONTH(T.FECHA) AS MES,
T.BRUTO,
V.NOMBRE,
T.NRODCTO,
M.DESCRIPCIO
FROM
TRADE AS T, 
VENDEN AS V,
TIPOVTA AS M
WHERE 
T.CODVEN ='07' AND
--T.BRUTO >'0' AND
T.CODVEN = V.CODVEN AND
T.TIPODCTO IN('NC','FA') AND
T.ORIGEN ='FAC' AND
M.TIPOVTA= T.TIPOVTA AND 
T.TIPOVTA IN ('0-020','0-025','16','28')AND
T.TIPODCTO Not In ('P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12','14','15','16','17','18','19','20','21','AJ','EP','CT','OP','OR','OF','OT','OM','CP') AND
--T.nota not like '%anula%' AND 
T.FECHA >'01/01/2019' And T.FECHA<='31/12/2023' 
ORDER BY NRODCTO ASC;
select * from VENDEN where NOMBRE LIKE '%FRANCISCO ALVAREZ%' AND CODVEN ='07'

SELECT * FROM TRADE WHERE TIPODCTO='FA' AND CODVEN ='07' 
SELECT * FROM MVTRADE
SELECT * FROM MTMERCIA

SELECT * FROM TIPOVTA

SELECT  
DATENAME(MONTH, DATEADD(MONTH,MONTH(T.FECHA) - 1, '1900-01-01')) AS MESLETRA,
T.FECHA,
YEAR(T.FECHA) AS AÑO,
MONTH(T.FECHA) AS MES,
T.BRUTO,
V.NOMBRE,
T.NRODCTO,
M.DESCRIPCIO
FROM
TRADE AS T, 
VENDEN AS V,
TIPOVTA AS M
WHERE 
T.CODVEN ='07' AND
T.BRUTO >'0' AND
T.CODVEN = V.CODVEN AND
T.TIPODCTO='FA' AND
T.ORIGEN ='FAC' AND
M.TIPOVTA= T.TIPOVTA AND 
T.TIPOVTA IN ('0-020','0-025','16','28')AND
T.TIPODCTO Not In ('P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12','14','15','16','17','18','19','20','21','AJ','EP','CT','OP','OR','OF','OT','OM','CP') AND
--T.nota not like '%anula%' AND 
T.FECHA>'01/01/2019' And T.FECHA<='31/12/2023' 
GROUP BY T.FECHA,T.BRUTO,V.NOMBRE,T.NRODCTO,M.DESCRIPCIO ORDER BY T.FECHA ASC;
---query sacar data producto terminado con rango de fecha de 2 años
SELECT     A.BODEGA, B.CODGRUPO, C.NOMBRE, A.CODIGO,B.CODBARRAS, B.DESCRIPCIO, A.NIT,  D.NOMBRE,  B.FECHA_ING, E.CODIGO
FROM         SALDOINV A INNER JOIN
                      MTMERCIA B ON A.CODIGO = B.CODIGO INNER JOIN
                      MTGRUINV C ON B.CODGRUPO = C.CODGRUPO INNER JOIN
                      MTPROCLI D ON A.NIT = D.NIT	INNER JOIN
					  TIPOINV E  ON B.TIPOINV =  E.CODIGO
WHERE  (E.CODIGO LIKE ('%PT%'))  
and YEAR (b.FECHA_ING) > = YEAR (GETDATE())  - 2
GROUP BY A.BODEGA, B.CODGRUPO, C.NOMBRE, A.CODIGO, B.CODBARRAS, B.DESCRIPCIO, A.NIT, D.NOMBRE,  B.FECHA_ING, E.CODIGO 
ORDER BY C.NOMBRE, B.DESCRIPCIO, B.FECHA_ING
---query sacar data producto terminado con rango de fecha de 2 años
SELECT A.CODIGO, A.CODBARRAS ,A.DESCRIPCIO, A.TIPOINV, B.NOMBRE AS TIPOINVENTARIO, F.NOMBRE AS SUBINVENTARIO, A.CODLINEA, C.NOMBRE AS TIPOLINEA, 
E.NOMBRE AS TIPOGRUPO, A.FECING, G.NOMBRE AS CLASIFICACION1, D.NOMBRE AS CLASIFICACION2
FROM MTMERCIA A, TIPOINV B, MTLINEA C, MTGRUINV E, MTSBLIN F, MT1CLAF G, MT2CLAF D
WHERE   (B.CODIGO IN ('PT005','PT010','PT015','PT020','PT025','PT030','PT035','PT036','PT037','PT038','PT039','PT040','PT045'))
AND YEAR (A.FECING) > = YEAR (GETDATE())  - 2
AND A.TIPOINV = B.CODIGO
AND A.CODLINEA = C.CODLINEA
AND A.CODGRUPO = E.CODGRUPO
AND A.CODSBLIN = F.CODSBLIN
AND A.CLASIFICA1 = G.CODIGO
AND A.CLASIFICA2 = D.CODIGO