SELECT   TOP (100) PERCENT A.NRODCTO, B.NOMBRE AS CLIENTE, B.DIRECCION, C.NOMBRE AS CIUDAD, B.TEL1, A.NIT, D.NOMBRE AS AGENTE, DAY(A.FECHA) AS DIA, MONTH(A.FECHA) AS MES, YEAR(A.FECHA) AS ANIO, F.CPAGO, F.TNEGO, F.NCAJA, F.KBRUT, F.KNETO, E.PRODUCTO AS COD_PROD, E.NOMBRE AS PRODUCTO, E.CANTIDAD, 
             E.XVALORUN AS VLR_UNIT, E.CANTIDAD * E.XVALORUN AS VLR_TOT, A.TRANSPORTA, F.PARAN, A.NOTA
FROM     dbo.TRADE AS A INNER JOIN
             dbo.MVTRADE AS E ON A.NRODCTO = E.NRODCTO AND A.TIPODCTO = E.TIPODCTO AND E.ORIGEN = 'fac' INNER JOIN
             dbo.MTPROCLI AS B ON A.NIT = B.NIT INNER JOIN
             dbo.CIUDAD AS C ON B.CIUDAD = C.CODCIUDAD INNER JOIN
             dbo.VENDEN AS D ON B.VENDEDOR = D.CODVEN INNER JOIN
             dbo.TRADEMAS AS F ON A.NRODCTO = F.NRODCTO AND A.TIPODCTO = F.TIPODCTO AND F.ORIGEN = 'fac'
WHERE   (A.TIPOVTA IN ('0-070','0-071')) AND (A.TIPODCTO IN ('FA','FR')) AND A.FECHA >'01-01-2024'