SELECT        A.NRODCTO, B.NOMBRE as CLIENTE,A.DIR, A.CIUDADCLI,B.TEL1, A.NIT, A.PASSWORDIN, E.PRODUCTO, F.CODBARRAS, E.NOMBRE, E.CANTIDAD, E.UNDVENTA, A.FECHA, A.BRUTO,  A.CAJAREG, A.TIPODCTO, A.HORA, A.TIPOVTA, C.DESCRIPCIO, A.MEDIOPAG,  A.IVABRUTO, E.VLRVENTA AS VERIFICAVAL, 
                         E.VALORUNIT, E.CANTORIG * E.VALORUNIT AS TOTALUNI, E.nota AS NOTA_MV, E.IVA
FROM            Trade AS A INNER JOIN
                         MtProcli AS B ON A.NIT = B.NIT INNER JOIN
                         TipoVta AS C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
                      MVTRADE AS E ON A.NRODCTO = E.NRODCTO AND A.TIPODCTO = E.TIPODCTO INNER JOIN
					  MtMercia AS F ON E.PRODUCTO = F.CODIGO
WHERE        (A.FECHA >= '01/07/2024') AND (A.TIPODCTO IN ('OR')) AND (A.ORIGEN = 'COM')
ORDER BY A.NRODCTO DESC 