select*from MVTRADE where FECHA>'15-07-2024' AND NRODCTO='96554442'

SELECT     A.NRODCTO,a.DCTOPRV, B.BODEGA, A.TIPODCTO, A.NIT, C.NOMBRE, A.FECHA, A.FECING, B.FECENT, A.AUTORIZA, B.PRODUCTO, B.NOMBRE , 
                      B.CANTIDAD, B.CANTORIG , B.CANVENTA , B.VALORUNIT, B.CANTORIG * B.VALORUNIT , b.nota AS NOTA_MV, A.NOTA
FROM         TRADE A INNER JOIN
                      MTPROCLI C ON A.NIT = C.NIT INNER JOIN
                      MVTRADE B ON A.NRODCTO = B.NRODCTO AND A.TIPODCTO = B.TIPODCTO
WHERE      (B.BODEGA IN ('02.TL.DECO','62.TL.DECO2')) AND A. NRODCTO='96554442'
AND A.FECHA BETWEEN '01-07-2024' AND '31-07-2024' 
ORDER BY A.nrodcto DESC

SELECT     A.NRODCTO,a.DCTOPRV, B.BODEGA, A.TIPODCTO, A.NIT, C.NOMBRE, A.FECHA, A.FECING, B.FECENT, A.AUTORIZA, B.PRODUCTO, B.NOMBRE , 
                      B.CANTIDAD, B.CANTORIG , B.CANVENTA , B.VALORUNIT, B.CANTORIG * B.VALORUNIT , b.nota AS NOTA_MV, A.NOTA
FROM         TRADE A INNER JOIN
                      MTPROCLI C ON A.NIT = C.NIT INNER JOIN
                      MVTRADE B ON A.NRODCTO = B.NRODCTO AND A.TIPODCTO = B.TIPODCTO
WHERE      (B.BODEGA IN ('02.TL.DECO','62.TL.DECO2')) AND A. NRODCTO='111175'
AND A.FECHA BETWEEN '01-07-2024' AND '31-07-2024' 
ORDER BY A.nrodcto DESC