USE COLNOTEXSA
SELECT * FROM TRADE where NRODCTO='442015' and tipodcto='PD'

SELECT BODEGA, CANTORIG, NOMBRE FROM MVTRADE WHERE NRODCTO='9202043'

SELECT AUTORIZA,PASSWORDIN as USUARIO_INGRESO_PEDIDO, PASSWORDMO AS USUARIO_MODIFICO_PEDIDO, NRODCTO, FECHA, FECMOD, HORA FROM TRADE where NRODCTO in('442015','92001221') and tipodcto='PD'


