------QUEERY PARA VER MEDIOS DE PAGO SIN ASIGNAR EN MVCUADRE SUPERTODO
USE SUPERTODO
SELECT        TOP (200) BANCO, BANCODEST, BANCOORI, BENEF, CODBANCO, CODCHQDEV, CODESTADO, CODPLAZA, CODTARJETA, COMENTARIO, CTACHEQUE, CTADEST, CTAORI, DCTO, FACTURA, FECHACHQ, FECHAMVTO, FECING, 
                         FECMOD, IDINTEGRA, IDMVCUADRE, IdTeletransporte, INTBANCO, MEDIOPAG, NIT, NROAPROBA, NROCHEQUE, ORIGEN, PAGODATAF, PASSWORDIN, PASSWORDMO, STADSINCRO, TIPODCTO, TIPODCTOFA, VALOR
FROM            MvCuadre
WHERE        (MEDIOPAG NOT IN ('01', '04', '97', '03', '09', '11', '13', '10', '12'))

------QUEERY PARA VER MEDIOS DE PAGO SIN ASIGNAR EN MVCUADRE BESTPRICE
USE BESTPRICE
SELECT        BANCO, BANCODEST, BANCOORI, BENEF, CODBANCO, CODCHQDEV, CODESTADO, CODPLAZA, CODTARJETA, COMENTARIO, CTACHEQUE, CTADEST, CTAORI, DCTO, FACTURA, FECHACHQ, FECHAMVTO, FECING, FECMOD, 
                         IDINTEGRA, IDMVCUADRE, IdTeletransporte, INTBANCO, MEDIOPAG, NIT, NROAPROBA, NROCHEQUE, ORIGEN, PAGODATAF, PASSWORDIN, PASSWORDMO, STADSINCRO, TIPODCTO, TIPODCTOFA, VALOR
FROM            MvCuadre
WHERE        (MEDIOPAG NOT IN ('01', '04', '97', '03', '09', '11', '13'))