SELECT       A.NRODCTO, b.DETALLE, A.FECHA, B.PRODUCTO, D.DESCRIPCIO , B.tipodcto, CONCAT(TRIM(A.NRODCTO),B.PRODUCTO) AS CODIGO, B.CANTIDAD, B.VALUNID AS VALORUNIT
FROM         TRADE A INNER JOIN
                      MVTRADE B ON A.NRODCTO = B.NRODCTO INNER JOIN
                      MTPROCLI C ON A.NIT = C.NIT INNER JOIN
                      MTMERCIA D ON B.PRODUCTO = D.CODIGO
WHERE     (A.ORIGEN = 'INV') AND B.ORIGEN = 'INV' AND (B.TIPOMVTO in ('EAI','SAI','01','02','03'))
AND (a.FECHA>=getdate()-120) 
ORDER BY A.FECHA, A.NRODCTO
UNION
SELECT       A.NRODCTO, b.DETALLE, A.FECHA, B.PRODUCTO, D.DESCRIPCIO , B.tipodcto, CONCAT(TRIM(A.NRODCTO),B.PRODUCTO) AS CODIGO, B.CANTIDAD, B.VALUNID AS VALORUNIT,B.TIPOMVTO
FROM         TRADE A INNER JOIN
                      MVTRADE B ON A.NRODCTO = B.NRODCTO INNER JOIN
                      MTPROCLI C ON A.NIT = C.NIT INNER JOIN
                      MTMERCIA D ON B.PRODUCTO = D.CODIGO
WHERE     (A.ORIGEN = 'INV') AND (A.TIPODCTO = 'ED') AND (B.ORIGEN = 'INV') AND (B.TIPODCTO = 'ED')
AND (a.FECHA>=getdate()-120) 
ORDER BY A.FECHA, A.NRODCTO

SELECT       A.NRODCTO, b.DETALLE, A.FECHA, B.PRODUCTO, D.DESCRIPCIO , B.tipodcto, CONCAT(TRIM(A.NRODCTO),B.PRODUCTO) AS CODIGO, B.CANTIDAD, B.VALUNID AS VALORUNIT
FROM         TRADE A INNER JOIN
                      MVTRADE B ON A.NRODCTO = B.NRODCTO INNER JOIN
                      MTPROCLI C ON A.NIT = C.NIT INNER JOIN
                      MTMERCIA D ON B.PRODUCTO = D.CODIGO
WHERE     (A.ORIGEN = 'INV') AND (A.TIPODCTO = 'G1') AND (B.ORIGEN = 'INV') AND (B.TIPODCTO = 'G1')
AND (a.FECHA>=getdate()-120) 
ORDER BY A.FECHA, A.NRODCTO