SELECT     A.PRODUCTO, B.DESCRIPCIO, A.FECENT, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.CODGRUPO, F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN, H.DCTOPRV, I.NOMBRE
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO INNER JOIN
                      TRADE H ON A.NRODCTO = H.NRODCTO AND A.TIPODCTO = H.TIPODCTO INNER JOIN
                      MT2CLAF I ON B.CLASIFICA2 = I.CODIGO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB',
'18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI',
'51. DC. SEPA','52. MC. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2',
'62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO','71.BONDEOPT','72.BONDEOMP'))
AND (A.TIPODCTO IN ('OR')) 
AND B.TIPOINV IN ('TL020','TL025','TL026','TL027')
AND  A.FECHA > =getdate() -180
AND A.NRODCTO LIKE '8%'
AND A.NOTA <> 'CEDI'
ORDER BY A.PRODUCTO