SELECT       D.NOMBRE, B.NOTA,  E.NOMBRE , A.FECHA, A.TIPODCTO, A.NRODCTO, A.BODEGA, A.PRODUCTO, A.NOMBRE , A.CANTIDAD, A.UNDVENTA, A.VALORUNIT, C.COSTO_USD, C.FACTOR, C.COSTO_UF, 
                         C.COSTO_USDR, C.FACTORR, C.COSTO_UFR, A.NOTA
FROM            MVTRADE AS A INNER JOIN
                         TRADE AS B ON A.NRODCTO = B.NRODCTO AND A.TIPODCTO = B.TIPODCTO INNER JOIN
                         MTMERCIA AS C ON A.PRODUCTO = C.CODIGO INNER JOIN
                         TIPOINV AS D ON C.TIPOINV = D.CODIGO INNER JOIN
                         MTGRUINV AS E ON C.CODGRUPO = E.CODGRUPO
WHERE        (A.FECHA >= '01/09/2024') AND (A.FECHA <= '30/09/2024') AND (A.TIPODCTO = 'A3') and A.PRODUCTO='1020000220443'
ORDER BY D.NOMBRE, B.NOTA,  E.NOMBRE  