update TRADE
set TRADE.IVABRUTO = (select IVABRUTO from AAATRADE05122024OK$
               where TRADE.NRODCTO = AAATRADE05122024OK$.NRODCTO)
where TRADE.NRODCTO in (select NRODCTO from   AAATRADE05122024OK$) AND TRADE.ORIGEN='COM'

update TRADE
set TRADE.BRUTO = (select BRUTO from AAATRADE05122024OK$
               where TRADE.NRODCTO = AAATRADE05122024OK$.NRODCTO)
where TRADE.NRODCTO in (select NRODCTO from   AAATRADE05122024OK$) AND TRADE.ORIGEN='COM'

update TRADE
set TRADE.DCTOPRV = (select NRODCTO from AAATRADE05122024OK$
               where TRADE.NRODCTO = AAATRADE05122024OK$.NRODCTO)
where TRADE.NRODCTO in (select NRODCTO from   AAATRADE05122024OK$) AND TRADE.ORIGEN='COM'

update MTMERCIA
set MTMERCIA.COSTO_ING = (select COSTO from AAAACostos_Sep02$
               where MTMERCIA.CODIGO = AAAACostos_Sep02$.producto)
where MTMERCIA.CODIGO in (select PRODUCTO from   AAAACostos_Sep02$)

