--- columnas con cuentas contables CTACOM, CTACOMDEV, CTACOMDIVA, CTACOMDRTE, CTACOMIVA, CTACOMRTE,CTAVTA, CTAVTADEV,CTAVTADIVA, CTAVTADRTE, CTAVTAIVA, CTAVTARTE, CTDRIRCCOM,CTRIRCCOM
update [dbo].[MtMercia]
set 
CTRIRCCOM='23670501'
WHERE        (CODIGO LIKE '%A-%') AND (CODTARIVA = 'TAR2') and CTRIRCCOM='                    '

update [dbo].[MtMercia]
set 
CTDRIRSCOM='                    '
WHERE        (CODIGO LIKE '%A-%') AND (CODTARIVA = 'TAR2') and CTDRIRSCOM='23670501'

SELECT*FROM MtMercia WHERE CODIGO IN ('A-11096')