

	ALTER TABLE [dbo].[MVTRADE] ALTER COLUMN CTAVTANIIF char (20) NULL;  
GO  
 CONSTRAINT [PK__MVTRADE__7260EDCA] PRIMARY KEY NONCLUSTERED 
(
	[IDMVTRADE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_BASE]  DEFAULT ((0)) FOR [BASE]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_BODEGA]  DEFAULT ('0') FOR [BODEGA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CANTEMPAQ]  DEFAULT ((0)) FOR [CANTEMPAQ]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CANTIDAD]  DEFAULT ((0)) FOR [CANTIDAD]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CANTORIG]  DEFAULT ((0)) FOR [CANTORIG]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CANTREMIS]  DEFAULT ((0)) FOR [CANTREMIS]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CANVENTA]  DEFAULT ((0)) FOR [CANVENTA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CARGOA]  DEFAULT ('') FOR [CARGOA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CODCC]  DEFAULT ('0') FOR [CODCC]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CODIGOCTA]  DEFAULT ('0') FOR [CODIGOCTA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CODINT]  DEFAULT ((0)) FOR [CODINT]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CODRETE]  DEFAULT ('0') FOR [CODRETE]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CODRETICA]  DEFAULT ('0') FOR [CODRETICA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CODTRAS]  DEFAULT ((0)) FOR [CODTRAS]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CODUBICA]  DEFAULT ('0') FOR [CODUBICA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CONSECUT]  DEFAULT ((0)) FOR [CONSECUT]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_COSTEO]  DEFAULT ((0)) FOR [COSTEO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_COSTO]  DEFAULT ((0)) FOR [COSTO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_DESCFINAN]  DEFAULT ((0)) FOR [DESCFINAN]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_DESCUENTO]  DEFAULT ((0)) FOR [DESCUENTO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_DETALLE]  DEFAULT ('') FOR [DETALLE]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_DSCTOFINAN]  DEFAULT ((0)) FOR [DSCTOFINAN]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_FACTURADO]  DEFAULT ((0)) FOR [FACTURADO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_FECENT]  DEFAULT ([dbo].[F_FechasinHora](getdate())) FOR [FECENT]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_FECHA]  DEFAULT ([dbo].[F_FechasinHora](getdate())) FOR [FECHA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_FECING]  DEFAULT ([dbo].[F_FechasinHora](getdate())) FOR [FECING]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_FECMOD]  DEFAULT ([dbo].[F_FechasinHora](getdate())) FOR [FECMOD]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_FHCOMPRA]  DEFAULT ([dbo].[F_FechasinHora](getdate())) FOR [FHCOMPRA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_HCOSTO]  DEFAULT ((0)) FOR [HCOSTO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_HVALUNID]  DEFAULT ((0)) FOR [HVALUNID]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_IDPEDORD]  DEFAULT ((0)) FOR [IDPEDORD]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_IDREMIS]  DEFAULT ((0)) FOR [IDREMIS]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_IDREQORD]  DEFAULT ((0)) FOR [IDREQORD]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_IMPORTAC]  DEFAULT ('') FOR [IMPORTAC]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_INCIDENTE]  DEFAULT ('') FOR [INCIDENTE]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_INTEGRADO]  DEFAULT ((0)) FOR [INTEGRADO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_INTEGTALL]  DEFAULT ((0)) FOR [INTEGTALL]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_IPCONSUMO]  DEFAULT ((0)) FOR [IPCONSUMO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_IVA]  DEFAULT ((0)) FOR [IVA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_LOGIN]  DEFAULT ('') FOR [LOGIN]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_MVTOTRAS]  DEFAULT ('') FOR [MVTOTRAS]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_NIT]  DEFAULT ('0') FOR [NIT]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_NOMBRE]  DEFAULT ('') FOR [NOMBRE]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_NORDEN]  DEFAULT ('') FOR [NORDEN]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_NOTA]  DEFAULT ('') FOR [NOTA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_NOTAS]  DEFAULT ('') FOR [NOTAS]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_NPEDIDO]  DEFAULT ('') FOR [NPEDIDO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_NROBONO]  DEFAULT ((0)) FOR [NROBONO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_NRODCTO]  DEFAULT ('') FOR [NRODCTO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_NROFACTURA]  DEFAULT ('') FOR [NROFACTURA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_NROORDEN]  DEFAULT ('') FOR [NROORDEN]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_NROSOLI]  DEFAULT ('') FOR [NROSOLI]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_NUMFACTNC]  DEFAULT ('') FOR [NUMFACTNC]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_ORDENADO]  DEFAULT ((0)) FOR [ORDENADO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_ORDENNRO]  DEFAULT ('0') FOR [ORDENNRO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_ORDENPRV]  DEFAULT ('') FOR [ORDENPRV]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_ORIGEN]  DEFAULT ('FAC') FOR [ORIGEN]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_PASATERORD]  DEFAULT ((0)) FOR [PASATERORD]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_PASSWORDIN]  DEFAULT ('') FOR [PASSWORDIN]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_PASSWORDMO]  DEFAULT ('') FOR [PASSWORDMO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_PESODOLAR]  DEFAULT ('') FOR [PESODOLAR]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_PORETE]  DEFAULT ((0)) FOR [PORETE]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_PORICA]  DEFAULT ((0)) FOR [PORICA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_PRETFTE]  DEFAULT ((0)) FOR [PRETFTE]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_PRODUCTO]  DEFAULT ('') FOR [PRODUCTO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_REMIFACT]  DEFAULT ('') FOR [REMIFACT]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_SERFLETES]  DEFAULT ((0)) FOR [SERFLETES]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_SUCURSAL]  DEFAULT ('0') FOR [SUCURSAL]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_TIPODCTO]  DEFAULT ('FA') FOR [TIPODCTO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_TIPODCTOFA]  DEFAULT ('') FOR [TIPODCTOFA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_TIPODCTONC]  DEFAULT ('') FOR [TIPODCTONC]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_TIPODCTOPC]  DEFAULT ('') FOR [TIPODCTOPC]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_TIPODCTORE]  DEFAULT ('') FOR [TIPODCTORE]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_TIPODCTOSI]  DEFAULT ('') FOR [TIPODCTOSI]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_TIPODCTOTR]  DEFAULT ('') FOR [TIPODCTOTR]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_TIPOMVTO]  DEFAULT ('0') FOR [TIPOMVTO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_TOPRETE]  DEFAULT ((0)) FOR [TOPRETE]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_TOPRETICA]  DEFAULT ((0)) FOR [TOPRETICA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_TRASLADO]  DEFAULT ((0)) FOR [TRASLADO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_UNDBASE]  DEFAULT ('UND') FOR [UNDBASE]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_UNDVENTA]  DEFAULT ('UND') FOR [UNDVENTA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_VALORUNIT]  DEFAULT ((0)) FOR [VALORUNIT]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_VALUNID]  DEFAULT ((0)) FOR [VALUNID]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_VENDEDOR]  DEFAULT ('0') FOR [VENDEDOR]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_VLRVENTA]  DEFAULT ((0)) FOR [VLRVENTA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_XCOSTO]  DEFAULT ((0)) FOR [XCOSTO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_XVALORUN]  DEFAULT ((0)) FOR [XVALORUN]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_XVALUNID]  DEFAULT ((0)) FOR [XVALUNID]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_ZVALORUNIT]  DEFAULT ((0)) FOR [ZVALORUNIT]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CTAVTA]  DEFAULT ('') FOR [CTAVTA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_BASEIMPOR]  DEFAULT ((0)) FOR [BASEIMPOR]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_BIVAIMPOR]  DEFAULT ((0)) FOR [BIVAIMPOR]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_CODDETRA]  DEFAULT ('0') FOR [CODDETRA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_IDIMPUESTO]  DEFAULT ('0') FOR [IDIMPUESTO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_IDREQSOL]  DEFAULT ((0)) FOR [IDREQSOL]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_NOTADOS]  DEFAULT ('') FOR [NOTADOS]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_PLANPED]  DEFAULT ((0)) FOR [PLANPED]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_PORCENTA]  DEFAULT ((0)) FOR [PORCENTA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_PORCENTI]  DEFAULT ((0)) FOR [PORCENTI]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_PORCENTU]  DEFAULT ((0)) FOR [PORCENTU]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_PORDETRA]  DEFAULT ((0)) FOR [PORDETRA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_TOPDETRA]  DEFAULT ((0)) FOR [TOPDETRA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_ITEMICA]  DEFAULT ((0)) FOR [ITEMICA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_ITEMIVA]  DEFAULT ((0)) FOR [ITEMIVA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_ITEMRETE]  DEFAULT ((0)) FOR [ITEMRETE]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  CONSTRAINT [DF_MVTRADE_PLANEAR]  DEFAULT ((0)) FOR [PLANEAR]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((1)) FOR [FORMULA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ('') FOR [IDINTEGRA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [IMPCIGARRI]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [INTNIIF]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [IPCONSUBEB]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ('') FOR [METRETIVA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [NCOSTO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [NVALUNID]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [PORAYS]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [PRETENIVA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ('0') FOR [TARIVA]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [VALORAIU]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [XNCOSTO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [XNVALUNID]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ('') FOR [APRUEBACAL]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ('') FOR [BODDESTINO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [CANANCHO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [CANESPESOR]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [CANLARGO]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ('0') FOR [CODIGOUEN]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ('') FOR [CTAVTANIIF]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ('') FOR [IDCAJAS]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [IPAZUCAR]
GO

ALTER TABLE [dbo].[MVTRADE] ADD  DEFAULT ((0)) FOR [IPSALUD]
GO

ALTER TABLE [dbo].[MVTRADE]  WITH CHECK ADD  CONSTRAINT [FK_MVTRADE_CENTCOS] FOREIGN KEY([CODCC])
REFERENCES [dbo].[CENTCOS] ([CODCC])
GO

ALTER TABLE [dbo].[MVTRADE] CHECK CONSTRAINT [FK_MVTRADE_CENTCOS]
GO

ALTER TABLE [dbo].[MVTRADE]  WITH CHECK ADD  CONSTRAINT [FK_MVTRADE_CUENTAS] FOREIGN KEY([CODIGOCTA])
REFERENCES [dbo].[CUENTAS] ([CODIGOCTA])
GO

ALTER TABLE [dbo].[MVTRADE] CHECK CONSTRAINT [FK_MVTRADE_CUENTAS]
GO

ALTER TABLE [dbo].[MVTRADE]  WITH CHECK ADD  CONSTRAINT [FK_MVTRADE_MTBODEGA] FOREIGN KEY([BODEGA])
REFERENCES [dbo].[MTBODEGA] ([LOGIN])
GO

ALTER TABLE [dbo].[MVTRADE] CHECK CONSTRAINT [FK_MVTRADE_MTBODEGA]
GO

ALTER TABLE [dbo].[MVTRADE]  WITH CHECK ADD  CONSTRAINT [FK_MVTRADE_MTLOTE] FOREIGN KEY([ORDENNRO])
REFERENCES [dbo].[MTLOTE] ([CODLOTE])
GO

ALTER TABLE [dbo].[MVTRADE] CHECK CONSTRAINT [FK_MVTRADE_MTLOTE]
GO

ALTER TABLE [dbo].[MVTRADE]  WITH CHECK ADD  CONSTRAINT [FK_MVTRADE_MTMERCIA] FOREIGN KEY([PRODUCTO])
REFERENCES [dbo].[MTMERCIA] ([CODIGO])
GO

ALTER TABLE [dbo].[MVTRADE] CHECK CONSTRAINT [FK_MVTRADE_MTMERCIA]
GO

ALTER TABLE [dbo].[MVTRADE]  WITH CHECK ADD  CONSTRAINT [FK_MVTRADE_MTPROCLI] FOREIGN KEY([NIT])
REFERENCES [dbo].[MTPROCLI] ([NIT])
GO

ALTER TABLE [dbo].[MVTRADE] CHECK CONSTRAINT [FK_MVTRADE_MTPROCLI]
GO

ALTER TABLE [dbo].[MVTRADE]  WITH CHECK ADD  CONSTRAINT [FK_MVTRADE_MTRETICA] FOREIGN KEY([CODRETICA])
REFERENCES [dbo].[MTRETICA] ([CODRETICA])
GO

ALTER TABLE [dbo].[MVTRADE] CHECK CONSTRAINT [FK_MVTRADE_MTRETICA]
GO

ALTER TABLE [dbo].[MVTRADE]  WITH CHECK ADD  CONSTRAINT [FK_MVTRADE_MTTOPRTE] FOREIGN KEY([CODRETE])
REFERENCES [dbo].[MTTOPRTE] ([CODRETE])
GO

ALTER TABLE [dbo].[MVTRADE] CHECK CONSTRAINT [FK_MVTRADE_MTTOPRTE]
GO

ALTER TABLE [dbo].[MVTRADE]  WITH CHECK ADD  CONSTRAINT [FK_MVTRADE_MTUBICA] FOREIGN KEY([CODUBICA])
REFERENCES [dbo].[MTUBICA] ([CODUBICA])
GO

ALTER TABLE [dbo].[MVTRADE] CHECK CONSTRAINT [FK_MVTRADE_MTUBICA]
GO

ALTER TABLE [dbo].[MVTRADE]  WITH CHECK ADD  CONSTRAINT [FK_Mvtrade_MTUEN] FOREIGN KEY([CODIGOUEN])
REFERENCES [dbo].[MTUEN] ([CODIGOUEN])
GO

ALTER TABLE [dbo].[MVTRADE] CHECK CONSTRAINT [FK_Mvtrade_MTUEN]
GO

ALTER TABLE [dbo].[MVTRADE]  WITH CHECK ADD  CONSTRAINT [FK_MVTRADE_TIPOMVTO] FOREIGN KEY([TIPOMVTO])
REFERENCES [dbo].[TIPOMVTO] ([TIPOMVTO])
GO

ALTER TABLE [dbo].[MVTRADE] CHECK CONSTRAINT [FK_MVTRADE_TIPOMVTO]
GO


