SELECT        A.NRODCTO, A.NIT,E.PRODUCTO, F.CODBARRAS, E.NOMBRE,A.FECHA, A.FECHA1, E.VLRVENTA, A.BRUTO, A.DIR, A.CAJAREG, A.PASSWORDIN, B.NOMBRE, A.TIPODCTO, A.HORA, A.TIPOVTA, C.DESCRIPCIO, A.MEDIOPAG,  A.IVABRUTO, A.BRUTO + A.IVABRUTO AS VERIFICAVAL, 
                         D.MEDIOPAG , D.VALOR, D.COMENTARIO
FROM            Trade AS A INNER JOIN
                         MtProcli AS B ON A.NIT = B.NIT INNER JOIN
                         TipoVta AS C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
                         MvCuadre AS D ON A.TIPODCTO = D.TIPODCTO AND A.NRODCTO = D.DCTO AND A.ORIGEN = D.ORIGEN INNER JOIN
                      MVTRADE AS E ON A.NRODCTO = E.NRODCTO AND A.TIPODCTO = E.TIPODCTO INNER JOIN
					  MtMercia AS F ON E.PRODUCTO = F.CODIGO
WHERE        (A.FECHA > '01-01-2023') AND (A.TIPODCTO IN ('F2','B2')) AND (A.ORIGEN = 'FAC')

select * from Mvtrade WHERE        (FECHA > '01-01-2023') AND (TIPODCTO IN ('B2')) AND (ORIGEN = 'FAC') AND PRODUCTO='A-00291'

SELECT * FROM MVPRECIO WHERE CODPRODUC='A-00291'

SELECT        A.NRODCTO, A.NIT,E.PRODUCTO, F.CODBARRAS, E.NOMBRE,e.IVA ,A.FECHA, A.FECHA1, E.VLRVENTA, A.BRUTO, A.DIR, A.CAJAREG, A.PASSWORDIN, B.NOMBRE, A.TIPODCTO, A.HORA, A.TIPOVTA, C.DESCRIPCIO, A.MEDIOPAG,  A.IVABRUTO, 
                         D.MEDIOPAG , D.COMENTARIO
FROM            Trade AS A INNER JOIN
                         MtProcli AS B ON A.NIT = B.NIT INNER JOIN
                         TipoVta AS C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
                         MvCuadre AS D ON A.TIPODCTO = D.TIPODCTO AND A.NRODCTO = D.DCTO AND A.ORIGEN = D.ORIGEN INNER JOIN
                      MVTRADE AS E ON A.NRODCTO = E.NRODCTO AND A.TIPODCTO = E.TIPODCTO INNER JOIN
					  MtMercia AS F ON E.PRODUCTO = F.CODIGO
WHERE        (A.FECHA > '01-01-2023') AND (A.TIPODCTO IN ('F2','B2')) AND (A.ORIGEN = 'FAC')