SELECT        NRODCTO,BODEGA,cantidad,CANTORIG,cantidad-CANTORIG as cuadre1,CANVENTA,cantidad-CANVENTA as cuadre2,PRODUCTO,NOMBRE,IVA,TARIVA, VALORUNIT, VALUNID, VLRVENTA
FROM            MVTRADE
WHERE        (NRODCTO IN ('372')) AND (TIPODCTO = 'fe') AND (ORIGEN = 'FAC')  --and iva <>'19.00' 

/*SELECT Mvtrade.TIPODCTO, Mvtrade.NRODCTO, Mvtrade.FECHA, Mvtrade.BODEGA, Mvtrade.BODDESTINO, Mvtrade.PRODUCTO, Mvtrade.NOMBRE, Mvtrade.CANTIDAD
FROM VERONASAS.dbo.Mvtrade Mvtrade
WHERE (Mvtrade.TIPODCTO In ('g1')) AND Mvtrade.BODDESTINO <> Mvtrade.BODEGA
ORDER BY mvtrade.producto, MVTRADE.TIPODCTO DESC*/

/*use VERONASAS
update Mvtrade
set 
cantidad=CANVENTA,
CANTORIG=CANVENTA,
VALORUNIT=VLRVENTA,
VALUNID=VLRVENTA
WHERE        (NRODCTO IN ('372')) AND (TIPODCTO = 'fe') AND (ORIGEN = 'FAC') */

use VERONASAS
update Mvtrade
set 
VALORUNIT=VLRVENTA,
VALUNID=VLRVENTA
WHERE        (NRODCTO IN ('372')) AND (TIPODCTO = 'fe') AND (ORIGEN = 'FAC') 