SELECT * FROM MVTRADE WHERE TIPODCTO in ('F2','B2') AND TIPODCTO NOT IN ('PD','F3') and Fecha >='31-01-2024' and Fecha <='31-01-2024'AND ORIGEN='FAC'

SELECT 
    CAST(Fecha AS DATE) AS Dia, 
    SUM(ROUND(T.HCOSTO,2)) AS Totalcostos,
	MONTH(T.Fecha) AS Mes,
	SUM(T.CANVENTA) AS Totalcantidad,
	SUM(ROUND(T.NVALUNID,2)) AS TOTALVENTASSINITBIS
FROM 
    Mvtrade as T
	WHERE T.TIPODCTO in ('F2','B2') AND T.TIPODCTO NOT IN ('PD','F3') and T.Fecha >'01-01-2024' AND ORIGEN='FAC'
GROUP BY 
    CAST(Fecha AS DATE),T.Fecha
ORDER BY 
    Dia;

SELECT 
    CAST(Fecha AS DATE) AS Dia, 
    SUM(T.CANVENTA) AS Totalventassiniva,
	MONTH(T.Fecha) AS Mes
FROM 
    Mvtrade as T
	WHERE T.TIPODCTO in ('F2','B2') AND T.TIPODCTO NOT IN ('PD','F3') and T.Fecha >'01-01-2024' AND ORIGEN='FAC'
GROUP BY 
    CAST(Fecha AS DATE),T.Fecha
ORDER BY 
    Dia;

---PRUEBA 
SELECT 
    CAST(Fecha AS DATE) AS Dia, 
    SUM(ROUND(T.HCOSTO,2))*SUM(T.CANVENTA) AS Totalcostos,
	MONTH(T.Fecha) AS Mes,
	SUM(T.CANVENTA) AS Totalcantidad,
	SUM(ROUND(T.NVALUNID,2))*SUM(T.CANVENTA) AS TOTALVENTASSINITBIS,
	T.PRODUCTO
FROM 
    Mvtrade as T
	WHERE T.TIPODCTO in ('B2') AND T.TIPODCTO NOT IN ('PD','F3') and T.Fecha >'01-01-2024' AND ORIGEN='FAC'
GROUP BY 
    CAST(Fecha AS DATE),T.Fecha, T.PRODUCTO
ORDER BY 
    Dia;

SELECT FECHA,PRODUCTO,NOMBRE, COSTO, HVALUNID,CANVENTA, COSTO*CANVENTA AS COSTOSTOTAL, HVALUNID*CANVENTA AS VENTATOTALSINIVA, MONTH(FECHA)AS Mes  FROM MVTRADE WHERE TIPODCTO in ('B2','F2') AND ORIGEN='FAC' and Fecha >'01-07-2024'

select*from MtMercia where CODIGO in ('A-07222','A-07180')

SELECT 
    T.PRODUCTO,
	CAST(Fecha AS DATE) AS Dia, 
    SUM(ROUND(T.COSTO,2))*SUM(T.CANVENTA) AS Totalcostos,
	MONTH(T.Fecha) AS Mes,
	SUM(T.CANVENTA) AS Totalcantidad,
	ROUND(T.COSTO,2)as costounitario
FROM 
    Mvtrade as T
	WHERE T.TIPODCTO in ('B2','f2') AND T.TIPODCTO NOT IN ('PD','F3') and T.Fecha >'01-06-2024' AND ORIGEN='FAC'
GROUP BY 
    CAST(Fecha AS DATE),T.Fecha, T.PRODUCTO, T.COSTO, T.CANVENTA
ORDER BY 
    Dia;
----
SELECT 
    T.PRODUCTO,
	CAST(Fecha AS DATE) AS Dia, 
    SUM(ROUND(T.NVALUNID,2))*SUM(T.CANVENTA) AS TOTALVENTASSINITBIS,
	MONTH(T.Fecha) AS Mes,
	SUM(T.CANVENTA) AS Totalcantidad,
	SUM(ROUND(T.NVALUNID,2)) AS TOTALVENTAUND
FROM 
    Mvtrade as T
	WHERE T.TIPODCTO in ('B2','F2') AND T.TIPODCTO NOT IN ('PD','F3') and T.Fecha >'01-06-2024' AND ORIGEN='FAC'
GROUP BY 
    CAST(Fecha AS DATE),T.Fecha, T.PRODUCTO, T.CANVENTA
ORDER BY 
    Dia;