SELECT TRADE.NRODCTO, TRADE.FECHA, trade.codcc,TRADE.NIT, MTPROCLI.NOMBRE, TRADE.BRUTO-TRADE.DESCUENTO, TRADE.IVABRUTO, TRADE.VLRETFTE, BRUTO-DESCUENTO+IVABRUTO-VLRETFTE AS 'Expr1', TRADEMAS.EFECTIVO, TRADEMAS.VLR_DEBITO, TRADEMAS.VLR_CREDIT, TRADEMAS.CREDIT_EMP, TRADE.PASSWORDIN, TRADE.NOTA, TRADEMAS.TNEGO, TRADEMAS.PARAN, TRADEMAS.CPAGO
FROM COLNOTEXSA.dbo.TRADE TRADE, COLNOTEXSA.dbo.TRADEMAS TRADEMAS, COLNOTEXSA.dbo.MTPROCLI MTPROCLI
WHERE (TRADE.TIPOVTA IN ('0-061','0-060')) AND (TRADE.TIPODCTO='FA') AND (TRADE.FECHA>='01/11/2017')
AND TRADE.TIPODCTO = TRADEMAS.TIPODCTO
AND TRADE.ORIGEN = TRADEMAS.ORIGEN
AND TRADE.NRODCTO = TRADEMAS.NRODCTO
AND MTPROCLI.NIT = TRADE.NIT

SELECT        A.NRODCTO, A.NIT,E.PRODUCTO, E.NOMBRE,E.CANTIDAD, A.FECHA, A.FECHA1, A.HORA, A.BRUTO, A.DIR, A.CAJAREG, A.PASSWORDIN, B.NOMBRE, A.TIPODCTO, A.HORA, A.TIPOVTA, C.DESCRIPCIO, A.MEDIOPAG,  A.IVABRUTO, A.BRUTO + A.IVABRUTO AS VERIFICAVAL
FROM            Trade AS A INNER JOIN
                         MtProcli AS B ON A.NIT = B.NIT INNER JOIN
                         TipoVta AS C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
                      MVTRADE AS E ON A.NRODCTO = E.NRODCTO AND A.TIPODCTO = E.TIPODCTO
WHERE (A.TIPOVTA IN ('0-061','0-060')) AND (A.TIPODCTO='FA') AND (A.FECHA>='01/01/2024')

SELECT * FROM MVTRADE WHERE NRODCTO='103582'