---inventario fisico
SELECT     A.BODEGA, E.NOMBRE, D.NOMBRE, B.CODGRUPO, C.NOMBRE, A.CODIGO, B.DESCRIPCIO, SUM(A.ICANTIDAD - A.OCANTIDAD) 
FROM         SALDOINV A INNER JOIN
                   MTMERCIA B ON A.CODIGO = B.CODIGO INNER JOIN
                   MTGRUINV C ON B.CODGRUPO = C.CODGRUPO INNER JOIN
                   MTSBLIN D ON B.CODSBLIN = D.CODSBLIN  INNER JOIN
                  MT2CLAF E ON B.CLASIFICA2 = E.CODIGO
WHERE     (A.BODEGA IN ('01.TL.GENE','02.TL.DECO','03.TL.VEST','04.TL.CLAB','05.TL.CLAC','06.TL.SEPA','07.PT.NACI','08.PT.EXPO','09.PT.VENB',
'18.CLIENTES','19.MUEBLES','20.PV.PVESTIR','34.CONSMAXI','35.CONSCARR','36.NEGESPEC','37.CONSDECO','39.CONSMUE','46.CONSEXITO','47.MARROQUI',
'50. VT. SEPA','53. HT. SEPA','54. PT. SEPA','55.CONSMODANOVA','57.PT.NACI2','59.GUATACEDI2','61.TL.GENE2',
'62.TL.DECO2','63.TL.VEST2','64.MARROQUI2','67.DIAN','58.TL.TRANSITO','71.BONDEOPT','72.BONDEOMP'))
AND B.TIPOINV IN ('TL020','TL025','TL026','TL027') 

GROUP BY A.BODEGA, E.NOMBRE, D.NOMBRE, B.CODGRUPO, C.NOMBRE, A.CODIGO, B.DESCRIPCIO
ORDER BY C.NOMBRE, B.DESCRIPCIO