SELECT        A.DIR, A.CAJAREG, A.PASSWORDIN, A.TIPODCTO, A.NRODCTO, A.FECHA, A.FECHA1, A.HORA, A.TIPOVTA, C.DESCRIPCIO, A.MEDIOPAG, A.NIT, B.NOMBRE, A.BRUTO, A.IVABRUTO, A.BRUTO + A.IVABRUTO , A.DESCUENTO
                         
FROM            Trade AS A INNER JOIN
                         MtProcli AS B ON A.NIT = B.NIT INNER JOIN
                         TipoVta AS C ON A.TIPOVTA = C.TIPOVTA 
WHERE        (A.FECHA >= '1/07/2024') 
AND (A.PASSWORDIN IN ('CAJASTD1','CAJASTD2')) 
AND (A.ORIGEN = 'FAC')
AND A.TIPODCTO NOT IN ('PD','F3') and A.NRODCTO='30680'
ORDER BY A.NRODCTO

--860509323-0

SELECT NRODCTO,FECHA, BRUTO + IVABRUTO AS TOTALPAGADO FROM TRADE  WHERE FECHA >= '1/07/2024' 

SELECT * FROM TRADE  WHERE FECHA >= '1/07/2024' AND NRODCTO='29975'