SELECT        A.NRODCTO, A.NIT,E.PRODUCTO, E.NOMBRE,E.CANTIDAD, A.FECHA, A.FECHA1, A.HORA, ROUND(E.VALORUNIT,2)AS VALORUNIT, ROUND(E.VLRVENTA,2)AS VLRVENTA, A.BRUTO, A.DIR, A.CAJAREG, A.PASSWORDIN, B.NOMBRE, A.TIPODCTO, A.HORA, A.TIPOVTA, C.DESCRIPCIO, A.MEDIOPAG,  A.IVABRUTO, A.BRUTO + A.IVABRUTO AS VERIFICAVAL, ROUND(E.HCOSTO,2)*E.CANTIDAD as costossiniva, ROUND(E.HVALUNID,2)*E.CANTIDAD as Monto_Vendido,ROUND(E.HVALUNID,2)*E.CANTIDAD-ROUND(E.HCOSTO,2)*E.CANTIDAD as ganancia, ROUND(E.HCOSTO,2)*E.CANTIDAD as COSTO_UNIT_SIN_ITBIS, ROUND(E.HVALUNID,2)*E.CANTIDAD AS PVP_SIN_ITBIS, E.IVA AS ITBIS, ROUND(E.HCOSTO*IVA/100+E.HCOSTO*E.CANTIDAD,2) as COSTO_UNIT_CON_ITBIS, ROUND(E.HVALUNID*IVA/100+E.HVALUNID*E.CANTIDAD,2) AS PVP_CON_ITBIS
FROM            Trade AS A INNER JOIN
                         MtProcli AS B ON A.NIT = B.NIT INNER JOIN
                         TipoVta AS C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
                      MVTRADE AS E ON A.NRODCTO = E.NRODCTO AND A.TIPODCTO = E.TIPODCTO
WHERE  (A.TIPODCTO in ('F2','B2')) AND (A.FECHA>='01/01/2024')AND A.ORIGEN='FAC' and A.NRODCTO='15091' ORDER BY A.NRODCTO ASC


SELECT TOP (200)* FROM Mvtrade WHERE TIPODCTO in ('F2','B2') AND FECHA>'01-10-2024' and NRODCTO=''
SELECT TOP (200)* FROM trade WHERE TIPODCTO in ('F2','B2') AND FECHA>'01-10-2024' AND ORIGEN='FAC'

SELECT TOP (200)CANTIDAD,HCOSTO, (HCOSTO*CANTIDAD)as costossiniva, (HVALUNID*CANTIDAD)as Monto_Vendido,(HVALUNID*CANTIDAD)-(HCOSTO*CANTIDAD) as ganancia, HCOSTO as COSTO_UNIT_SIN_ITBIS, HVALUNID AS PVP_SIN_ITBIS, IVA AS ITBIS, HCOSTO*IVA/100+HCOSTO as COSTO_UNIT_CON_ITBIS, HVALUNID*IVA/100+HVALUNID AS PVP_CON_ITBIS FROM Mvtrade WHERE TIPODCTO in ('F2','B2') AND FECHA>'01-10-2024' and NRODCTO=''
--QUERY ORIGINAL
SELECT        A.NRODCTO, A.NIT,E.PRODUCTO, E.NOMBRE,E.CANTIDAD, A.FECHA, A.FECHA1, A.HORA, E.VALORUNIT, E.VLRVENTA, A.BRUTO, A.DIR, A.CAJAREG, A.PASSWORDIN, B.NOMBRE, A.TIPODCTO, A.HORA, A.TIPOVTA, C.DESCRIPCIO, A.MEDIOPAG,  A.IVABRUTO, A.BRUTO + A.IVABRUTO AS VERIFICAVAL, E.IVA
FROM            Trade AS A INNER JOIN
                         MtProcli AS B ON A.NIT = B.NIT INNER JOIN
                         TipoVta AS C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
                      MVTRADE AS E ON A.NRODCTO = E.NRODCTO AND A.TIPODCTO = E.TIPODCTO
WHERE  (A.TIPODCTO in ('F2','B2')) AND (A.FECHA>='01/01/2024')AND A.ORIGEN='FAC' ORDER BY A.NRODCTO ASC