SELECT A.ORIGEN, A.TIPODCTO, B.TIPOVTA, E.DESCRIPCIO, A.FECHA, A.NRODCTO, B.NIT, D.NOMBRE, A.PRODUCTO, C.DESCRIPCIO, C.FECHA_ING, C.COSTO_ING, C.COSTO_UF,  C.COSTO_UFR, A.CANTIDAD, (A.VALORUNIT-(A.VALORUNIT*A.DESCUENTO)/100) AS VALORUNIT
FROM COLNOTEXSA.dbo.MVtrade A, COLNOTEXSA.dbo.TRADE B, COLNOTEXSA.dbo.MTMERCIA C, COLNOTEXSA.dbo.MTPROCLI D, COLNOTEXSA.dbo.TIPOVTA E
WHERE (A.FECHA>='01/06/2024' And A.FECHA<='30/06/2024') 
AND (A.TIPODCTO In ('FA','NC','ND','FR','EP') And A.TIPODCTO=B.TIPODCTO) 
AND (A.ORIGEN In ('FAC')) 
AND (B.ORIGEN = ('FAC')) 
AND (A.NRODCTO=B.NRODCTO) 
AND (A.PRODUCTO=C.CODIGO) 
AND (B.NIT=D.NIT) 
AND (E.TIPOVTA=B.TIPOVTA)
AND B.TIPOVTA NOT  IN ('0-080','0-090','0-091','0-092','0-093')
AND A.NRODCTO NOT IN ('90052')
ORDER BY D.NOMBRE, C.DESCRIPCIO

select * from MVTRADE where nrodcto='109633' AND TIPODCTO='FA'