SELECT       A.NRODCTO, b.DETALLE, A.FECHA, B.PRODUCTO, D.DESCRIPCIO , CONCAT(TRIM(B.DETALLE),B.PRODUCTO) AS CODIGO, B.CANTIDAD, B.VALUNID AS VALORUNIT
FROM         TRADE A INNER JOIN
                      MVTRADE B ON A.NRODCTO = B.NRODCTO INNER JOIN
                      MTPROCLI C ON A.NIT = C.NIT INNER JOIN
                      MTMERCIA D ON B.PRODUCTO = D.CODIGO
WHERE     (A.ORIGEN = 'INV') AND (A.TIPODCTO = 'K7') AND (B.ORIGEN = 'INV') AND (B.TIPODCTO = 'K7')
AND (a.FECHA>=getdate()-120) 
ORDER BY A.FECHA, A.NRODCTO