SELECT * FROM TRADE WHERE NRODCTO ='100609' AND CODVEN='P73'; 
EXEC sp_columns MVTRADE
SELECT * FROM MVTRADE WHERE NRODCTO ='100609'; 

EXEC sp_columns MTPROCLI

SELECT * FROM MTPROCLI 

EXEC sp_columns VENDEN

SELECT * FROM VENDEN WHERE CODVEN='P73'

SELECT*FROM MVTO WHERE DCTO ='206942'

SELECT*FROM MTMERCIA WHERE CODIGO='100609'

SELECT * FROM MVTRADE WHERE NRODCTO ='91756291'
SELECT * FROM TRADE WHERE NRODCTO ='91756291'

SELECT     A.NRODCTO, A.AUTORIZA, A.TIPOVTA, C.DESCRIPCIO, A.NIT, B.NOMBRE, A.CODVEN, D.NOMBRE , A.FECHA, F.FECHAAUT, E.FECENT, 
                      F.HHORAAUT, E.PRODUCTO, E.NOMBRE , E.CANTORIG, E.CANTIDAD , E.CANVENTA , 
                      E.CANTORIG - E.CANVENTA , E.CANTORIG - (E.CANTORIG - E.CANVENTA) , E.VLRVENTA, 
                      E.CANTORIG * E.VLRVENTA , (E.CANTORIG - E.CANVENTA) * E.VLRVENTA , A.NOTA, A.PASSWORDIN, A.HORA, A.FECMOD
FROM         TRADE A INNER JOIN
                      MTPROCLI B ON A.NIT = B.NIT INNER JOIN
                      TIPOVTA C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
                      VENDEN D ON A.CODVEN = D.CODVEN INNER JOIN
                      MVTRADE E ON A.TIPODCTO = E.TIPODCTO AND A.NRODCTO = E.NRODCTO INNER JOIN
                     TRADEMAS F ON A.NRODCTO = F.NRODCTO AND A.ORIGEN = F.ORIGEN AND A.TIPODCTO = F.TIPODCTO
WHERE     (A.TIPODCTO = 'PD') AND (A.FECHA >= getdate() -60)
AND A.TIPOVTA IN ('0-005','0-010','0-015','0-030','0-045','0-035','0-040','0-041','0-042','0-020','0-025','0-086','0-043','0-028','0-087','0-027','0-046','0-059','0-063','0-088')
AND E.CANTORIG <> 0
AND E.CANTORIG - (E.CANTORIG - E.CANVENTA) <>0
AND A.NRODCTO='91756291'
ORDER BY E.FECENT DESC, D.NOMBRE 