SELECT     A.BODEGA, B.CODGRUPO, C.NOMBRE, A.CODIGO,B.CODBARRAS, B.DESCRIPCIO, A.NIT,  D.NOMBRE, SUM(A.ICANTIDAD - A.OCANTIDAD) 
FROM         SALDOINV A INNER JOIN
                      MTMERCIA B ON A.CODIGO = B.CODIGO INNER JOIN
                      MTGRUINV C ON B.CODGRUPO = C.CODGRUPO INNER JOIN
                      MTPROCLI D ON A.NIT = D.NIT
WHERE     (A.BODEGA LIKE ('%PT%'))
GROUP BY A.BODEGA, B.CODGRUPO, C.NOMBRE, A.CODIGO, B.CODBARRAS, B.DESCRIPCIO, A.NIT, D.NOMBRE
ORDER BY C.NOMBRE, B.DESCRIPCIO

select*from TRADE where TIPODCTO='EP' AND NRODCTO='15612'

select*from MVTRADE where TIPODCTO='EP' AND NRODCTO='15612'

SELECT * FROM CONSECUT WHERE  ORIGEN ='FAC' AND DESCRIPCIO LIKE '%NOTAS CREDITO FACTURACION NACIONAL%' and CODIGOCONS ='F4NC';

use COLNOTEXSA
UPDATE        TRADEMAS
SET COPIAS = '0'
WHERE      (NRODCTO IN ('100530'))
and tipodcto='fa'


select nrodcto,copias from TRADEMAS
WHERE      (NRODCTO IN ('100530'))
and tipodcto='fa'

SELECT*FROM MVTO WHERE IDMVTO='184568'
--IN ('184568','184569','184570','184571','184572')
SELECT     A.FECHAMVTO, A.CODIGOCTA, A.CODCOMPROB, A.DCTO, A.CODCC, A.NIT, B.NOMBRE, A.BASE, A.CREDITO, A.DEBITO, A.DESCRIPCIO, 
                      A.DETALLE, c.DESCRIPCIO
FROM         MVTO A INNER JOIN
             NIT B ON A.NIT = B.NRONIT inner join cuentas c on a.codigocta = c.CODIGOCTA
WHERE     (A.FECHAMVTO >= '01/01/2023') AND (A.FECHAMVTO <= '31/12/2023') and A.CODCOMPROB='RC' AND DCTO IN ('184568')


SELECT*FROM TRADE WHERE NRODCTO IN ('100863')

SELECT*FROM MVBANCOS WHERE DCTO IN ('184568')

SELECT*FROM ABONOS WHERE DCTO IN ('184568')


------query uno para traer datos de factura 
SELECT     A.NRODCTO, A.NIT, D.NOMBRE, A.FECHA, A.FECHA1, A.BRUTO, A.CIUDADCLI, A.TRANSPORTA, A.CODVEN, C.NOMBRE , A.ENVIADOA, A.DIR, 
                      A.NOTA, A.ORDEN, A.PAIS, B.VALORUNIT, B.UNDBASE, B.UNDVENTA, B.NPEDIDO, B.CANTIDAD, E.CODIGOPLU, E.DESCRIP2, B.NOMBRE , 
                      A.REMISION
FROM         Trade AS A INNER JOIN
                      MVTRADE AS B ON A.NRODCTO = B.NRODCTO AND A.TIPODCTO = B.TIPODCTO INNER JOIN
                      VENDEN AS C ON A.CODVEN = C.CODVEN INNER JOIN
                      MTPROCLI AS D ON A.NIT = D.NIT INNER JOIN
                      MTMERCIA AS E ON B.PRODUCTO = E.CODIGO
WHERE     (A.ORIGEN = 'FAC') AND (A.TIPODCTO = 'FA')
ORDER BY A.NRODCTO, E.DESCRIP2

select  A.NRODCTO, A.NIT, A.FECHA, A.FECHA1, A.BRUTO, A.CIUDADCLI, A.TRANSPORTA, A.CODVEN, A.ENVIADOA, A.DIR, 
                      A.NOTA, A.ORDEN, A.PAIS,A.REMISION FROM  Trade AS A WHERE     (A.ORIGEN = 'FAC') AND A.FECHA >= getdate()-15

------query dos 
----EN OFIMATICA LA OPCION DE FACTURA CREDITO FISCAL ES EL B1 TRADE.NRODCTO, TRADE.NIT, TRADE.FECHA, TRADE.REMISION
SELECT *
FROM INVERSIONRD.dbo.TRADE TRADE
WHERE (TRADE.ORIGEN='FAC') 
AND (TRADE.TIPODCTO='FA')
ORDER BY TRADE.NRODCTO DESC

SELECT TRADE.NRODCTO, TRADE.NIT, TRADE.FECHA, TRADE.REMISION
FROM INVERSIONRD.dbo.TRADE TRADE
WHERE (TRADE.ORIGEN='FAC') AND (TRADE.TIPODCTO='FA')
ORDER BY TRADE.NRODCTO

----QUERY TRES
SELECT     A.NRODCTO, A.NIT, B.CODALTERNO, B.NOMBRE, C.NOMCIUD, B.TEL1, B.TEL2
FROM         TRADE AS A INNER JOIN
                      MTPROCLI AS B ON A.NIT = B.NIT INNER JOIN
                      MTCDDAN AS C ON B.CDCIIU = C.CODIGO
WHERE     (A.ORIGEN = 'FAC') AND (A.TIPODCTO = 'FA')
ORDER BY A.NRODCTO

------query
