SELECT 
    T.PRODUCTO,
	CAST(Fecha AS DATE) AS Dia, 
    SUM(ROUND(T.NVALUNID,2))*SUM(T.CANVENTA) AS TOTALVENTASSINITBIS,
	MONTH(T.Fecha) AS Mes,
	SUM(T.CANVENTA) AS Totalcantidad,
	SUM(ROUND(T.NVALUNID,2)) AS TOTALVENTAUND
FROM 
    Mvtrade as T
	WHERE T.TIPODCTO in ('B2','F2') AND T.TIPODCTO NOT IN ('PD','F3') and T.Fecha >'01-06-2024' AND ORIGEN='FAC'
GROUP BY 
    CAST(Fecha AS DATE),T.Fecha, T.PRODUCTO, T.CANVENTA
ORDER BY 
    Dia;

SELECT 
    T.PRODUCTO,
	CAST(Fecha AS DATE) AS Dia, 
    SUM(ROUND(T.NVALUNID,2))*SUM(T.CANVENTA) AS TOTALVENTASSINITBIS,
	MONTH(T.Fecha) AS Mes,
	SUM(T.CANVENTA) AS Totalcantidad,
	SUM(ROUND(T.NVALUNID,2)) AS TOTALVENTAUND
FROM 
    Mvtrade as T
	WHERE T.TIPODCTO in ('B2','F2') AND T.TIPODCTO NOT IN ('PD','F3') and T.Fecha >'01-06-2024' AND ORIGEN='FAC'
GROUP BY 
    CAST(Fecha AS DATE),T.Fecha, T.PRODUCTO, T.CANVENTA
ORDER BY 
    Dia;
