USE [COLNOTEXSA]
GO

/****** Object:  Table [dbo].[MTPROCLI]    Script Date: 19/02/2024 11:00:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MTPROCLI](
	[APELLIDO1] [char](30) NULL,
	[APELLIDO2] [char](30) NULL,
	[AUTORET] [bit] NULL,
	[BANCO] [char](9) NULL,
	[CALIFCALID] [numeric](1, 0) NULL,
	[CALIFTIEMP] [numeric](1, 0) NULL,
	[CANAL] [char](5) NULL,
	[CDCIIU] [char](5) NULL,
	[CIIU] [char](5) NULL,
	[CIUDAD] [char](5) NULL,
	[CIUDADPRV] [char](15) NULL,
	[COBRADOR] [char](60) NULL,
	[CODALTERNO] [char](15) NULL,
	[CODDESFIN] [char](5) NULL,
	[CODDESFINP] [char](5) NULL,
	[CODIGOCTA] [char](20) NULL,
	[CODIGOCTAP] [char](20) NULL,
	[CODPOSTAL] [char](20) NULL,
	[CODPOSTALP] [char](20) NULL,
	[CODPRECIO] [char](5) NULL,
	[CODPRECIOP] [char](5) NULL,
	[CODRETE] [char](5) NULL,
	[CODRETEP] [char](5) NULL,
	[CODRUTA] [char](5) NULL,
	[COL_DEL] [char](100) NULL,
	[COMENTA2] [char](250) NULL,
	[COMENTARIO] [char](100) NULL,
	[CONTACTO] [char](35) NULL,
	[CONTRIBUYE] [bit] NULL,
	[CTACTE] [char](20) NULL,
	[CUPOCR] [numeric](14, 2) NULL,
	[CUPOCRP] [numeric](17, 2) NULL,
	[CURP] [char](50) NULL,
	[DESCCOMER] [numeric](6, 2) NULL,
	[DESCCOMERP] [numeric](6, 2) NULL,
	[DESCFINAN] [numeric](6, 2) NULL,
	[DESCFINANP] [numeric](6, 2) NULL,
	[DETALLE] [text] NOT NULL,
	[DIRECCION] [char](250) NULL,
	[EMAIL] [char](250) NULL,
	[EMAILP] [char](250) NULL,
	[ENTRECALLE] [char](100) NULL,
	[ESCLIENTE] [char](1) NULL,
	[ESPROVEE] [char](1) NULL,
	[ESTRATO] [numeric](1, 0) NULL,
	[EXTERIOR] [bit] NULL,
	[FECHAING] [datetime] NULL,
	[FECNAC] [datetime] NULL,
	[FIGURA] [char](10) NULL,
	[HABILITADO] [char](1) NULL,
	[IDENTIFICA] [char](2) NULL,
	[INTCAR] [char](1) NULL,
	[LOCAL] [char](1) NULL,
	[NIT] [char](15) NOT NULL,
	[NITSUCUR] [char](15) NULL,
	[NOMBRE] [char](200) NULL,
	[NOMBRE1] [char](30) NULL,
	[NOMBRE2] [char](30) NULL,
	[NRORESOL] [char](20) NULL,
	[NUMCTA] [char](20) NULL,
	[PAGINAWEB] [char](50) NULL,
	[PASSWORD] [char](15) NULL,
	[PASSWPROV] [char](15) NULL,
	[PERIODOFAC] [numeric](3, 0) NULL,
	[PERSONANJ] [numeric](1, 0) NULL,
	[PLAZO] [numeric](3, 0) NULL,
	[PLAZOP] [numeric](3, 0) NULL,
	[PORAIU] [numeric](6, 2) NULL,
	[PORAIUP] [numeric](6, 2) NULL,
	[PRETICA] [numeric](6, 2) NULL,
	[PRETICAP] [numeric](6, 2) NULL,
	[PRETIVA] [numeric](7, 4) NULL,
	[PRETIVAP] [numeric](7, 4) NULL,
	[REGSIMP] [bit] NULL,
	[REPORTDC] [bit] NULL,
	[RESPRETE] [bit] NULL,
	[RETICA] [char](5) NULL,
	[RETICAP] [char](5) NULL,
	[STADSINCRO] [bit] NULL,
	[SUCURSAL] [bit] NULL,
	[TEL1] [char](30) NULL,
	[TEL2] [char](30) NULL,
	[TIPOCAR] [char](5) NULL,
	[TIPOCLI] [char](5) NULL,
	[TIPOCTA] [numeric](1, 0) NULL,
	[TIPOCXP] [char](5) NULL,
	[TIPOIDEN] [char](2) NULL,
	[TIPOPER] [char](2) NULL,
	[TIPOPRV] [char](5) NULL,
	[VENDEDOR] [char](15) NULL,
	[ZONA] [char](5) NULL,
	[FHCCUPO] [datetime] NULL,
	[AVALCOD] [char](15) NULL,
	[AVALDIREC] [char](250) NULL,
	[AVALNOMBRE] [char](60) NULL,
	[AVALTEL] [char](20) NULL,
	[CIUDADMX] [char](40) NULL,
	[CLASE] [char](2) NULL,
	[CODDEPTO] [char](5) NULL,
	[CONSUMIDOR] [bit] NULL,
	[CONTESP] [bit] NULL,
	[DELEGACION] [char](100) NULL,
	[ESDECLARA] [bit] NULL,
	[ESMAQUILA] [bit] NULL,
	[ESPERCAR] [bit] NULL,
	[ESRESPCREE] [bit] NULL,
	[ESRETCREE] [bit] NULL,
	[ESTADOMX] [char](100) NULL,
	[FACELECTRO] [bit] NULL,
	[FECING] [datetime] NULL,
	[FECMOD] [datetime] NULL,
	[IDADJUNTOS] [char](50) NULL,
	[IDCANALENT] [int] NULL,
	[INDEPENDIE] [bit] NULL,
	[ISPROSPECT] [bit] NULL,
	[LOCALIDAD] [char](40) NULL,
	[NDIAGRACIA] [int] NULL,
	[NROENTREGA] [char](15) NULL,
	[NROINTERNO] [char](15) NULL,
	[NUMCUENTA] [char](50) NULL,
	[PAIS] [char](5) NULL,
	[PAISMX] [char](50) NULL,
	[PASSWORDIN] [char](20) NULL,
	[PASSWORDMO] [char](20) NULL,
	[PRETPERC] [numeric](6, 2) NULL,
	[PRETPERP] [numeric](6, 2) NULL,
	[TIDENTI] [char](5) NULL,
	[CODCTANIIF] [char](20) NULL,
	[CTANIIFPRV] [char](20) NULL,
	[MEADENDA] [char](250) NULL,
	[CDUSOCFDI] [char](10) NOT NULL,
	[CLAVEPAGO] [char](3) NOT NULL,
	[MedPag] [char](5) NOT NULL,
	[BANCOCLI] [char](10) NOT NULL,
	[CODREGFIS] [char](5) NOT NULL,
	[COMPLECFDI] [char](250) NOT NULL,
	[EMAILCAR] [char](250) NOT NULL,
	[EMAILCXP] [char](250) NOT NULL,
	[EMAILFEC] [char](250) NOT NULL,
	[EXENTOIVA] [bit] NULL,
	[HABILPROV] [bit] NOT NULL,
	[NITEXTERIO] [char](20) NOT NULL,
	[PLAZOJUSTO] [bit] NOT NULL,
	[REGTRSIMP] [bit] NOT NULL,
	[COMELECTRO] [bit] NOT NULL,
	[NDIASENTREGA] [int] NOT NULL,
	[TOKENRECUP] [varchar](200) NULL,
	[SG_SST] [char](2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NIT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_APELLIDO1]  DEFAULT ('') FOR [APELLIDO1]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_APELLIDO2]  DEFAULT ('') FOR [APELLIDO2]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_AUTORET]  DEFAULT ((0)) FOR [AUTORET]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_BANCO]  DEFAULT ('0') FOR [BANCO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CALIFCALID]  DEFAULT ((0)) FOR [CALIFCALID]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CALIFTIEMP]  DEFAULT ((0)) FOR [CALIFTIEMP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CANAL]  DEFAULT ('0') FOR [CANAL]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CDCIIU]  DEFAULT ('0') FOR [CDCIIU]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CIIU]  DEFAULT ('0') FOR [CIIU]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CIUDAD]  DEFAULT ('0') FOR [CIUDAD]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CIUDADPRV]  DEFAULT ('0') FOR [CIUDADPRV]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_COBRADOR]  DEFAULT ('') FOR [COBRADOR]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CODALTERNO]  DEFAULT ('') FOR [CODALTERNO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CODDESFIN]  DEFAULT ('0') FOR [CODDESFIN]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CODDESFINP]  DEFAULT ('0') FOR [CODDESFINP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CODIGOCTA]  DEFAULT ('0') FOR [CODIGOCTA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CODIGOCTAP]  DEFAULT ('0') FOR [CODIGOCTAP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CODPOSTAL]  DEFAULT ('') FOR [CODPOSTAL]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CODPOSTALP]  DEFAULT ('') FOR [CODPOSTALP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CODPRECIO]  DEFAULT ('0') FOR [CODPRECIO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CODPRECIOP]  DEFAULT ('0') FOR [CODPRECIOP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CODRETE]  DEFAULT ('0') FOR [CODRETE]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CODRETEP]  DEFAULT ('0') FOR [CODRETEP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CODRUTA]  DEFAULT ('0') FOR [CODRUTA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_COL_DEL]  DEFAULT ('') FOR [COL_DEL]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_COMENTA2]  DEFAULT ('') FOR [COMENTA2]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_COMENTARIO]  DEFAULT ('') FOR [COMENTARIO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CONTACTO]  DEFAULT ('') FOR [CONTACTO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CONTRIBUYE]  DEFAULT ((0)) FOR [CONTRIBUYE]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CTACTE]  DEFAULT ('') FOR [CTACTE]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CUPOCR]  DEFAULT ((0)) FOR [CUPOCR]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CUPOCRP]  DEFAULT ((0)) FOR [CUPOCRP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CURP]  DEFAULT ('0') FOR [CURP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_DESCCOMER]  DEFAULT ((0)) FOR [DESCCOMER]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_DESCCOMERP]  DEFAULT ((0)) FOR [DESCCOMERP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_DESCFINAN]  DEFAULT ((0)) FOR [DESCFINAN]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_DESCFINANP]  DEFAULT ((0)) FOR [DESCFINANP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_DETALLE]  DEFAULT ('') FOR [DETALLE]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_DIRECCION]  DEFAULT ('') FOR [DIRECCION]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_EMAIL]  DEFAULT ('') FOR [EMAIL]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_EMAILP]  DEFAULT ('') FOR [EMAILP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_ENTRECALLE]  DEFAULT ('') FOR [ENTRECALLE]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_ESCLIENTE]  DEFAULT ('') FOR [ESCLIENTE]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_ESPROVEE]  DEFAULT ('') FOR [ESPROVEE]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_ESTRATO]  DEFAULT ((4)) FOR [ESTRATO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_EXTERIOR]  DEFAULT ((0)) FOR [EXTERIOR]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_FECHAING]  DEFAULT ([dbo].[F_FechasinHora](getdate())-(1825)) FOR [FECHAING]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_FECNAC]  DEFAULT ([dbo].[F_FechasinHora](getdate())) FOR [FECNAC]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_FIGURA]  DEFAULT ('') FOR [FIGURA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_HABILITADO]  DEFAULT ('') FOR [HABILITADO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_IDENTIFICA]  DEFAULT ('C') FOR [IDENTIFICA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_INTCAR]  DEFAULT ('') FOR [INTCAR]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_LOCAL]  DEFAULT ('') FOR [LOCAL]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_NIT]  DEFAULT ('0') FOR [NIT]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_NITSUCUR]  DEFAULT ('') FOR [NITSUCUR]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_NOMBRE]  DEFAULT ('VARIOS') FOR [NOMBRE]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_NOMBRE1]  DEFAULT ('') FOR [NOMBRE1]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_NOMBRE2]  DEFAULT ('') FOR [NOMBRE2]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_NRORESOL]  DEFAULT ('') FOR [NRORESOL]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_NUMCTA]  DEFAULT ('') FOR [NUMCTA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PAGINAWEB]  DEFAULT ('') FOR [PAGINAWEB]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PASSWORD]  DEFAULT ('') FOR [PASSWORD]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PASSWPROV]  DEFAULT ('') FOR [PASSWPROV]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PERIODOFAC]  DEFAULT ((0)) FOR [PERIODOFAC]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PERSONANJ]  DEFAULT ((2)) FOR [PERSONANJ]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PLAZO]  DEFAULT ((0)) FOR [PLAZO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PLAZOP]  DEFAULT ((0)) FOR [PLAZOP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PORAIU]  DEFAULT ((0)) FOR [PORAIU]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PORAIUP]  DEFAULT ((0)) FOR [PORAIUP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PRETICA]  DEFAULT ((0)) FOR [PRETICA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PRETICAP]  DEFAULT ((0)) FOR [PRETICAP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PRETIVA]  DEFAULT ((0)) FOR [PRETIVA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PRETIVAP]  DEFAULT ((0)) FOR [PRETIVAP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_REGSIMP]  DEFAULT ((0)) FOR [REGSIMP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_REPORTDC]  DEFAULT ((1)) FOR [REPORTDC]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_RESPRETE]  DEFAULT ((1)) FOR [RESPRETE]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_RETICA]  DEFAULT ('0') FOR [RETICA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_RETICAP]  DEFAULT ('0') FOR [RETICAP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_SUCURSAL]  DEFAULT ((0)) FOR [SUCURSAL]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_TEL1]  DEFAULT ('') FOR [TEL1]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_TEL2]  DEFAULT ('') FOR [TEL2]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_TIPOCAR]  DEFAULT ('0') FOR [TIPOCAR]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_TIPOCLI]  DEFAULT ('0') FOR [TIPOCLI]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_TIPOCTA]  DEFAULT ((0)) FOR [TIPOCTA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_TIPOCXP]  DEFAULT ('0') FOR [TIPOCXP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_TIPOIDEN]  DEFAULT ('0') FOR [TIPOIDEN]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_TIPOPER]  DEFAULT ('NN') FOR [TIPOPER]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_TIPOPRV]  DEFAULT ('0') FOR [TIPOPRV]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_VENDEDOR]  DEFAULT ('0') FOR [VENDEDOR]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_ZONA]  DEFAULT ('0') FOR [ZONA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_FHCCUPO]  DEFAULT ([dbo].[F_FechasinHora](getdate())) FOR [FHCCUPO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_AVALCOD]  DEFAULT ('0') FOR [AVALCOD]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_AVALDIREC]  DEFAULT ('') FOR [AVALDIREC]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_AVALNOMBRE]  DEFAULT ('') FOR [AVALNOMBRE]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_AVALTEL]  DEFAULT ('') FOR [AVALTEL]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CIUDADMX]  DEFAULT ('') FOR [CIUDADMX]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CLASE]  DEFAULT ('') FOR [CLASE]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CODDEPTO]  DEFAULT ('0') FOR [CODDEPTO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CONSUMIDOR]  DEFAULT ((0)) FOR [CONSUMIDOR]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CONTESP]  DEFAULT ((1)) FOR [CONTESP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_DELEGACION]  DEFAULT ('') FOR [DELEGACION]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_ESDECLARA]  DEFAULT ((0)) FOR [ESDECLARA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_ESMAQUILA]  DEFAULT ((0)) FOR [ESMAQUILA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_ESPERCAR]  DEFAULT ((0)) FOR [ESPERCAR]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_ESRESPCREE]  DEFAULT ((0)) FOR [ESRESPCREE]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_ESRETCREE]  DEFAULT ((0)) FOR [ESRETCREE]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_ESTADOMX]  DEFAULT ('') FOR [ESTADOMX]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_FACELECTRO]  DEFAULT ((0)) FOR [FACELECTRO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_FECING]  DEFAULT ([dbo].[F_FechasinHora](getdate())) FOR [FECING]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_FECMOD]  DEFAULT ([dbo].[F_FechasinHora](getdate())) FOR [FECMOD]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_IDADJUNTOS]  DEFAULT ('') FOR [IDADJUNTOS]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_IDCANALENT]  DEFAULT ((1)) FOR [IDCANALENT]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_INDEPENDIE]  DEFAULT ((0)) FOR [INDEPENDIE]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_ISPROSPECT]  DEFAULT ((0)) FOR [ISPROSPECT]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_LOCALIDAD]  DEFAULT ('') FOR [LOCALIDAD]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_NDIAGRACIA]  DEFAULT ((0)) FOR [NDIAGRACIA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_NROENTREGA]  DEFAULT ('') FOR [NROENTREGA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_NROINTERNO]  DEFAULT ('') FOR [NROINTERNO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_NUMCUENTA]  DEFAULT ('0') FOR [NUMCUENTA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PAIS]  DEFAULT ('169') FOR [PAIS]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PAISMX]  DEFAULT ('') FOR [PAISMX]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PASSWORDIN]  DEFAULT ('') FOR [PASSWORDIN]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PASSWORDMO]  DEFAULT ('') FOR [PASSWORDMO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PRETPERC]  DEFAULT ((0)) FOR [PRETPERC]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_PRETPERP]  DEFAULT ((0)) FOR [PRETPERP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_TIDENTI]  DEFAULT ('0') FOR [TIDENTI]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CODCTANIIF]  DEFAULT ('0') FOR [CODCTANIIF]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_CTANIIFPRV]  DEFAULT ('0') FOR [CTANIIFPRV]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MTPROCLI_MEADENDA]  DEFAULT ('') FOR [MEADENDA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ('') FOR [CDUSOCFDI]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ('0') FOR [CLAVEPAGO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  CONSTRAINT [DF_MtProCli_MedPag]  DEFAULT ('0') FOR [MedPag]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ('0') FOR [BANCOCLI]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ('ZZ') FOR [CODREGFIS]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ('') FOR [COMPLECFDI]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ('') FOR [EMAILCAR]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ('') FOR [EMAILCXP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ('') FOR [EMAILFEC]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ((0)) FOR [EXENTOIVA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ((1)) FOR [HABILPROV]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ('') FOR [NITEXTERIO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ((0)) FOR [PLAZOJUSTO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ((0)) FOR [REGTRSIMP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ((0)) FOR [COMELECTRO]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ((0)) FOR [NDIASENTREGA]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ('') FOR [TOKENRECUP]
GO

ALTER TABLE [dbo].[MTPROCLI] ADD  DEFAULT ('') FOR [SG_SST]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_CANAL] FOREIGN KEY([CANAL])
REFERENCES [dbo].[CANAL] ([CODCANAL])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_CANAL]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_CANALENT] FOREIGN KEY([IDCANALENT])
REFERENCES [dbo].[CANALENT] ([IDCANALENT])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_CANALENT]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_CIUDAD] FOREIGN KEY([CIUDAD])
REFERENCES [dbo].[CIUDAD] ([CODCIUDAD])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_CIUDAD]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_MTBANPRO] FOREIGN KEY([BANCO])
REFERENCES [dbo].[MTBANPRO] ([BANCO])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_MTBANPRO]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_MTCDDAN] FOREIGN KEY([CDCIIU])
REFERENCES [dbo].[MTCDDAN] ([CODIGO])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_MTCDDAN]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_MTCIIU] FOREIGN KEY([CIIU])
REFERENCES [dbo].[MTCIIU] ([CODIGO])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_MTCIIU]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_MTDEPTO] FOREIGN KEY([CODDEPTO])
REFERENCES [dbo].[MTDEPTO] ([CODDEPTO])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_MTDEPTO]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_MTDESFIN] FOREIGN KEY([CODDESFIN])
REFERENCES [dbo].[MTDESFIN] ([CODIGODES])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_MTDESFIN]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MtProcli_MtMedPag] FOREIGN KEY([MedPag])
REFERENCES [dbo].[MTMEDPAG] ([MEDIOPAG])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MtProcli_MtMedPag]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_MTPAISES] FOREIGN KEY([PAIS])
REFERENCES [dbo].[MTPAISES] ([CODIGO])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_MTPAISES]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_MTPRECIO] FOREIGN KEY([CODPRECIOP])
REFERENCES [dbo].[MTPRECIO] ([CODPRECIO])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_MTPRECIO]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_MTPRECIO1] FOREIGN KEY([CODPRECIO])
REFERENCES [dbo].[MTPRECIO] ([CODPRECIO])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_MTPRECIO1]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_MTRETICA] FOREIGN KEY([RETICA])
REFERENCES [dbo].[MTRETICA] ([CODRETICA])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_MTRETICA]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_MTRUTAS] FOREIGN KEY([CODRUTA])
REFERENCES [dbo].[MTRUTAS] ([CODRUTA])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_MTRUTAS]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_MTTIPOIDEN] FOREIGN KEY([TIDENTI])
REFERENCES [dbo].[MTTIPOIDEN] ([CODIGO])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_MTTIPOIDEN]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_MTTOPRTE] FOREIGN KEY([CODRETE])
REFERENCES [dbo].[MTTOPRTE] ([CODRETE])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_MTTOPRTE]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_TIPOCAR] FOREIGN KEY([TIPOCAR])
REFERENCES [dbo].[TIPOCAR] ([CODTC])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_TIPOCAR]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_TIPOCL] FOREIGN KEY([TIPOCLI])
REFERENCES [dbo].[TIPOCL] ([CODTIPOCL])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_TIPOCL]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_TIPOCXP] FOREIGN KEY([TIPOCXP])
REFERENCES [dbo].[TIPOCXP] ([CODTCXP])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_TIPOCXP]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_TIPOPRV] FOREIGN KEY([TIPOPRV])
REFERENCES [dbo].[TIPOPRV] ([CODTIPOPRV])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_TIPOPRV]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_VENDEN] FOREIGN KEY([VENDEDOR])
REFERENCES [dbo].[VENDEN] ([CODVEN])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_VENDEN]
GO

ALTER TABLE [dbo].[MTPROCLI]  WITH CHECK ADD  CONSTRAINT [FK_MTPROCLI_ZONA] FOREIGN KEY([ZONA])
REFERENCES [dbo].[ZONA] ([CODZONA])
GO

ALTER TABLE [dbo].[MTPROCLI] CHECK CONSTRAINT [FK_MTPROCLI_ZONA]
GO


