use colnotexsa
update MVTRADE
set MVTRADE.ORDENPRV= (select ORDENNRO from  ['LOTES NOVIEMBRE EXITO$']
               where MVTRADE.PRODUCTO =  ['LOTES NOVIEMBRE EXITO$'].PRODUCTO)
where MVTRADE.PRODUCTO in (select PRODUCTO from  ['LOTES NOVIEMBRE EXITO$']) AND 
(MVTRADE.NRODCTO = '0022041495') AND (MVTRADE.BODEGA = '46.CONSEXITO')


use colnotexsa
update MVTRADEEXITONOV$
set MVTRADEEXITONOV$.ORDENNRO= (select ORDENNRO from  ['LOTES NOVIEMBRE EXITO$']
               where MVTRADEEXITONOV$.PRODUCTO =  ['LOTES NOVIEMBRE EXITO$'].PRODUCTO)
where MVTRADEEXITONOV$.PRODUCTO in (select PRODUCTO from  ['LOTES NOVIEMBRE EXITO$']) AND 
(MVTRADEEXITONOV$.NRODCTO = '0022041495') AND (MVTRADEEXITONOV$.BODEGA = '46.CONSEXITO')


SELECT        TOP (200) AFECTACAR, AFECTAINV, ANTICIPO, CONSMANUAL, DCTOMAE, DESCRIPCIO, ORIGEN, POSITIVO, STADSINCRO, TIPODCTO, COMPROB, CONTROLFIS, DCTORELSAT, CODELECTRONICO, FEPREFIJO, NROPUNTO, 
                         NROSUCURSAL
FROM            TIPODCTO
WHERE        (TIPODCTO = 'NS')

SELECT        TOP (200) CARTERA, COMPRAS, CXP, DCTOMAE, DESCRIPCIO, FACTURAS, INVENTAR, STADSINCRO, TALLERES, ACTIVOS, CONTABLE, NOMINA
FROM            MTDOCMAE
WHERE        (DCTOMAE = 'ND')

SELECT        TOP (200) ACTCANT, ACTUPC, ACTVALOR, CODINT, COSTEA, DESCRIPCIO, ENTRADA, ORDEN, RECVALOR, SALDOINI, STADSINCRO, TIPOMVTO, TRASLADO, ESCOMP, DEVOLUCION, EXCLCALOTM, GARANTIA, REQSOLI
FROM            TIPOMVTO
WHERE        (TIPOMVTO = 'NS')

SELECT        TOP (200) AVISOFALTE, CODIGOCONS, CODINT, CONSECFIN, CONSECINI, CONSECUT, DESCRIPCIO, DESPEDINI, FHAUTORIZ, IDUSUARIO, NRORESOL, ORIGEN, PREFIJO, RUTAFISCAL, STADSINCRO, TIPODCTO, TIPODCTOFR, 
                         TIPOMVTO, CODENCAB, CONSFISCAL, CONSFISFIN, CONSFISINI, DIASPERIOC, DIAVIVEN, EMAIL, ENVIAMAIL, FECHAINICI, FVENRESO, IDMEDELECT, LONGITUD, NOMFORMATO, NUMLINEA, PERIOCIDAD, PREFIJOFIS, SERIE, 
                         TIPOTRANSA, CERTIFSAT, CODPOSTAL, EXTERNAKEY, LLAVEDIAN, PREFIJDIAN, ESCONTINGE
FROM            CONSECUT
WHERE        (TIPODCTO = 'NS')

SELECT        TOP (200) BANCO, BASE, CHEQUE, CODCC, CODCOMP, CODCTA, CODIGO, CODMONEDA, CREDITO, CRMONEXT, CRMULTIM, DBMONEXT, DBMULTIM, DCTO, DEBITO, DETALLE, FECHAMVTO, MODULO, NIT, NOMBRE, 
                         STADSINCRO, ESENC, ESMEDPAG, ESMOV, ESNIIF, ESOTROIMP, CODIGOUEN
FROM            TABLAINT
WHERE        (CODIGO LIKE '4%') AND (CODIGO = '418')
ORDER BY CODIGO
