USE VERONASAS
UPDATE MVTRADE
SET
CANTIDAD=CANVENTA,
CANTORIG=CANVENTA,
VALORUNIT=VLRVENTA,
VALUNID=VLRVENTA,
XVALUNID=VLRVENTA
WHERE        (NRODCTO IN ('386')) AND (TIPODCTO = 'FE')


SELECT        CANTIDAD, CANTORIG, CANVENTA, IVA, NIT, NOMBRE, NOTA, NPEDIDO, NRODCTO, PASSWORDIN, PRODUCTO, TIPODCTO, TIPOMVTO, UNDVENTA, VALORUNIT, VALUNID, VENDEDOR, VLRVENTA, 
                         VALUNID - VLRVENTA AS CRUCE
FROM            MVTRADE
WHERE        (NRODCTO IN ('275')) AND (TIPODCTO = 'FE')