USE SUPERTODO
select NRODCTO,NOTA,TIPODCTO from Trade WHERE NOTA like 'RNY #165'

select COUNT(NOTA) from AAATRADERNY1$

select 
NRODCTO,A.NOTA,B.,TIPODCTO 
from 
	Trade A
INNER JOIN
AAATRADERNY1$ B ON A.NRODCTO=B.NCF_Secuencia WHERE TIPODCTO IN ('R1','R2') ORDER BY A.NOTA ASC

update A 
SET
	A.NOTA=B.NOTA2
from 
	Trade A
INNER JOIN
AA_TRADE$ B ON A.NRODCTO=B.NCF_Secuencia 
WHERE A.TIPODCTO IN ('R1','R2')