USE SUPERTODO
--select * from MvCuadre where MEDIOPAG='11' order by FECING dESC
select * from ABOCXP WHERE DCTO='4773'
select * from ABOCXP WHERE FACTURA='5554'

select * from MVBANCOS WHERE NIT='130914273'
select * from ABONOS WHERE DCTO='6254'

select ORIGEN,NRODCTO,TIPODCTO,FECHA from Trade WHERE NIT='130914273'

select COUNT(NRODCTO) from Trade where MEDIOPAG='R4'
select COUNT(DCTO) from MvCuadre where MEDIOPAG='R4'

select A.NRODCTO from Trade A
WHERE A.MEDIOPAG='R4'

select A.NRODCTO,B.DCTO from MvCuadre B
RIGHT JOIN Trade A ON B.DCTO=A.NRODCTO
WHERE B.MEDIOPAG='R4' AND B.DCTO IS NULL