USE SUPERTODO
--select * from MvCuadre where MEDIOPAG='11' order by FECING dESC
select * from ABOCXP WHERE DCTO='4773'
select * from ABOCXP WHERE FACTURA='5554'

select ORIGEN,NRODCTO,TIPODCTO,FECHA from Trade WHERE NIT='130914273'

select ORIGEN,NRODCTO,TIPODCTO,FECHA from Trade WHERE NRODCTO='6254'

select * from MVBANCOS WHERE NIT='130914273'
select * from ABONOS WHERE DCTO='6254'