USE SUPERTODO
SELECT TOP(10)NRODCTO,TIPODCTO,PASSWORDIN,FECHA,BRUTO,IVABRUTO,NIT
FROM Trade
WHERE TIPODCTO IN ('R1')
ORDER BY CAST(NRODCTO AS INT) DESC

SELECT TOP(10)NRODCTO,TIPODCTO,PASSWORDIN,FECHA
FROM Trade
WHERE TIPODCTO IN ('R2')
ORDER BY CAST(NRODCTO AS INT) DESC

SELECT TOP(10)NRODCTO,TIPODCTO,PASSWORDIN,FECHA
FROM Trade
WHERE TIPODCTO IN ('F2')
ORDER BY CAST(NRODCTO AS INT) DESC