USE SUPERTODO
/*
SELECT NRODCTO,TIPODCTO,PASSWORDIN,FECHA,BRUTO,IVABRUTO,NIT
FROM Trade
WHERE TIPODCTO IN ('R1') AND FECHA BETWEEN '01/06/2025' AND '30/04/2026'
ORDER BY CAST(NRODCTO AS INT) DESC
*/
/*
SELECT COUNT(NRODCTO) FROM Trade WHERE TIPODCTO='R1'
SELECT COUNT(NRODCTO) FROM Mvtrade WHERE TIPODCTO='R1'
SELECT COUNT(DCTO) FROM MvCuadre WHERE TIPODCTO='R1'
*/
SELECT TOP(10)NRODCTO,TIPODCTO,PASSWORDIN,FECHA
FROM Trade
WHERE TIPODCTO IN ('R1')
ORDER BY CAST(NRODCTO AS INT) DESC

SELECT TOP(10)NRODCTO,TIPODCTO,PASSWORDIN,FECHA
FROM Trade
WHERE TIPODCTO IN ('R2')
ORDER BY CAST(NRODCTO AS INT) DESC

SELECT TOP(10)NRODCTO,TIPODCTO,PASSWORDIN,FECHA
FROM Trade
WHERE TIPODCTO IN ('F2')
ORDER BY CAST(NRODCTO AS INT) DESC