USE SUPERTODO
--REVISA PRIMERO LOS REGISTROS QUE TIENEN MEDIOPAG VACIO
SELECT T.NRODCTO, T.TIPODCTO, T.MEDIOPAG AS MEDIOPAG_ANTES, M.MEDIOPAG AS MEDIOPAG_NUEVO
FROM Trade T
INNER JOIN Mvcuadre M 
    ON T.NRODCTO = M.DCTO 
    AND T.TIPODCTO = M.TIPODCTO
    AND M.BANCO <> '0'
WHERE 
    (T.MEDIOPAG = '' OR T.MEDIOPAG IS NULL)
    AND T.FECHA >= '2024-06-01'
    AND T.ORIGEN = 'FAC'
    AND T.TIPODCTO IN ('B1','B2','B4','F2','F4','NC');
--ACTUALIZA LOS REGISTROS EN TRADE 
UPDATE T
SET T.MEDIOPAG = M.MEDIOPAG
FROM Trade T
INNER JOIN Mvcuadre M 
    ON T.NRODCTO = M.DCTO 
    AND T.TIPODCTO = M.TIPODCTO
	AND M.BANCO<>'0'
WHERE 
	(T.MEDIOPAG = '' OR T.MEDIOPAG IS NULL) 
	AND T.FECHA >='01-06-2024' 
	AND T.ORIGEN='FAC' 
	AND T.TIPODCTO IN ('B1','B2','B4','F2','F4','NC')