--REFERENCIAS PASAR DE ST A LP
USE SUPERTODO
select S.CODIGO from MtMercia S
LEFT JOIN  BESTPRICE.dbo.MtMercia B ON B.CODIGO=S.CODIGO WHERE B.CODIGO IS NULL

--REFERENCIAS NO EXISTEN EN ST
USE SUPERTODO
select B.CODIGO,B.DESCRIPCIO,B.CODBARRAS,S.CODIGO from MtMercia S
RIGHT JOIN  BESTPRICE.dbo.MtMercia B ON B.CODIGO=S.CODIGO WHERE S.CODIGO IS NULL

--REFERENCIAS EN SUPERTODO
SELECT
    (SELECT COUNT(*) FROM SUPERTODO.DBO.MtMercia) AS TOTAL_ST,
    (SELECT COUNT(*) FROM BESTPRICE.DBO.MtMercia) AS TOTAL_BR;