/*Forma 1 excluye 4 campos no aceptados por SQL*/
CREATE TRIGGER Tr_Traslada_Ref_LPZ_STD
ON BESTPRICE.dbo.MtMercia
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO SUPERTODO.dbo.MtMercia (
    ANO, ARANCEL, AREA, CLASIFICA1, CLASIFICA2, CLAVEPRSER, CODAGRUPA, CODBARRAS, CODDETRA, CODGRUPO, CODIGO, CODIGOINV, CODIGOPLU, CODIGOUEN, CODLINEA, CODRETE, CODSBLIN, 
    CODSUMIN, CODTARIVA, CODUBICA, CONVERSION, COSTO_ING, COSTO_UF, COSTO_UFR, COSTO_USD, COSTO_USDR, COSTOCOMPA, CTAAII, CTACOM, CTACOMDEV, CTACOMDIVA, CTACOMDRTE, CTACOMIVA, CTACOMRTE, 
    CTAVTA, CTAVTADEV, CTAVTADIVA, CTAVTADRTE, CTAVTAIVA, CTAVTARTE, CTDRIRCCOM, CTDRIRCVTA, CTDRIRSCOM, CTRIRCCOM, CTRIRCVTA, CTRIRSCOM, DESCRIP2, DESCRIPCIO, DESCUENTO1, 
    DESCUENTO2, DESPACHO, DETALLE, DIASREP, DIASVENCI, DTMFRCP, DTMFRSFPEP, DTMFRSPE, DTMLTCP, DTMLTPEP, ESBONO, ESCOMER, ESIMPOR, ESPRODUCTO, EXCBASIMP, FACTOR, FACTORR, FECHA_ING, 
    FECING, FECMOD, FORMATCANT, FORMATPREC, GRADOALCO, HABILITADO, HANCM, IDADJUNTOS, IMDCOLOR, IMDDCDSC, IMDDLDSC, IMDESTILO, IMDFFPF, IMDFRAGAN, IMDMANIPU1, IMDMANIPU2, 
    IMDMANIPU3, IMDMANIPU4, IMDMANIPU5, IMDMARCA, IMDNF, IMDNFABRI, IMDPA, IMDRS, IMDSABOR, IMDTALLA, IMDTT, IMDUC, IMDUCIO, IMDUD, IMDVALORVO, IMDVOLUMEN, IMPREG, INDPEDI, INDPRESU, INSUMO, 
    INVSEGUR, IPCMVALOR, IPCMVALORCIG, IPCMVALORRES, IPCMVALORSALU, IPCONSUMO, IVA, IVADIFER, LINTIPCOD, LOTEMIN, MANAIU, MATPRIMA, MAXIMO, MAYORFLE, MAYORIVA, MAYVALCOSCOM, MEAALTOUM, 
    MEAALTOVR, MEAANCHOUM, MEAANCHOVR, MEAAPROFVR, MEANMUAUM, MEANMUAVM, MEANTUM, MEANTVR, MEANUTUM, MEANUTUVR, MEAPBUM, MEAPBVR, MEAPNUN, MEAPROFUUM, MEAPSVR, MEATARAUM, 
    MEATARAVR, MEATEMPAM, MEATEMUM, MEATEMVRMA, MEATEMVRMI, MINIMO, NCTAAII, NCTACOM, NCTACOMDEV, NCTACOMDIV, NCTACOMDRT, NCTACOMIVA, NCTACOMRTE, NCTAVTA, NCTAVTADEV, NCTAVTADIV, 
    NCTAVTADRT, NCTAVTAIVA, NCTAVTARTE, NCTDRIRCCO, NCTDRIRCVT, NCTDRIRSCO, NCTRIRCCOM, NCTRIRCVTA, NCTRIRSCOM, PASSWORDIN, PASSWORDMO, PIACIFCDPR, PIACIFIDAD, PIAIACCDPR, PIAIACIDAD, 
    PIAICITEM, PIANAPCDPR, PIANAPIDAD, PMP, PORARANC, PORAYS, PORIPCMRES, PORIVADIF, PREDIAL, PRODTER, PRONOSTICO, PRUEBA, PVALLEJO, QTYCCEUM, QTYCCEVR, QTYNPUM, QTYNPVR, QTYNUCUIUM, 
    QTYNUCUIVR, REFERPROV, REQCALIDAD, REQSERIE, STADSINCRO, T_ALTO, T_ALTOUE, T_ANCHO, T_ANCHOUE, T_COSTEO, T_EMPAQUE, T_ENTREGA, T_FONDO, T_FONDOUE, T_PESOUE, TAMLOTE, TAXVLORIVA, 
    TIEMPROD, TIEMSEGU, TIPEMPAQUE, TIPOBEBIDA, TIPOINGRES, TIPOINV, TIPOTALLA, TOTALLOTE, UBICACION, UNDCONVERS, UNDEMPAQUE, UNDTIEMPOS, UNDTIESEGU, UNDTPREP, UNIDADMED, VALIPCMCIG, 
    VOLUMEN
    )
    SELECT 
    i.ANO, i.ARANCEL, i.AREA, i.CLASIFICA1, i.CLASIFICA2, i.CLAVEPRSER, i.CODAGRUPA, i.CODBARRAS, i.CODDETRA, i.CODGRUPO, i.CODIGO, i.CODIGOINV, i.CODIGOPLU, i.CODIGOUEN, i.CODLINEA, i.CODRETE, i.CODSBLIN,
    i.CODSUMIN, i.CODTARIVA, i.CODUBICA, i.CONVERSION, i.COSTO_ING, i.COSTO_UF, i.COSTO_UFR, i.COSTO_USD, i.COSTO_USDR, i.COSTOCOMPA, i.CTAAII, i.CTACOM, i.CTACOMDEV, i.CTACOMDIVA, i.CTACOMDRTE, i.CTACOMIVA, i.CTACOMRTE,
    i.CTAVTA, i.CTAVTADEV, i.CTAVTADIVA, i.CTAVTADRTE, i.CTAVTAIVA, i.CTAVTARTE, i.CTDRIRCCOM, i.CTDRIRCVTA, i.CTDRIRSCOM, i.CTRIRCCOM, i.CTRIRCVTA, i.CTRIRSCOM,i.DESCRIP2, i.DESCRIPCIO, i.DESCUENTO1,
    i.DESCUENTO2, i.DESPACHO, i.DETALLE, i.DIASREP, i.DIASVENCI, i.DTMFRCP, i.DTMFRSFPEP, i.DTMFRSPE, i.DTMLTCP, i.DTMLTPEP, i.ESBONO, i.ESCOMER, i.ESIMPOR, i.ESPRODUCTO, i.EXCBASIMP, i.FACTOR, i.FACTORR, i.FECHA_ING,
    i.FECING, i.FECMOD, i.FORMATCANT, i.FORMATPREC, i.GRADOALCO, i.HABILITADO, i.HANCM, i.IDADJUNTOS, i.IMDCOLOR, i.IMDDCDSC, i.IMDDLDSC, i.IMDESTILO, i.IMDFFPF, i.IMDFRAGAN, i.IMDMANIPU1, i.IMDMANIPU2,
    i.IMDMANIPU3, i.IMDMANIPU4, i.IMDMANIPU5, i.IMDMARCA, i.IMDNF, i.IMDNFABRI, i.IMDPA, i.IMDRS, i.IMDSABOR, i.IMDTALLA, i.IMDTT, i.IMDUC, i.IMDUCIO, i.IMDUD, i.IMDVALORVO, i.IMDVOLUMEN, i.IMPREG, i.INDPEDI, i.INDPRESU, i.INSUMO,
    i.INVSEGUR, i.IPCMVALOR, i.IPCMVALORCIG, i.IPCMVALORRES, i.IPCMVALORSALU, i.IPCONSUMO, i.IVA, i.IVADIFER, i.LINTIPCOD, i.LOTEMIN, i.MANAIU, i.MATPRIMA, i.MAXIMO, i.MAYORFLE, i.MAYORIVA, i.MAYVALCOSCOM, i.MEAALTOUM,
    i.MEAALTOVR, i.MEAANCHOUM, i.MEAANCHOVR, i.MEAAPROFVR, i.MEANMUAUM, i.MEANMUAVM, i.MEANTUM, i.MEANTVR, i.MEANUTUM, i.MEANUTUVR, i.MEAPBUM, i.MEAPBVR, i.MEAPNUN, i.MEAPROFUUM, i.MEAPSVR, i.MEATARAUM,
    i.MEATARAVR, i.MEATEMPAM, i.MEATEMUM, i.MEATEMVRMA, i.MEATEMVRMI, i.MINIMO, i.NCTAAII, i.NCTACOM, i.NCTACOMDEV, i.NCTACOMDIV, i.NCTACOMDRT, i.NCTACOMIVA, i.NCTACOMRTE, i.NCTAVTA, i.NCTAVTADEV, i.NCTAVTADIV,
    i.NCTAVTADRT, i.NCTAVTAIVA, i.NCTAVTARTE, i.NCTDRIRCCO, i.NCTDRIRCVT, i.NCTDRIRSCO, i.NCTRIRCCOM, i.NCTRIRCVTA, i.NCTRIRSCOM,i.PASSWORDIN, i.PASSWORDMO, i.PIACIFCDPR, i.PIACIFIDAD, i.PIAIACCDPR, i.PIAIACIDAD,
    i.PIAICITEM, i.PIANAPCDPR, i.PIANAPIDAD, i.PMP, i.PORARANC, i.PORAYS, i.PORIPCMRES, i.PORIVADIF, i.PREDIAL, i.PRODTER, i.PRONOSTICO, i.PRUEBA, i.PVALLEJO, i.QTYCCEUM, i.QTYCCEVR, i.QTYNPUM, i.QTYNPVR, i.QTYNUCUIUM,
    i.QTYNUCUIVR, i.REFERPROV, i.REQCALIDAD, i.REQSERIE, i.STADSINCRO, i.T_ALTO, i.T_ALTOUE, i.T_ANCHO, i.T_ANCHOUE, i.T_COSTEO, i.T_EMPAQUE, i.T_ENTREGA, i.T_FONDO, i.T_FONDOUE, i.T_PESOUE, i.TAMLOTE, i.TAXVLORIVA,
    i.TIEMPROD, i.TIEMSEGU, i.TIPEMPAQUE, i.TIPOBEBIDA, i.TIPOINGRES, i.TIPOINV, i.TIPOTALLA, i.TOTALLOTE, i.UBICACION, i.UNDCONVERS, i.UNDEMPAQUE, i.UNDTIEMPOS, i.UNDTIESEGU, i.UNDTPREP, i.UNIDADMED, i.VALIPCMCIG,
    i.VOLUMEN
    
FROM inserted i;
END;