--SUPERTODO
SELECT 
    TIPODCTO,
    COUNT(*) AS total
FROM SUPERTODO.dbo.Trade
WHERE TIPODCTO IN ('B1','B2','B4')
GROUP BY TIPODCTO;
--BESTPRICE
SELECT 
    TIPODCTO,
    COUNT(*) AS total
FROM BESTPRICE.dbo.Trade
WHERE TIPODCTO IN ('B1','B2','B4')
GROUP BY TIPODCTO;
--RANDY
SELECT 
    TIPODCTO,
    COUNT(*) AS total
FROM SUPERTODO.dbo.Trade
WHERE TIPODCTO IN ('R1','R2','R4')
GROUP BY TIPODCTO;