USE supertodo;
SELECT        
A.FECHA, B.HORA, A.TIPODCTO, A.NRODCTO, B.CAJAREG, A.BODEGA, A.CODCC, A.CODINT, 
A.PRODUCTO, A.NOMBRE, A.CANTIDAD, A.TARIVA, A.IVA, A.VALORUNIT, A.VLRVENTA,
A.VLRVENTA * A.CANTIDAD , A.VALORUNIT * A.CANTIDAD , A.VLRVENTA * A.CANTIDAD - A.VALORUNIT * A.CANTIDAD, 
A.COSTO, A.HCOSTO, B.NIT, C.NOMBRE , B.TIPOVTA, D.DESCRIPCIO, E.TIPOINV, 
F.NOMBRE , E.CODLINEA, G.NOMBRE , E.CODSBLIN, H.NOMBRE, E.CODBARRAS
FROM            Mvtrade AS A INNER JOIN
                         Trade AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO AND A.ORIGEN = B.ORIGEN INNER JOIN
                         MtProcli AS C ON B.NIT = C.NIT INNER JOIN
                         TipoVta AS D ON B.TIPOVTA = D.TIPOVTA INNER JOIN
                         MtMercia AS E ON A.PRODUCTO = E.CODIGO INNER JOIN
                         TipoInv AS F ON E.TIPOINV = F.CODIGO INNER JOIN
                         MtLinea AS G ON E.CODLINEA = G.CODLINEA INNER JOIN
                         MtSblin AS H ON E.CODSBLIN = H.CODSBLIN
WHERE        (A.FECHA >= '22/05/2024')
AND (A.ORIGEN = 'FAC')
AND A.TIPODCTO IN ('F2','B2','B1')
ORDER BY A.FECHA DESC, A.NRODCTO
--METODOS DE PAGO
SELECT MtMedPag.MEDIOPAG, MtMedPag.CONCEPTO, MtMedPag.DESCRIPCIO, MtMedPag.EFECTIVO, MtMedPag.TIPOMTVO, MtMedPag.TIPOMTVOPAGO
FROM BESTPRICE.dbo.MtMedPag MtMedPag