use BESTPRICE
select FECHA,PASSWORDIN,PASSWORDMO,PRODUCTO,NOMBRE from MVTRADE where  BODEGA='32.BEERPUB' AND PRODUCTO NOT IN ('ZZ') AND ORIGEN='FAC'
AND NOMBRE not like '%CERVEZA%' group by FECHA,PASSWORDIN,PASSWORDMO,PRODUCTO,NOMBRE ORDER BY PRODUCTO DESC

SELECT DISTINCT
    A.FECHA,A.PASSWORDIN,A.PASSWORDMO,
    A.PRODUCTO,A.NOMBRE,B.CODLINEA,C.NOMBRE,B.CODSBLIN,D.NOMBRE
FROM MVTRADE A
INNER JOIN MtMercia B 
    ON A.PRODUCTO = B.CODIGO
INNER JOIN MtLinea C 
	ON B.CODLINEA = C.CODLINEA 
INNER JOIN
    MtSblin D 
	ON B.CODSBLIN = D.CODSBLIN
WHERE A.BODEGA = '32.BEERPUB'
    AND A.PRODUCTO <> 'ZZ'
    AND A.ORIGEN = 'FAC'
    AND B.CODLINEA <> '018'
	AND B.CODSBLIN NOT IN ('001')
ORDER BY A.FECHA ASC