USE 
	BESTPRICE
SELECT  
	A.FECHA, E.NOMBRE AS CATEGORIA,C.NOMBRE AS PROVEEDOR,B.BODEGA,
	B.PRODUCTO AS CODIGO,B.NOMBRE AS DESCRIPCION,A.NRODCTO, 
	A.TIPODCTO,D.CODSBLIN, B.CANVENTA, B.COSTO, B.IVA,
	B.COSTO*B.CANVENTA AS TOTAL_COSTO,
	VLRVENTA AS PRECIO_CON_ITBIS,
	VLRVENTA/((B.IVA/100)+1) AS PRECIO_SIN_ITBIS,
	(VLRVENTA/((B.IVA/100)+1))*(DSCTOCOM/100) AS DSCTO,
	(VLRVENTA/((B.IVA/100)+1))-(VLRVENTA/((B.IVA/100)+1))*(DSCTOCOM/100) AS BRUTO_UNIT,
	((VLRVENTA/((B.IVA/100)+1))-(VLRVENTA/((B.IVA/100)+1))*(DSCTOCOM/100))*CANVENTA AS TOTAL_VENTA
	
FROM
	TRADE  A INNER JOIN
	MVTRADE B ON A.NRODCTO = B.NRODCTO AND A.TIPODCTO=B.TIPODCTO  AND A.ORIGEN = B.ORIGEN INNER JOIN
	MTPROCLI C ON C.NIT=A.NIT INNER JOIN
	MTMERCIA D ON B.PRODUCTO = D.CODIGO INNER JOIN
	MTSBLIN E ON D.CODSBLIN= E.CODSBLIN
WHERE  
	A.TIPODCTO = ('B2')
	AND A.FECHA >='01-01-2025'
	AND A.FECHA <='31-12-2025'
ORDER BY 
	A.FECHA DESC, A.NRODCTO DESC