--SHOW ALL DATA FOR ONE MONTH
USE SUPERTODO
select NRODCTO,FECHA,SUM(BRUTO+IVABRUTO) AS NETO,DESCUENTO from Trade WHERE TIPODCTO IN ('B1', 'B2', 'B4', 'F2', 'F4', 'NC') AND ORIGEN='FAC' AND FECHA BETWEEN '01/01/2025' AND '31/01/2025' GROUP BY NRODCTO,FECHA,DESCUENTO ORDER BY NRODCTO ASC
USE SUPERTODO
select CAJAREG from Trade WHERE TIPODCTO IN ('B1', 'B2', 'B4', 'F2', 'F4', 'NC') 
AND ORIGEN='FAC' AND FECHA BETWEEN '01/01/2025' AND '31/01/2025' AND CAJAREG like ' '

USE SUPERTODO
select CAJAREG,NRODCTO from Trade where NRODCTO IN ('1737','1738')
--SHOW ALL TOTAL FOR MONTH 1
USE SUPERTODO;
SELECT 
    FORMAT(FECHA, 'yyyy-MM') AS MES,
	SUM(BRUTO) AS BRUTO,
	SUM(BRUTO + IVABRUTO) AS BRUTO_IVA,
	SUM (DESCUENTO) AS DESCUENTO,
    ROUND(SUM((BRUTO + IVABRUTO) - DESCUENTO),0) AS TOTAL_NETO

FROM 
    Trade
WHERE 
    TIPODCTO IN ('B1', 'B2', 'B4', 'F2', 'F4', 'NC') AND ORIGEN='FAC'
AND FECHA BETWEEN '01/01/2025' AND '31/01/2025' GROUP BY FORMAT(FECHA, 'yyyy-MM')
ORDER BY 
    MES ASC;