USE SUPERTODO
SELECT        
	A.CAJAREG, A.PASSWORDIN, A.TIPODCTO, A.NRODCTO, A.FECHA, 
	A.HORA, C.DESCRIPCIO, A.NIT, B.NOMBRE,A.DESCUENTO, 
	A.BRUTO, A.IVABRUTO, A.BRUTO + A.IVABRUTO AS BRUTO_IVABRUTO, (A.BRUTO + A.IVABRUTO)-A.DESCUENTO AS BRUTOIVA_DESC,
	MV.EFECTIVO_PV,MV.TARJETA_DEBITO_PV,TARJETA_CREDITO_PV,MV.BONOS_PROMO_200,MV.CAMBIOS_DEVOLUCIONES,MV.TOTAL
FROM 
	Trade AS A INNER JOIN
	MtProcli AS B ON A.NIT = B.NIT LEFT JOIN
	TipoVta AS C ON A.TIPOVTA = C.TIPOVTA LEFT JOIN
	(SELECT 
    DCTO,
    TIPODCTO,
    SUM(CASE WHEN MEDIOPAG = '0' THEN VALOR ELSE 0 END) AS VARIOS,
    SUM(CASE WHEN MEDIOPAG = 'R1' THEN VALOR ELSE 0 END)+ SUM(CASE WHEN MEDIOPAG = '97' THEN VALOR ELSE 0 END) AS EFECTIVO_PV,
    SUM(CASE WHEN MEDIOPAG = 'R3' THEN VALOR ELSE 0 END) AS TARJETA_DEBITO_PV,
    SUM(CASE WHEN MEDIOPAG = 'R4' THEN VALOR ELSE 0 END) AS TARJETA_CREDITO_PV,
	SUM(CASE WHEN MEDIOPAG = 'R6' THEN VALOR ELSE 0 END) AS BONOS_PROMO_200,
	SUM(CASE WHEN MEDIOPAG = '97' THEN VALOR ELSE 0 END) AS CAMBIOS_DEVOLUCIONES,
    SUM(VALOR) AS TOTAL
FROM 
    MvCuadre
WHERE 
    FECING >= '2025-01-01' AND TIPODCTO IN ('R1','R2')
GROUP BY 
    DCTO, TIPODCTO
	) AS MV ON DCTO=A.NRODCTO
WHERE        
	(A.FECHA >='2025-01-01') AND
	(A.ORIGEN = 'FAC') AND A.TIPODCTO IN ('R1','R2')
ORDER BY A.NRODCTO