USE SUPERTODO;
SELECT 
    FORMAT(FECHA, 'yyyy-MM') AS MES,
    ROUND(SUM((BRUTO + IVABRUTO) - DESCUENTO),0) AS TOTAL_NETO

FROM 
    Trade
WHERE 
    TIPODCTO IN ('R1', 'R2','R4','B1','B2','B4','F4','NC','F2') 
AND ORIGEN='FAC'
AND FECHA BETWEEN '01/01/2026' AND '31/12/2026' 
AND NOTA LIKE 'RNY %'
AND CAJAREG NOT LIKE ' ' 
GROUP BY FORMAT(FECHA, 'yyyy-MM')
ORDER BY 
    MES ASC;