--Saber la estructura de MVTRADE
select * from MVTRADE;
EXEC sp_help trade;
-- Query 2 Consulta Facturas x Mes
USE COLNOTEXSA;
SELECT 
	MVTRADE.PRODUCTO,MVTRADE.NOMBRE,MVTRADE.BODEGA,
	MVTRADE.CODCC,MVTRADE.CANTIDAD,
    MVTRADE.VALORUNIT,TRADE.FECHA
FROM TRADE INNER JOIN 
MVTRADE ON TRADE.NRODCTO = MVTRADE.NRODCTO AND TRADE.ORIGEN = MVTRADE.ORIGEN AND TRADE.TIPODCTO = MVTRADE.TIPODCTO--Comparamos los datos
WHERE TRADE.TIPODCTO = 'FA' AND trade.FECHA between '20250101' AND '20250228' ORDER BY trade.FECHA DESC;


