--ESTA CONSULTA ES LA QUE SE IMPRIME AL MOMENTO DE OPRMIMIR EL ATAJO CTRL + K EN PVTA
Select Top 1  Ltrim(Rtrim(C.CODIGOCONS)) As CODIGOCONS, M.NUMFACTNC
From MvTrade M Inner Join CONSECUT C On M.ORIGEN = C.ORIGEN and M.TIPODCTONC = C.TIPODCTO
Where M.Origen = 'FAC' And M.NRODCTO = '707' and M.TIPODCTO = 'B4'

--las notas credito se almacenan en mvtrade, NCF MODIFICADO, son NUMFACTNC y TIPODCTONC si no hay valores aparecera vacio
select NUMFACTNC,TIPODCTONC,NRODCTO,TIPODCTO,* from Mvtrade where NUMFACTNC='11703' AND TIPODCTONC='B1'
--Y LOS DATOS DE TRADE
USE SUPERTODO
select ORIGEN,MEDIOPAG,TIPOVTA,CODCC,CODIGOCTA,CODVEN,CODINT,* from trade WHERE TIPODCTO='B4'
UNION ALL
select ORIGEN,MEDIOPAG,* from trade WHERE NRODCTO='11703' AND TIPODCTO='B1'

select NUMFACTNC,TIPODCTONC,NRODCTO,TIPODCTO,CODCC,CODINT,* from Mvtrade where TIPODCTO='B4'