SELECT 
	BANCO, CODBANCO,COMENTARIO, DCTO, FACTURA, 
	FECHACHQ, FECHAMVTO, FECING, FECMOD, IDMVCUADRE, 
	MEDIOPAG, NIT, ORIGEN, PASSWORDIN, PASSWORDMO, TIPODCTO, VALOR
FROM 
	MvCuadre
WHERE 
	(FECING >= '01/01/2025') AND MEDIOPAG <> '97' AND TIPODCTO IN ('B1','B2','B4','F2','F4')
ORDER BY TIPODCTO