USE SUPERTODO
SELECT        
	A.CAJAREG, A.PASSWORDIN, A.TIPODCTO, A.NRODCTO, A.FECHA, 
	A.HORA, C.DESCRIPCIO, A.NIT, B.NOMBRE,A.DESCUENTO, 
	A.BRUTO, A.IVABRUTO, A.BRUTO + A.IVABRUTO AS BRUTO_IVABRUTO, (A.BRUTO + A.IVABRUTO)-A.DESCUENTO AS BRUTOIVA_DESC,
	MV.EFECTIVO_PV,MV.TARJETA_DEBITO_PV,TARJETA_CREDITO_PV,MV.BONO_PROMO_200,MV.TARJETA_SUPER_CLIENTE_EFECTIVO,MV.TARJETA_SUPERCLIENTE,
	MV.TRANSFERENCIA_ELECT,MV.VENTAS_CREDITO,MV.PAGO_MOVIL_WHATSAPP,MV.TARJETA_KOMIDA,MV.KOMIDA_EFECTIVO,MV.CAMBIOS_DEVOLUCIONES,MV.TOTAL
FROM 
	Trade AS A INNER JOIN
	MtProcli AS B ON A.NIT = B.NIT INNER JOIN
	TipoVta AS C ON A.TIPOVTA = C.TIPOVTA LEFT JOIN
	(SELECT 
    DCTO,
    TIPODCTO,
    SUM(CASE WHEN MEDIOPAG = '0' THEN VALOR ELSE 0 END) AS VARIOS,
    SUM(CASE WHEN MEDIOPAG = '01' THEN VALOR ELSE 0 END)+ SUM(CASE WHEN MEDIOPAG = '97' THEN VALOR ELSE 0 END) AS EFECTIVO_PV,
    SUM(CASE WHEN MEDIOPAG = '03' THEN VALOR ELSE 0 END) AS TARJETA_DEBITO_PV,
    SUM(CASE WHEN MEDIOPAG = '04' THEN VALOR ELSE 0 END) AS TARJETA_CREDITO_PV,
	SUM(CASE WHEN MEDIOPAG = '06' THEN VALOR ELSE 0 END) AS BONO_PROMO_200,
	SUM(CASE WHEN MEDIOPAG = '08' THEN VALOR ELSE 0 END) AS TARJETA_SUPER_CLIENTE_EFECTIVO,
	SUM(CASE WHEN MEDIOPAG = '09' THEN VALOR ELSE 0 END) AS TARJETA_SUPERCLIENTE,
	SUM(CASE WHEN MEDIOPAG = '10' THEN VALOR ELSE 0 END) AS TRANSFERENCIA_ELECT,
	SUM(CASE WHEN MEDIOPAG = '11' THEN VALOR ELSE 0 END) AS VENTAS_CREDITO,
	SUM(CASE WHEN MEDIOPAG = '12' THEN VALOR ELSE 0 END) AS PAGO_MOVIL_WHATSAPP,
	SUM(CASE WHEN MEDIOPAG = '13' THEN VALOR ELSE 0 END) AS TARJETA_KOMIDA,
	SUM(CASE WHEN MEDIOPAG = '14' THEN VALOR ELSE 0 END) AS KOMIDA_EFECTIVO,
	SUM(CASE WHEN MEDIOPAG = '15' THEN VALOR ELSE 0 END) AS GANADOR_HAPY_HOUR,
	SUM(CASE WHEN MEDIOPAG = '97' THEN VALOR ELSE 0 END) AS CAMBIOS_DEVOLUCIONES,
    SUM(VALOR) AS TOTAL
FROM 
    MvCuadre
WHERE 
    FECING >= '2025-01-01' AND TIPODCTO IN ('B1','B2','B4','F2','F4','NC')
GROUP BY 
    DCTO, TIPODCTO
	) AS MV ON DCTO=A.NRODCTO
WHERE        
	(A.FECHA >='01/01/2025')
	AND (A.CAJAREG LIKE '0%') AND (A.ORIGEN = 'FAC') AND A.TIPODCTO IN ('B1','B2','B4','F2','F4','NC')
ORDER BY A.NRODCTO