SELECT
    A.FECHA, MONTH (A.FECHA) AS MES, A.TIPODCTO, A.NRODCTO, A.NIT,
    CASE
        WHEN A.TIPOVTA = '0-060' THEN 'VENTA DE BODEGA'
        ELSE D.NOMBRE
    END AS CLIENTE,
    A.TIPOVTA, B.DESCRIPCIO AS NOMBRE_TIPOVTA,
    X.NOMBRE AS CLASIFI_NOM_TIPOVTA, C.NOMBRE AS VENDEDOR, E.PRODUCTO,
    E.NOMBRE AS DESCRIP_PRODUCTO, E.CANTIDAD, E.VALORUNIT, E.DESCUENTO,
    (E.CANTIDAD * E.VALORUNIT) AS TOTALVTA,
    (E.CANTIDAD * E.VALORUNIT) * (E.DESCUENTO / 100) AS DESC_TOTVTA,
    G.COSTO_ING, G.COSTO_USD, G.FACTOR, F.VALOR,
    CASE
        WHEN A.TIPODCTO = 'NC' THEN (
            (
                (E.CANTIDAD * E.VALORUNIT) - (E.CANTIDAD * E.VALORUNIT) * (E.DESCUENTO / 100)
            ) * -1
        ) / 1000
        ELSE (
            (E.CANTIDAD * E.VALORUNIT) - (E.CANTIDAD * E.VALORUNIT) * (E.DESCUENTO / 100)
        ) / 1000
    END AS VALOR_FINAL
FROM
    TRADE A
    INNER JOIN MVTRADE E ON A.ORIGEN = E.ORIGEN
    AND A.TIPODCTO = E.TIPODCTO
    AND A.NRODCTO = E.NRODCTO
    INNER JOIN TIPOVTA B ON A.TIPOVTA = B.TIPOVTA
    INNER JOIN VENDEN C ON A.CODVEN = C.CODVEN
    INNER JOIN MTPROCLI D ON A.NIT = D.NIT
    INNER JOIN MTCAMBIO F ON A.FECHA = F.FECHA
    INNER JOIN MTMERCIA G ON E.PRODUCTO = G.CODIGO
    INNER JOIN VTIPOUEN X ON X.CODIGO = A.TIPOVTA
WHERE
    A.ORIGEN = 'FAC'
    AND A.TIPODCTO IN ('FA', 'FR', 'NC', 'ND')
    AND E.CANTIDAD > 0
    AND A.NRODCTO NOT IN ('137581', '137582')
    AND A.FECHA BETWEEN '2026-01-01' AND '2026-01-31'
ORDER BY
    A.FECHA,
    A.NRODCTO;