USE SUPERTODO
select COUNT(PRODUCTO) AS CANT_VENDIDA,PRODUCTO,NOMBRE,B.CODBARRAS from Mvtrade
INNER JOIN MtMercia B ON PRODUCTO=CODIGO
WHERE B.CODBARRAS = ' ' AND (B.CODIGO LIKE 'A-%' OR B.CODIGO LIKE 'B-%')
group by PRODUCTO,NOMBRE,B.CODBARRAS order by COUNT(PRODUCTO) DESC 
