USE SUPERTODO
SELECT 
    a.CODIGO,
	a.CODBARRAS,
    a.DESCRIPCIO,
    MAX(CASE WHEN b.CODPRECIO = '1' THEN b.PRECIO ELSE '0' END) AS PRECIO_STD_1,
    MAX(CASE WHEN b.CODPRECIO = '7' THEN b.PRECIO ELSE '0' END) AS PRECIO_RNY_7
FROM MtMercia a
LEFT JOIN MvPrecio b 
    ON a.CODIGO = b.CODPRODUC
    AND b.CODPRECIO IN ('1','7')
WHERE 
a.CODIGO like 'A%' or a.CODIGO like 'B%'
GROUP BY 
    a.CODIGO,
	a.CODBARRAS,
    a.DESCRIPCIO;