USE SUPERTODO
SELECT        
	A.DIR, A.CAJAREG, A.PASSWORDIN, A.TIPODCTO, A.NRODCTO, A.FECHA, 
	A.HORA, A.TIPOVTA, C.DESCRIPCIO, A.NIT, B.NOMBRE, 
	A.BRUTO, A.IVABRUTO, A.BRUTO + A.IVABRUTO AS BRUTO_IVABRUTO, (A.BRUTO + A.IVABRUTO)-A.DESCUENTO AS BRUTOIVA_DESC,
	MV.VALOR,MV.MEDIOPAG,ISNULL(MV97.VALOR97, 0) AS VALOR_MEDIOPAG_97
FROM 
	Trade AS A INNER JOIN
	MtProcli AS B ON A.NIT = B.NIT INNER JOIN
	TipoVta AS C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
	MvCuadre AS MV ON MV.TIPODCTO = A.TIPODCTO AND MV.DCTO = A.NRODCTO 
		LEFT JOIN (
		SELECT 
			DCTO,TIPODCTO,SUM(VALOR) AS VALOR97   -- por si hay más de uno, se agrupa
		FROM 
			MvCuadre
		WHERE 
			MEDIOPAG = '97' AND FECING >= '01/01/2025'
		GROUP BY 
			DCTO, TIPODCTO
	) AS MV97 
		ON MV97.DCTO = A.NRODCTO 
		AND MV97.TIPODCTO = A.TIPODCTO
WHERE        
	(A.FECHA >='01/01/2025') 
	AND (A.CAJAREG LIKE '00%') AND (A.ORIGEN = 'FAC') AND A.TIPODCTO IN ('R1','R2','R4','R6')
	AND MV.FECING >= '01/01/2025' AND MV.MEDIOPAG <> '97' AND MV.TIPODCTO IN ('R1','R2','R4','R6')
ORDER BY A.FECHA DESC
