-- ========== SOLICITADO SONIA FACTURAS X INTERVALO 1 HR
USE SUPERTODO
SELECT 
	DATENAME(WEEKDAY, A.FECHA) AS DIA,	
    A.FECHA,
    A.NRODCTO,
    A.HORA,
    SUM((A.BRUTO + IVABRUTO) - DESCUENTO) AS TOTAL
FROM  
    Trade AS A
WHERE 
    A.FECHA >= getdate() - 3 AND 
	A.HORA >= '12:00:00' AND A.HORA <= '13:00:00' --DATEPART(HOUR, A.HORA) BETWEEN 12 AND 13
GROUP BY
	A.FECHA,
	A.NRODCTO,
    A.HORA
ORDER BY A.FECHA ASC
-- ========== SOLICITADO SONIA FACTURAS X INTERVALO 1 HR ==========
-- ========== SOLICITADO SONIA TOTAL DE FACTURAS X DIA
USE SUPERTODO
SELECT 
    DIA,
    FECHA,
    COUNT(*) AS #_FACTURAS,
    SUM(TOTAL) AS TOTAL
FROM (
    SELECT 
        DATENAME(WEEKDAY, A.FECHA) AS DIA,
        A.FECHA,
        (A.BRUTO + IVABRUTO) - DESCUENTO AS TOTAL
    FROM  
        Trade AS A
    WHERE 
        A.FECHA >= getdate() - 3
) AS Subquery
GROUP BY
    DIA,
    FECHA
ORDER BY FECHA ASC
-- ========== SOLICITADO SONIA TOTAL DE FACTURAS X DIA ==========

-- ========== SOLICITADO SONIA DEFINITIVO INTERVALO X CANTIDAD 1 HR 
USE SUPERTODO
SELECT 
    DATENAME(WEEKDAY, A.FECHA) AS DIA,
    A.FECHA,
    DATEPART(HOUR, A.HORA) AS HORA,
    COUNT(*) AS #_FACTURAS,
    SUM((A.BRUTO + IVABRUTO) - DESCUENTO) AS TOTAL
FROM  
    Trade AS A
WHERE 
    A.FECHA >= getdate() - 54
GROUP BY
    DATENAME(WEEKDAY, A.FECHA),
    A.FECHA,
    DATEPART(HOUR, A.HORA)
ORDER BY A.FECHA ASC, HORA ASC
-- ================ SOLICITADO SONIA DEFINITIVO INTERVALO X CANTIDAD 1 HR ==========

-- ================ TOTAL X DIA 
USE SUPERTODO
SELECT 
	A.FECHA,
    SUM((A.BRUTO + IVABRUTO) - DESCUENTO) AS TOTAL
FROM  
    Trade AS A
WHERE 
    A.FECHA >= getdate() - 2
GROUP BY
	A.FECHA
-- ================ TOTAL X DIA ==========
-- ================ TOTAL X FACTURAS DEL DIA
USE SUPERTODO
SELECT 
	A.FECHA,
	A.NRODCTO,
	A.HORA,
	--ROUND(SUM(A.BRUTO+A.IVABRUTO)-A.DESCUENTO AS R
	(ROUND(SUM(A.BRUTO), 0) - ROUND(SUM(A.IVABRUTO), 0)-A.DESCUENTO) AS CANTIDAD_SALDO
FROM  
	Trade AS A
WHERE 
	A.FECHA >= getdate()-1
GROUP BY
	A.FECHA,
	A.NRODCTO,
	A.HORA,
	A.DESCUENTO
ORDER BY A.FECHA, A.HORA ASC
-- ================ TOTAL X FACTURAS DEL DIA ==========