use COLNOTEXSA
update 
	MTMERCIA
set 
	MTMERCIA.FECHA_ING = (select CAST(FECHAING AS VARCHAR) from V_ULTIMA_FECHAING
where 
	MTMERCIA.CODIGO = V_ULTIMA_FECHAING.PRODUCTO)
where 
	MTMERCIA.CODIGO in (select V_ULTIMA_FECHAING.PRODUCTO from V_ULTIMA_FECHAING)

PRINT 'Ejecucion realizada en: ' + CONVERT(VARCHAR, GETDATE(), 120);

UPDATE
	ABONOS
SET
	NIT = NITSUCUR
WHERE
	(NIT = ' ')

PRINT 'Ejecucion realizada en: ' + CONVERT(VARCHAR, GETDATE(), 120);