USE COLNOTEXSA
UPDATE M
SET M.FECHA_ING = CAST(V.FECHAING AS VARCHAR)
FROM MTMERCIA M
INNER JOIN V_ULTIMA_FECHAING V
    ON M.CODIGO = V.PRODUCTO;

PRINT 'Ejecucion realizada en: ' + CONVERT(VARCHAR, GETDATE(), 30);

/*V1
use COLNOTEXSA
update 
	MTMERCIA
set 
	MTMERCIA.FECHA_ING = (select CAST(FECHAING AS VARCHAR) from V_ULTIMA_FECHAING
where 
	MTMERCIA.CODIGO = V_ULTIMA_FECHAING.PRODUCTO)
where 
	MTMERCIA.CODIGO in (select V_ULTIMA_FECHAING.PRODUCTO from V_ULTIMA_FECHAING)
*/
UPDATE
	ABONOS
SET
	NIT = NITSUCUR
WHERE
	(NIT = ' ')

PRINT 'Ejecucion realizada en: ' + CONVERT(VARCHAR, GETDATE(), 30);