USE SUPERTODO
UPDATE MtMercia
SET
    CTACOM      = CASE WHEN CTACOM      = ' ' THEN '0' ELSE CTACOM END,
    CTACOMDEV   = CASE WHEN CTACOMDEV   = ' ' THEN '0' ELSE CTACOMDEV END,
    CTACOMDIVA  = CASE WHEN CTACOMDIVA  = ' ' THEN '0' ELSE CTACOMDIVA END,
    CTACOMDRTE  = CASE WHEN CTACOMDRTE  = ' ' THEN '0' ELSE CTACOMDRTE END,
    CTACOMIVA   = CASE WHEN CTACOMIVA   = ' ' THEN '0' ELSE CTACOMIVA END,
    CTACOMRTE   = CASE WHEN CTACOMRTE   = ' ' THEN '0' ELSE CTACOMRTE END,
    CTAVTA      = CASE WHEN CTAVTA      = ' ' THEN '0' ELSE CTAVTA END,
    CTAVTADEV   = CASE WHEN CTAVTADEV   = ' ' THEN '0' ELSE CTAVTADEV END,
    CTAVTADIVA  = CASE WHEN CTAVTADIVA  = ' ' THEN '0' ELSE CTAVTADIVA END,
    CTAVTAIVA   = CASE WHEN CTAVTAIVA   = ' ' THEN '0' ELSE CTAVTAIVA END,
    CTDRIRCCOM  = CASE WHEN CTDRIRCCOM  = ' ' THEN '0' ELSE CTDRIRCCOM END,
    CTRIRCCOM   = CASE WHEN CTRIRCCOM   = ' ' THEN '0' ELSE CTRIRCCOM END;

PRINT 'Ejecucion realizada en: ' + CONVERT(VARCHAR, GETDATE(), 30);