SELECT 
SALDOINV.BODEGA, SALDOINV.CODIGO, MTMERCIA.DESCRIPCIO, MTMERCIA.DESCRIP2, TIPOINV.NOMBRE, MTLINEA.NOMBRE, MTSBLIN.NOMBRE, MTGRUINV.NOMBRE, SUM(SALDOINV.ICANTIDAD-SALDOINV.OCANTIDAD) AS 'SALDO', MTMERCIA.CODBARRAS
FROM 
VERONASAS.dbo.MTGRUINV MTGRUINV, VERONASAS.dbo.MTLINEA MTLINEA, VERONASAS.dbo.MTMERCIA MTMERCIA, VERONASAS.dbo.MTSBLIN MTSBLIN, VERONASAS.dbo.SALDOINV SALDOINV, VERONASAS.dbo.TIPOINV TIPOINV
WHERE 
SALDOINV.CODIGO = MTMERCIA.CODIGO AND MTMERCIA.TIPOINV = TIPOINV.CODIGO AND MTMERCIA.CODLINEA = MTLINEA.CODLINEA AND MTMERCIA.CODSBLIN = MTSBLIN.CODSBLIN AND MTMERCIA.CODGRUPO = MTGRUINV.CODGRUPO
GROUP BY 
SALDOINV.BODEGA, SALDOINV.CODIGO, MTMERCIA.DESCRIPCIO, MTMERCIA.DESCRIP2, TIPOINV.NOMBRE, MTLINEA.NOMBRE, MTSBLIN.NOMBRE, MTGRUINV.NOMBRE, MTMERCIA.CODBARRAS
ORDER BY 
MTMERCIA.DESCRIPCIO, MTMERCIA.DESCRIP2, TIPOINV.NOMBRE, MTLINEA.NOMBRE, MTSBLIN.NOMBRE, MTGRUINV.NOMBRE, SALDOINV.BODEGA, SALDOINV.CODIGO

SELECT * FROM TRADE WHERE TIPODCTO IN ('K7','G1')
SELECT * FROM MVTRADE WHERE TIPODCTO IN ('K7','G1')