use VERONASAS
SELECT     A.NRODCTO, A.AUTORIZA, A.TIPOVTA, C.DESCRIPCIO, A.NIT, B.NOMBRE, A.CODVEN, D.NOMBRE , A.FECHA,  E.FECENT, 
                      E.PRODUCTO, E.NOMBRE , E.CANTORIG, E.CANTIDAD , E.CANVENTA , 
                      E.CANTORIG - E.CANVENTA , E.CANTORIG - (E.CANTORIG - E.CANVENTA) , E.VLRVENTA, E.VALORUNIT,
                      E.CANTORIG * E.VLRVENTA , (E.CANTORIG - E.CANVENTA) * E.VLRVENTA , A.NOTA, A.PASSWORDIN, A.HORA, A.FECMOD, A.REMISION, A.ORDEN, A.DCTOPRV, A.TIPODCTO
FROM         TRADE A INNER JOIN
                      MTPROCLI B ON A.NIT = B.NIT INNER JOIN
                      TIPOVTA C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
                      VENDEN D ON A.CODVEN = D.CODVEN INNER JOIN
                      MVTRADE E ON A.TIPODCTO = E.TIPODCTO AND A.NRODCTO = E.NRODCTO 

WHERE A.ORIGEN = 'fac'
AND a.FECHA>= '01/01/2024'
and a.tipodcto in ('fa','fe')
and a.nit like '80016070%'


ORDER BY E.FECENT DESC, D.NOMBRE