SELECT MtMedPag.MEDIOPAG, MtMedPag.CONCEPTO, MtMedPag.DESCRIPCIO, MtMedPag.EFECTIVO, MtMedPag.TIPOMTVO, MtMedPag.TIPOMTVOPAGO
FROM MtMedPag MtMedPag

SELECT        A.DIR, A.CAJAREG, A.PASSWORDIN, A.TIPODCTO, A.NRODCTO, A.FECHA, A.FECHA1, A.HORA, A.TIPOVTA, C.DESCRIPCIO, A.MEDIOPAG, A.NIT, B.NOMBRE, A.BRUTO, A.IVABRUTO, A.BRUTO + A.IVABRUTO , A.DESCUENTO
                         
FROM            Trade AS A INNER JOIN
                         MtProcli AS B ON A.NIT = B.NIT INNER JOIN
                         TipoVta AS C ON A.TIPOVTA = C.TIPOVTA 

WHERE        (A.FECHA >= '1/07/2024') 
AND (A.PASSWORDIN IN ('ROMELIOCJ1')) 
AND (A.ORIGEN = 'FAC')
AND A.TIPODCTO NOT IN ('PD','F3')
ORDER BY A.NRODCTO

SELECT MvCuadre.BANCO, MvCuadre.BANCODEST, MvCuadre.BANCOORI, MvCuadre.BENEF, MvCuadre.CODBANCO, MvCuadre.CODCHQDEV, MvCuadre.CODESTADO, MvCuadre.CODPLAZA, MvCuadre.CODTARJETA, MvCuadre.COMENTARIO, MvCuadre.CTACHEQUE, MvCuadre.CTADEST, MvCuadre.CTAORI, MvCuadre.DCTO, MvCuadre.FACTURA, MvCuadre.FECHACHQ, MvCuadre.FECHAMVTO, MvCuadre.FECING, MvCuadre.FECMOD, MvCuadre.IDINTEGRA, MvCuadre.IDMVCUADRE, MvCuadre.IdTeletransporte, MvCuadre.INTBANCO, MvCuadre.MEDIOPAG, MvCuadre.NIT, MvCuadre.NROAPROBA, MvCuadre.NROCHEQUE, MvCuadre.ORIGEN, MvCuadre.PAGODATAF, MvCuadre.PASSWORDIN, MvCuadre.PASSWORDMO, MvCuadre.STADSINCRO, MvCuadre.TIPODCTO, MvCuadre.TIPODCTOFA, MvCuadre.VALOR
FROM MvCuadre MvCuadre
WHERE (MvCuadre.FECING >='1/07/2024')

ORDER BY MvCuadre.TIPODCTO