SELECT        TIPODCTO, NRODCTO, FECHA
FROM            TRADE
WHERE        (NRODCTO IN ('305')) AND (TIPODCTO = 'f3') AND (ORIGEN = 'com')

SELECT        TIPODCTO, NRODCTO, FECHA
FROM            MVTRADE
WHERE        (TIPODCTO = 'f3') AND (NRODCTO IN ('305')) AND (ORIGEN = 'com')

SELECT        NRODCTO, ORIGEN, STADSINCRO, TIPODCTO, PED_ANTICI, CREDIT_EMP, NRO_APROBA, VLR_DEBITO, VLR_CREDIT, EFECTIVO, COPIAS, KBRUT, KNETO, NCAJA, TNEGO, PARAN, CPAGO, FECHAAUT, HHORAAUT, HORAAUT, 
                         COL_NOTARE, CUFE, BANCOPLANPAG, CUENTAPLANPAG, FECHA_AUTORIZACION, USUARIO_AUTORIZACION, Exportacion, MesesSAT, PeriodicidadSAT, Regimen, DocumentNumberMobile, IdUserMobile, Cal_Calidad, 
                         Cal_Entrega, Cal_SerVenta, ZEMPREDES, ZNRODOCTRA, ZTIPOTRAS
FROM            TRADEMAS
WHERE        (NRODCTO IN ('301')) AND (TIPODCTO = 'F3')