SELECT        A.DIR, A.CAJAREG, A.PASSWORDIN, A.TIPODCTO, A.NRODCTO, A.FECHA, A.FECHA1, A.HORA, A.TIPOVTA, C.DESCRIPCIO, A.MEDIOPAG, M.MEDIOPAG, T.DESCRIPCIO, A.NIT, B.NOMBRE, A.BRUTO, A.IVABRUTO, A.BRUTO + A.IVABRUTO AS TOTAL_A_PAGAR , A.DESCUENTO, M.VALOR
                         
FROM            Trade AS A INNER JOIN
                         MtProcli AS B ON A.NIT = B.NIT INNER JOIN
                         TipoVta AS C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
						 MVCUADRE AS M ON A.NRODCTO = M.DCTO INNER JOIN
						 MTMEDPAG AS T ON T.MEDIOPAG = M.MEDIOPAG
WHERE        (A.FECHA >=GETDATE()-210) 
--AND (A.PASSWORDIN IN ('CJVR010001')) 
--and A.TIPODCTO in('23','21')
 and (A.CAJAREG IN ('001','002','003'))
AND (A.ORIGEN = 'FAC')
AND A.TIPODCTO NOT IN ('PD','F3')
AND M.MEDIOPAG NOT IN('97')
AND M.FECING >=GETDATE()-210
and A.CODVEN IN ('002','003')
ORDER BY A.NRODCTO, A.TIPODCTO asc

select * from trade where FECHA >=GETDATE()-180  and tipodcto='f2'