SELECT        A.DIR, A.CAJAREG, A.PASSWORDIN, A.TIPODCTO, A.NRODCTO, A.FECHA, A.FECHA1, A.HORA, A.TIPOVTA, C.DESCRIPCIO, A.MEDIOPAG, M.MEDIOPAG, T.DESCRIPCIO, A.NIT, B.NOMBRE, A.BRUTO, A.IVABRUTO, A.BRUTO + A.IVABRUTO AS TOTAL_A_PAGAR , A.DESCUENTO, M.VALOR
                         
FROM            Trade AS A INNER JOIN
                         MtProcli AS B ON A.NIT = B.NIT INNER JOIN
                         TipoVta AS C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
						 MVCUADRE AS M ON A.NRODCTO = M.DCTO INNER JOIN
						 MTMEDPAG AS T ON T.MEDIOPAG = M.MEDIOPAG

WHERE        (A.FECHA >= '1/07/2024') 
--AND (A.PASSWORDIN IN ('CJVR010001')) 
and A.TIPODCTO in('23','21')
AND (A.ORIGEN = 'FAC')
AND A.TIPODCTO NOT IN ('PD','F3')
AND M.MEDIOPAG NOT IN('97')
ORDER BY A.NRODCTO