SELECT m.CODPRECIO, m.CODPRODUC,m.UNIDAD, c.UNIDADMED as medida_mtmercia, c.DESCRIPCIO FROM MVPRECIO as m, MTMERCIA as c WHERE CODPRECIO='01' and m.CODPRODUC=c.CODIGO

update MTMERCIA
set MTMERCIA.UNIDADMED = (select UNIDAD from MVPRECIO
               where MVPRECIO.CODPRODUC = MTMERCIA.CODIGO and MVPRECIO.CODPRECIO='02') where MTMERCIA.CODIGO in (select CODPRODUC from MVPRECIO where MVPRECIO.CODPRECIO='02') 

SELECT m.CODPRODUC,c.DESCRIPCIO FROM MVPRECIO as m, MTMERCIA as c WHERE CODPRECIO='02' and m.CODPRODUC=c.CODIGO
