/****** Script para el sacar data  en iforme de las facturas con respectivo medio de pago******/
SELECT TOP (1000) [Tipo_Dcto]
      ,[Documento]
      ,[Fecha_Dcto]
      ,[Fecha_Inicial]
	  ,MONTH(Fecha_Inicial) AS MES
	  ,DAY(Fecha_Inicial) AS DIA
      ,[Fecha_Final]
      ,[Hora]
      ,[Cliente]
      ,[Nombre_Cliente]
      ,[Cod_PuntoVenta]
      ,[Nombre_PuntoVenta]
      ,[Cod_Caja]
      ,[Nombre_Caja]
      ,[Bruto]
      ,[Descuento]
      ,[Iva]
      ,[neto]
      ,[Efectivo]
      ,[Cheque]
      ,[Tarjeta_Debito]
      ,[Tarjeta_Credito]
      ,[Ventas_A_Credito]
      ,[Bonos]
      ,[Vales]
      ,[Otros]
      ,[Saldo_A_Favor]
      ,[Transferencia]
      ,[Vueltas]
      ,[Total_Pagado]
	  ,[Vendedor]
      ,[Tipo_Venta]
      ,[Zona]
      ,[Canal]
      ,[Ciudad]
      ,[Tipo_Cliente]
      ,[Tipo_Cartera]
      ,[Centro_Costos]
      ,[Nombre_Vendedor]
      ,[Nombre_Tipo_Venta]
      ,[Nombre_Zona]
      ,[Nombre_Canal]
      ,[Nombre_Ciudad]
      ,[Nombre_Tipo_Cliente]
      ,[Nombre_Tipo_Cartera]
      ,[Nombre_Centro_Costos]
	  ,[COMENTARIO]
  FROM [VERONASAS].[dbo].[Vconcepto_Valor_PuntoVenta_prueba]  WHERE Nombre_Caja LIKE '%nueva%' and Documento='5005'
  ORDER BY DOCUMENTO ASC

  --select * from MVCUADRE where dcto='298'

  SELECT TOP (1000) [Tipo_Dcto]
      ,[Documento]
      ,[Fecha_Dcto]
      ,[Fecha_Inicial]
	  ,MONTH(Fecha_Inicial) AS MES
	  ,DAY(Fecha_Inicial) AS DIA
      ,[Fecha_Final]
      ,[Hora]
      ,[Cliente]
      ,[Nombre_Cliente]
      ,[Cod_PuntoVenta]
      ,[Nombre_PuntoVenta]
      ,[Cod_Caja]
      ,[Nombre_Caja]
      ,[Bruto]
      ,[Descuento]
      ,[Iva]
      ,[neto]
      ,[Efectivo]
      ,[Cheque]
      ,[Tarjeta_Debito]
      ,[Tarjeta_Credito]
      ,[Ventas_A_Credito]
      ,[Bonos]
      ,[Vales]
      ,[Otros]
      ,[Saldo_A_Favor]
      ,[Transferencia]
      ,[Vueltas]
      ,[Total_Pagado]
	  ,[Vendedor]
      ,[Centro_Costos]
      ,[Nombre_Vendedor]
      ,[COMENTARIO]
  FROM [VERONASAS].[dbo].[Vconcepto_Valor_PuntoVenta_prueba]  WHERE Nombre_Caja LIKE '%nueva%' and [Fecha_Inicial] >= getdate() - 180--AND Documento='298'
  ORDER BY DOCUMENTO ASC