use SUPERTODO
  SELECT [Tipo_Dcto]
      ,[Documento]
      ,[Fecha_Dcto]
      ,[Fecha_Inicial]
	  ,MONTH(Fecha_Inicial) AS MES
	  ,DAY(Fecha_Inicial) AS DIA
      ,[Fecha_Final]
      ,[Hora]
      ,[Cliente]
      ,[Nombre_Cliente]
      ,[Cod_PuntoVenta]
      ,[Nombre_PuntoVenta]
      ,[Cod_Caja]
      ,[Nombre_Caja]
      ,[Bruto]
      ,[Descuento]
      ,[Iva]
      ,[neto]
      ,[Efectivo]
      ,[Cheque]
      ,[Tarjeta_Debito]
      ,[Tarjeta_Credito]
      ,[Ventas_A_Credito]
      ,[Bonos]
      ,[Vales]
      ,[Otros]
      ,[Saldo_A_Favor]
      ,[Transferencia]
      ,[Vueltas]
      ,[Total_Pagado]
	  ,[Vendedor]
      ,[Centro_Costos]
      ,[Nombre_Vendedor]
	  ,[COMENTARIO]
  FROM [SUPERTODO].[dbo].[Vconcepto_Valor_PuntoVenta_prueba]  WHERE [Fecha_Inicial] >= getdate() - 180--AND Documento='298' and Nombre_Caja LIKE '%carulla%' 
  ORDER BY  Fecha_Inicial ASC