USE VERONASAS
SELECT     M.CAJAREGIS, M.FHINICIAL AS FEC_APERTURA_CAJA, M.FHFINAL AS FEC_CIERRE_CAJA, NOMBRE AS PUNTO_DE_VENTA, M.USUARIO,C.VALOR, T.DESCRIPCIO
FROM            MVCAJAREG AS M, MVCAJAMEDIOS AS C, MTMEDPAG AS T, MTPVENTA as P
WHERE        (USUARIO = 'SUPERGACJ1') AND M.IDMVCAJREG=C.IDMVCAJREG AND C.MEDIOPAGO=T.MEDIOPAG AND P.CODIGO=M.PUNTOVENTA

SELECT        TOP (200) CANTIDAD, ESTADO, IDMVCAJMED, IDMVCAJREG, MEDIOPAGO, STADSINCRO, VALOR, IdTeletransporte
FROM            MVCAJAMEDIOS