USE [CONTROL_OFIMAEnterprise]
GO

/****** Object:  Table [dbo].[CONFIGURACIONGLOBAL]    Script Date: 07/06/2024 14:59:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONFIGURACIONGLOBAL](
	[IDCONFIGURACIONGLOBAL] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ULTFHCONSULACTUALIZACION] [datetime] NULL,
	[ULTIMAVERSIONCONSULTADA] [numeric](12, 0) NULL,
	[VERSIONOFIMAINSTALADA] [numeric](12, 0) NULL,
	[VERSIONROBOTINSTALADA] [numeric](12, 0) NULL,
	[CREARCARPETAS] [bit] NULL,
	[MODELOVISTAS] [int] NULL,
	[RUTAVISTAS] [char](250) NULL,
	[RUTACOMUNANTERIOR] [varchar](500) NOT NULL,
	[RUTATECNICOANTERIOR] [varchar](500) NOT NULL,
	[RUTADEFINICIONES] [varchar](500) NOT NULL,
	[LINKGOLDPARTNER] [varchar](500) NOT NULL,
	[LINKOFIMACOMPUTO] [varchar](500) NOT NULL,
	[SERIALSOFTWARE] [uniqueidentifier] NOT NULL,
	[ESOFIMAPYME] [bit] NOT NULL,
	[SEGURIDADPLUS] [bit] NOT NULL,
	[VERSIONPUBLICADA] [numeric](12, 0) NOT NULL,
	[ACTIVAOFIMASIS] [bit] NOT NULL,
	[ACTIVASERVICEPORTAL] [bit] NOT NULL,
	[FechaAlertaTeletransporte] [datetime] NOT NULL,
	[FHCONTROLRD] [datetime] NULL,
	[HABILITARBOTONPILDOR] [bit] NOT NULL,
	[PROGRAMADOAE] [bit] NOT NULL,
	[usaProxy] [bit] NULL,
	[direccionProxy] [varchar](100) NULL,
	[puertoProxy] [varchar](10) NULL,
	[usuarioProxy] [varchar](100) NULL,
	[contrasenaProxy] [varchar](100) NULL,
	[URLServicioWeb] [varchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDCONFIGURACIONGLOBAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONFIGURACIONGLOBAL] ADD  DEFAULT ('') FOR [RUTACOMUNANTERIOR]
GO

ALTER TABLE [dbo].[CONFIGURACIONGLOBAL] ADD  DEFAULT ('') FOR [RUTATECNICOANTERIOR]
GO

ALTER TABLE [dbo].[CONFIGURACIONGLOBAL] ADD  DEFAULT ('') FOR [RUTADEFINICIONES]
GO

ALTER TABLE [dbo].[CONFIGURACIONGLOBAL] ADD  DEFAULT ('') FOR [LINKGOLDPARTNER]
GO

ALTER TABLE [dbo].[CONFIGURACIONGLOBAL] ADD  DEFAULT ('') FOR [LINKOFIMACOMPUTO]
GO

ALTER TABLE [dbo].[CONFIGURACIONGLOBAL] ADD  DEFAULT (newid()) FOR [SERIALSOFTWARE]
GO

ALTER TABLE [dbo].[CONFIGURACIONGLOBAL] ADD  DEFAULT ((0)) FOR [ESOFIMAPYME]
GO

ALTER TABLE [dbo].[CONFIGURACIONGLOBAL] ADD  DEFAULT ((0)) FOR [SEGURIDADPLUS]
GO

ALTER TABLE [dbo].[CONFIGURACIONGLOBAL] ADD  DEFAULT ((0)) FOR [ACTIVAOFIMASIS]
GO

ALTER TABLE [dbo].[CONFIGURACIONGLOBAL] ADD  DEFAULT ((0)) FOR [ACTIVASERVICEPORTAL]
GO

ALTER TABLE [dbo].[CONFIGURACIONGLOBAL] ADD  DEFAULT ([dbo].[F_FechasinHora](getdate())) FOR [FechaAlertaTeletransporte]
GO

ALTER TABLE [dbo].[CONFIGURACIONGLOBAL] ADD  DEFAULT (NULL) FOR [FHCONTROLRD]
GO

ALTER TABLE [dbo].[CONFIGURACIONGLOBAL] ADD  DEFAULT ((0)) FOR [HABILITARBOTONPILDOR]
GO

ALTER TABLE [dbo].[CONFIGURACIONGLOBAL] ADD  DEFAULT ((0)) FOR [PROGRAMADOAE]
GO

2023-09-16 17:19:51.987


