USE VERONASAS;

WITH K7 AS (
    SELECT DISTINCT
        TR.NRODCTO,
        MV.CONSECUT AS CONSECUTIVO,
		SUM(MV.VALUNID*MV.CANTIDAD) AS BRUTO
    FROM TRADE TR
    JOIN MVTRADE MV 
        ON TR.NRODCTO = MV.NRODCTO
       AND TR.TIPODCTO = MV.TIPODCTO
    WHERE TR.ORIGEN = 'inv'
      AND TR.TIPODCTO = 'K7'
     GROUP BY TR.NRODCTO, MV.CONSECUT 
),

G1 AS (
    SELECT DISTINCT
        TR.NRODCTO,
        MV.CONSECUT AS CONSECUTIVO,
		SUM(MV.VALUNID*MV.CANTIDAD) AS BRUTO
    FROM TRADE TR
    JOIN MVTRADE MV 
        ON TR.NRODCTO = MV.NRODCTO
       AND TR.TIPODCTO = MV.TIPODCTO
    WHERE TR.ORIGEN = 'inv'
      AND TR.TIPODCTO = 'G1'
      GROUP BY TR.NRODCTO, MV.CONSECUT
)

SELECT
    K7.NRODCTO,
    K7.CONSECUTIVO AS CONSECUTIVO_K7,
    G1.CONSECUTIVO AS CONSECUTIVO_G1,
	K7.BRUTO AS BRUTO_K7,
	G1.BRUTO AS BRUTO_G1,
    CASE
        WHEN G1.CONSECUTIVO IS NULL THEN 'No existe en G1'
        ELSE 'Igual'
    END AS ESTADO

FROM K7
LEFT JOIN G1
    ON K7.CONSECUTIVO = G1.CONSECUTIVO

ORDER BY K7.CONSECUTIVO;

use BESTPRICE
 SELECT SUM(Valor)
                FROM MvCuadre AS sub
                WHERE sub.DCTO = '18340'
				  AND Sub.FechaMvto='2025-01-01'
                  AND sub.Banco = 0
                  AND sub.Valor < 0


select * from MvCuadre where DCTO = '18340'