------- querys para actaulizar Informe de facturacion 

-- query conexion 1 a.nrodcto,
SELECT     a.FECHA, a.nrodcto, a.TIPODCTO, d.NOMBRE, a.TIPOVTA, b.DESCRIPCIO, c.NOMBRE , a.BRUTO, ((a.BRUTO - a.DESCUENTO)/1000) 
FROM         TRADE a INNER JOIN
                      TIPOVTA b ON a.TIPOVTA = b.TIPOVTA INNER JOIN
                      VENDEN c ON a.CODVEN = c.CODVEN INNER JOIN
                      MTPROCLI d ON a.NIT = d.NIT
WHERE     (a.ORIGEN = 'FAC') --AND (a.TIPODCTO Not In ('NC','P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12','14','15','16','17','18','19','20','21','AJ')) 
AND (A.FECHA Between '01/01/2024' And '31/12/2024')
AND A.codven IN ('P47')
ORDER BY    a.FECHA

---query datos
SELECT a.FECHA, a.TIPODCTO, a.TIPOVTA, b.DESCRIPCIO, c.NOMBRE, a.BRUTO, ((A.BRUTO-A.DESCUENTO)/1000) AS 'SUBT'
FROM COLNOTEXSA.dbo.trade a, COLNOTEXSA.dbo.tipovta b, COLNOTEXSA.dbo.venden c
WHERE (a.ORIGEN='FAC') AND (a.TIPOVTA=b.tipovta And a.codven In ('P47')) AND (c.CODVEN=a.codven) AND (a.TIPODCTO Not In ('P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12','14','15','16','17','18','19','20','21','AJ'))
AND (A.FECHA Between '01/01/2024' And '31/12/2024')
ORDER BY a.TIPODCTO

-----query DatosProd
SELECT A.FECHA, A.TIPODCTO, A.NRODCTO, D.NOMBRE, A.TIPOVTA, B.DESCRIPCIO, C.NOMBRE, E.PRODUCTO, E.NOMBRE, E.CANTIDAD, E.VALORUNIT, (E.CANTIDAD*E.VALORUNIT) AS 'TOTALVTA', G.COSTO_ING, G.COSTO_USD, G.FACTOR, F.VALOR, E.DESCUENTO
FROM COLNOTEXSA.dbo.TRADE A, COLNOTEXSA.dbo.TIPOVTA B, COLNOTEXSA.dbo.VENDEN C, COLNOTEXSA.dbo.MTPROCLI D, COLNOTEXSA.dbo.MVTRADE E, COLNOTEXSA.dbo.MTCAMBIO F, COLNOTEXSA.dbo.MTMERCIA G, COLNOTEXSA.dbo.MTGRUINV H
WHERE (A.ORIGEN='FAC' And A.ORIGEN=E.ORIGEN) AND (A.TIPODCTO Not In ('P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12','14','15','16','17','18','19','20','21','AJ') And A.TIPODCTO=E.TIPODCTO) 
AND (A.FECHA Between '01/01/2024' And '31/12/2024' And A.FECHA=F.FECHA) AND (A.NRODCTO=E.NRODCTO) AND (A.TIPOVTA=B.TIPOVTA And A.codven In ('P47')) AND (E.PRODUCTO=G.CODIGO) AND (G.CODGRUPO=H.CODGRUPO) AND (A.NIT=D.NIT) AND (A.CODVEN=C.CODVEN) AND (E.CANTIDAD>0)
ORDER BY A.FECHA, A.NRODCTO
