SELECT        A.NRODCTO, B.NOMBRE as CLIENTE,A.DIR, A.CIUDADCLI,B.TEL1, A.NIT, A.PASSWORDIN, E.PRODUCTO, F.CODBARRAS, E.NOMBRE, E.CANTIDAD, E.UNDVENTA, A.FECHA, A.BRUTO,  A.CAJAREG, A.TIPODCTO, A.HORA, A.TIPOVTA, C.DESCRIPCIO, A.MEDIOPAG,  A.IVABRUTO, E.VLRVENTA AS VERIFICAVAL, 
                          E.VALORUNIT, E.CANTORIG * E.VALORUNIT , E.nota AS NOTA_MV,E.IVA
FROM            Trade AS A INNER JOIN
                         MtProcli AS B ON A.NIT = B.NIT INNER JOIN
                         TipoVta AS C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
                         --MvCuadre AS D ON A.TIPODCTO = D.TIPODCTO AND A.NRODCTO = D.DCTO AND A.ORIGEN = D.ORIGEN  INNER JOIN
                      MVTRADE AS E ON A.NRODCTO = E.NRODCTO AND A.TIPODCTO = E.TIPODCTO INNER JOIN
					  MtMercia AS F ON E.PRODUCTO = F.CODIGO
WHERE        A.FECHA >= getdate() - 180 AND (A.ORIGEN = 'COM') AND (A.TIPODCTO = 'OR') 
ORDER BY A.NRODCTO DESC

SELECT     A.NRODCTO,C.NOMBRE AS CLIENTE,C.TEL1,A.NIT, B.PRODUCTO, B.CANTIDAD, C.DIRECCION,a.DCTOPRV, B.BODEGA, A.TIPODCTO, A.FECHA, A.FECING, B.FECENT, A.AUTORIZA, B.NOMBRE , 
                      B.IVA ,B.CANTORIG , B.CANVENTA , B.VALORUNIT, B.CANTORIG * B.VALORUNIT , b.nota AS NOTA_MV, A.NOTA
FROM         TRADE A INNER JOIN
                      MTPROCLI C ON A.NIT = C.NIT INNER JOIN
                      MVTRADE B ON A.NRODCTO = B.NRODCTO AND A.TIPODCTO = B.TIPODCTO
WHERE     (A.ORIGEN = 'COM') AND (A.TIPODCTO = 'OR') AND A.NRODCTO='377'
AND A.FECHA >= getdate() - 180
ORDER BY A.nrodcto ASC

SELECT * FROM MTPROCLI WHERE NIT='101007631'