SELECT MTMERCIA.CODIGO, MTMERCIA.DESCRIPCIO, MTMERCIA.COSTO_ING, MTMERCIA.COSTO_USDR, MTMERCIA.FACTORR, MTMERCIA.COSTO_UFR,MTMERCIA.CLIENTE_PR
FROM COLNOTEXSA.dbo.MTMERCIA MTMERCIA
WHERE MTMERCIA.TIPOINV LIKE 'PT%'

SELECT MTMERCIA.CODIGO, MTMERCIA.DESCRIPCIO, MTMERCIA.COSTO_ING, MTMERCIA.COSTO_USDR, MTMERCIA.FACTORR, MTMERCIA.COSTO_UFR,MTMERCIA.CLIENTE_PR
FROM COLNOTEXSA.dbo.MTMERCIA MTMERCIA WHERE 

SELECT A.FECHA, B.DESCRIPCIO,E.PRODUCTO, G.CODIGO, E.NOMBRE, E.VALORUNIT, G.COSTO_ING, G.COSTO_USD, G.FACTOR, F.VALOR
FROM COLNOTEXSA.dbo.TRADE A, COLNOTEXSA.dbo.TIPOVTA B, COLNOTEXSA.dbo.VENDEN C, COLNOTEXSA.dbo.MTPROCLI D, COLNOTEXSA.dbo.MVTRADE E, COLNOTEXSA.dbo.MTCAMBIO F, COLNOTEXSA.dbo.MTMERCIA G, COLNOTEXSA.dbo.MTGRUINV H
WHERE (A.ORIGEN='FAC' And A.ORIGEN=E.ORIGEN) AND (A.TIPODCTO Not In ('P1','P2','P3','RE','AN','CD','06','13','PD','03','04','05','07','08','09','10','11','12','14','15','16','17','18','19','20','21','AJ','EP','CT','OP','OR','OF','OT','OM') And A.TIPODCTO=E.TIPODCTO) 
AND (A.FECHA Between '01/01/2024' And '31/12/2024' And A.FECHA=F.FECHA)
 AND (A.NRODCTO=E.NRODCTO) AND (A.TIPOVTA=B.TIPOVTA And A.TIPOVTA In ('0-035','0-040','0-041','0-042','0-043','0-046')) AND (E.PRODUCTO=G.CODIGO) AND (G.CODGRUPO=H.CODGRUPO) AND (A.NIT=D.NIT) AND (A.CODVEN=C.CODVEN) AND (E.CANTIDAD>0)
ORDER BY A.FECHA, A.NRODCTO