select CODIGOCTA, DCTO,FECHA,FECING, FECMOD,NIT, VALOR, TIPODCTO, PASSWORDIN AS USUARIO, DETALLE from MVBANCOS where dcto ='91298' and Fecha>'01-02-2024' 
select BANCO,DCTO, FECHA, FECING,FECMOD, NIT, VALOR, TIPODCTO, PASSWORDIN AS USUARIO, NOTA from ABOCXP where dcto ='91298' 
SELECT CODIGOCTA, DCTO, CODCOMPROB, DEBITO, CREDITO, FECHAMVTO,  FECING,FECMOD, NIT, CODCOMPROB, PASSWORDIN AS USUARIO, DETALLE FROM MVTO where DCTO  IN ('91298')  AND CODCOMPROB='CE'

------query para ver descuadres de bancos 

SELECT ANO, CODCC, CODIGOCTA, CREDITO, CRMONEXT, DBMONEXT, DEBITO, NIT, PERIODO, STADSINCRO, NIIF
FROM SALDCONT
WHERE (CODIGOCTA IN ('2105')) 
ORDER BY ANO, PERIODO


SELECT CODIGOCTA, SALDOANTDB, SALDOANTCR, SALDOANTDB-SALDOANTCR AS SALDO, DMES13, CMES13, DMES13-CMES13 AS EXPR1
FROM CUENTAS
WHERE (CODIGOCTA LIKE '2105')
ORDER BY CODIGOCTA


SELECT NIT, CODIGOCTA, SALDOANTDB, SALDOANTCR, SALDOANTDB-SALDOANTCR AS SALDO, DMES13, CMES13, DMES13-CMES13 AS EXPR1
FROM TERCEROS
WHERE (CODIGOCTA LIKE '14650101')
ORDER BY CODIGOCTA
---CUENTAS EXTRANJERAS
SELECT        NIT, CODIGOCTA, SALDOANTDX, SALDOANTCX, SALDOANTDX - SALDOANTCX AS SALDO, DMES13, CMES13, DMES13 - CMES13 AS EXPR1
FROM            TERCEROS
WHERE        (CODIGOCTA LIKE '11101003') AND (NIT = '132487907')
ORDER BY CODIGOCTA
--query para ver terceros ventas mes por mes en dolares
use COLNOTEXSA
SELECT NIT, CODIGOCTA, SALDOANTDX, SALDOANTCX, CXABRIL, CXAGOSTO, CXDICIEMBR, CXENERO, CXFEBRERO, CXJULIO, CXJUNIO, CXMARZO, CXMARZO, CXMAYO, CXMES13, CXNOVIEMBR, CXOCTUBRE, CXSEPTIEMB, SALDOANTDX - SALDOANTCX AS SALDO
FROM TERCEROS
WHERE (CODIGOCTA LIKE '14650101') 
ORDER BY CODIGOCTA