SELECT     A.NRODCTO, B.BODEGA, A.TIPODCTO, A.NIT, C.NOMBRE, A.FECHA,  A.FECHA1, A.FECING, B.FECENT, A.AUTORIZA, B.PRODUCTO, B.NOMBRE , 
                      B.CANTIDAD, B.CANTORIG , B.CANVENTA , B.VALORUNIT, B.CANTORIG * B.VALORUNIT , A.NOTA
FROM         TRADE A INNER JOIN
             MTPROCLI C ON A.NIT = C.NIT INNER JOIN
             MVTRADE B ON A.NRODCTO = B.NRODCTO AND A.TIPODCTO = B.TIPODCTO
WHERE     (A.ORIGEN = 'COM') AND (A.TIPODCTO = 'OR') 
AND A.NRODCTO ='91500'
AND A.FECHA >=01/01/2019
ORDER BY A.nrodcto DESC

select * from trade where nrodcto in ('91500','91599') and (ORIGEN = 'COM') AND (TIPODCTO = 'OR')
select * from MVTRADE where nrodcto in ('91500','91599') and (ORIGEN = 'COM') AND (TIPODCTO = 'OR')