USE VERONASAS
SELECT     A.NRODCTO, A.BRUTO, A.CIUDADCLI, A.CODCC, C.DIRECCION, A.FECHA, A.FECHA1, A.IVABRUTO, A.NIT, A.NOTA, A.OTRAMON, A.VLRETFTE, A.VRECICA, A.VRETENIVA, A.VRETIVA,B.BODEGA,B.CANTIDAD,B.FECENT,B.PRODUCTO,C.NOMBRE,B.VALUNID AS VALORUNIT, 
                       D.DESCRIPCIO , C.TEL1,    B.DESCUENTO, B.IVA
FROM         TRADE A INNER JOIN
                      MVTRADE B ON A.NRODCTO = B.NRODCTO INNER JOIN
                      MTPROCLI C ON A.NIT = C.NIT INNER JOIN
                      MTMERCIA D ON B.PRODUCTO = D.CODIGO
WHERE     (A.ORIGEN = 'INV') AND (A.TIPODCTO = 'K7') AND (B.ORIGEN = 'INV') AND (B.TIPODCTO = 'K7')
AND A.FECHA >= '01/08/2024'
ORDER BY A.FECHA, A.NRODCTO

SELECT * FROM MVTRADE WHERE TIPODCTO = 'K7' AND FECHA >= '01/08/2024'

SELECT * FROM MTMERCIA WHERE CODIGO='1020000107638'

USE SUPERTODO
SELECT * FROM TablaInt