SELECT        A.NRODCTO, A.TIPODCTO, A.FECHA, B.FECENT,B.FECING, B.FECMOD, B.FHCOMPRA, A.CODCC, A.TIPOVTA, A.REMISION, A.NIT, F.NOMBRE, A.CIUDADCLI, B.PRODUCTO, C.CODBARRAS, C.DESCRIPCIO, C.DESCRIP2,
                         D.NOMBRE , E.NOMBRE , B.CANTIDAD, B.NOTA , A.NOTA
FROM            TRADE AS A INNER JOIN
                         MVTRADE AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO INNER JOIN
                         MTMERCIA AS C ON B.PRODUCTO = C.CODIGO INNER JOIN
                         MT1CLAF AS D ON C.CLASIFICA1 = D.CODIGO INNER JOIN
                         MTGRUINV AS E ON C.CODGRUPO = E.CODGRUPO INNER JOIN
                         MTPROCLI AS F ON A.NIT = F.NIT
WHERE        (A.TIPODCTO = 'EP') AND (A.FECHA >= getdate() -360)and REMISION LIKE'%REPROCESO%'
ORDER BY  A.NRODCTO DESC, B.PRODUCTO

SELECT * FROM MVTRADE WHERE TIPODCTO = 'EP' AND FECHA >'01-01-2024' 
SELECT * FROM TRADE WHERE TIPODCTO = 'EP' AND FECHA >'01-01-2024' and REMISION LIKE'%REPROCESO%'