SELECT MTMERCIA.CODIGO, MTMERCIA.CODBARRAS, MTMERCIA.DESCRIPCIO, MTMERCIA.TIPOINV, MTMERCIA.CODLINEA, MTMERCIA.CODSBLIN, MTMERCIA.CODGRUPO, MTMERCIA.FECHA_ING, MTMERCIA.CLASIFICA1, MTMERCIA.CTACOM, MTMERCIA.CTACOMDEV, MTMERCIA.CTACOMDIVA, MTMERCIA.CTACOMDRTE, MTMERCIA.CTACOMIVA, MTMERCIA.CTACOMRTE, MTMERCIA.CTAVTA, MTMERCIA.CTAVTADEV, MTMERCIA.CTAVTADIVA, MTMERCIA.CTAVTADRTE, MTMERCIA.CTAVTAIVA, MTMERCIA.CTAVTARTE,MTMERCIA.CTACOM AS Gastos,MTMERCIA.CTACOMDEV as DevoGastos,MTMERCIA.CTACOMDIVA AS Gastoscta1,MTMERCIA.CTACOMIVA AS Gastoscta2, MTMERCIA.CTACOMDRTE as Gastoscta3,  MTMERCIA.CTACOMRTE as Gastoscta4, MTMERCIA.CTDRIRCCOM AS RegiComun, MTMERCIA.CTRIRCCOM AS DevRegComun,MTMERCIA.CLIENTE_PR, MTMERCIA.CLASIFICA1
FROM COLNOTEXSA.dbo.MTMERCIA MTMERCIA
WHERE (MTMERCIA.HABILITADO=1) AND (MTMERCIA.ESPRODUCTO=1) AND (MTMERCIA.TIPOINV In ('0','PT005','PT010','PT015','PT020','TPB00','PT040','PT001','TL027','TL045','SM001'))
ORDER BY MTMERCIA.TIPOINV DESC, MTMERCIA.DESCRIPCIO

select * from v_cancidesrod ORDER BY TIPOINV DESC, DESCRIPCIO


