---QUERY PARA REVISAR DATOS DE LIQUIDACION DE NOMINA
SELECT        CODBANCO, CODIGO, DIASPAG, FECFIN, FECHPAGO, FECING, FECINI, FECMOD, GRUPO, INTEGCONT, INTEGRBAN, NOMABIERTA, NRODCTO, NUMCHEQ, ORIGEN, PASSWORDIN, PASSWORDMO, STADSINCRO, 
                         TIPODCTO, CALEND, MECADORIG, MECANCELA, MEFALLO, MEFECHAT, MENOCERSAT, MESELLOCFD, MESELLOSAT, MEUUID, MEVERSION, MEXML, IDINTEGRA, INTPROVI, CONSECNE, CONSECNEAJ, DIASADICIONAL, 
                         INTEGNIIF, INTEGRACXP, INTLIBRA, INTPROVINIIF, MECANCELAANT, NOTA, NRODCTOR, TDConsNEAJ, TIPODCTONE, TRELACIO, UUIDANT, IDADJUNTOS
FROM            MTLIQNOM
WHERE        (NRODCTO = '2825') AND CODIGO='1019097420'