SELECT     A.NRODCTO,a.DCTOPRV, B.BODEGA, A.TIPODCTO, A.NIT, C.NOMBRE, A.FECHA, A.FECING, B.FECENT, A.AUTORIZA, B.PRODUCTO, B.NOMBRE , 
                      B.CANTIDAD, B.CANTORIG , B.CANVENTA , B.VALORUNIT, B.CANTORIG * B.VALORUNIT , b.nota AS NOTA_MV, A.NOTA
FROM         TRADE A INNER JOIN
                      MTPROCLI C ON A.NIT = C.NIT INNER JOIN
                      MVTRADE B ON A.NRODCTO = B.NRODCTO AND A.TIPODCTO = B.TIPODCTO
WHERE     (A.ORIGEN = 'COM') AND (A.TIPODCTO = 'OR')  AND (B.BODEGA IN ('02.TL.DECO'))
AND A.FECHA BETWEEN '01-01-2023' AND '31-12-2024' 
ORDER BY A.nrodcto DESC

