uSe SUPERTODO
SELECT * FROM TABLAINT WHERE CODIGO in ('424')
uSe COLNOTEXSA
SELECT * FROM TABLAINT WHERE CODIGO in ('424')

---CAMBIO DE CUENTA CODIGO DE INTEGRACION 315 ORIGINAL  22100101                                                    

UPDATE TABLAINT
SET NOMBRE='CE. CANCELACION ANTICIPO'
WHERE CODIGO='307' AND NOMBRE='CE. CANCELACION ANTICIPOS'

use SUPERTODO
SELECT * FROM TABLAINT WHERE CODIGO='307'
uSe COLNOTEXSA
SELECT * FROM TABLAINT WHERE CODIGO in ('301')
USE SUPERTODO
SELECT        TOP (200) CODINT, DESCRIPCIO, FACTURA, PORCENTAJE, STADSINCRO, SUMA, TIPOCPTO, ORIGEN, TIPOMTVO
FROM            TIPOCPTO
WHERE        (CODINT = '301')

select * from TABLAINT