SELECT        A.NRODCTO, A.NIT,E.PRODUCTO, E.NOMBRE,A.FECHA, A.FECHA1, A.BRUTO, A.DIR, A.CAJAREG, A.PASSWORDIN, B.NOMBRE, A.TIPODCTO, A.HORA, A.TIPOVTA, C.DESCRIPCIO, A.MEDIOPAG,  A.IVABRUTO, A.BRUTO + A.IVABRUTO AS VERIFICAVAL, 
                         D.MEDIOPAG , D.VALOR, D.COMENTARIO
FROM            Trade AS A INNER JOIN
                         MtProcli AS B ON A.NIT = B.NIT INNER JOIN
                         TipoVta AS C ON A.TIPOVTA = C.TIPOVTA INNER JOIN
                         MvCuadre AS D ON A.TIPODCTO = D.TIPODCTO AND A.NRODCTO = D.DCTO AND A.ORIGEN = D.ORIGEN INNER JOIN
                      MVTRADE AS E ON A.NRODCTO = E.NRODCTO AND A.TIPODCTO = E.TIPODCTO
WHERE        (A.FECHA > '01-01-2023') AND A.NRODCTO='60016' AND (A.TIPODCTO = 'F2') AND (A.ORIGEN = 'FAC')

SELECT*FROM Mvtrade WHERE NRODCTO='23900'

SELECT TOP(1)* FROM Mvtrade ORDER BY NRODCTO ASC

SELECT*FROM TRADE WHERE NRODCTO='60025'
SELECT* FROM TipoVta
SELECT * FROM MvCuadre WHERE DCTO='1'

select *  from MtProcli WHERE NIT='102328927'