SELECT        A.NRODCTO, A.TIPODCTO, A.FECHA, B.FECENT, A.CODCC, A.TIPOVTA, A.NIT, F.NOMBRE, A.CIUDADCLI, B.PRODUCTO, C.CODBARRAS, C.DESCRIPCIO, C.DESCRIP2,
                         D.NOMBRE , E.NOMBRE , B.CANTIDAD, B.NOTA , A.NOTA,A.FECHA1, A.TRANSPORTA, A.REMISION
FROM            TRADE AS A INNER JOIN
                         MVTRADE AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO INNER JOIN
                         MTMERCIA AS C ON B.PRODUCTO = C.CODIGO INNER JOIN
                         MT1CLAF AS D ON C.CLASIFICA1 = D.CODIGO INNER JOIN
                         MTGRUINV AS E ON C.CODGRUPO = E.CODGRUPO INNER JOIN
                         MTPROCLI AS F ON A.NIT = F.NIT
WHERE        (A.TIPODCTO = 'EP') AND (A.FECHA >= getdate() -90) and A.NRODCTO='14253'
ORDER BY  A.NRODCTO DESC, B.PRODUCTO



select * from MTMERCIA where CODBARRAS ='7703447716987'
select * from MTGRUINV where CODGRUPO ='PT073'
select * from MTGRUINV where NOMBRE like '%JUANA%'