SELECT ANO, CODCC, CODIGOCTA, CREDITO, CRMONEXT, DBMONEXT, DEBITO, NIT, PERIODO, STADSINCRO, NIIF
FROM SALDCONT
WHERE (CODIGOCTA IN ('36050101')) AND (ANO = 2015)
ORDER BY ANO, PERIODO


SELECT CODIGOCTA, SALDOANTDB, SALDOANTCR, SALDOANTDB-SALDOANTCR AS SALDO, DMES13, CMES13, DMES13-CMES13 AS EXPR1
FROM CUENTAS
WHERE (CODIGOCTA LIKE '39050102')
ORDER BY CODIGOCTA


SELECT NIT, CODIGOCTA, SALDOANTDB, SALDOANTCR, SALDOANTDB-SALDOANTCR AS SALDO, DMES13, CMES13, DMES13-CMES13 AS EXPR1
FROM TERCEROS
WHERE (CODIGOCTA LIKE '36050101')
ORDER BY CODIGOCTA

select * from SALDCONT
select * from CUENTAS
select CODIGOCTA,NIT,SALDOANTCX,SALDOANTDX,CXMES13,DXMES13 from TERCEROS
select * from TERCEROS
USE COLNIIF23
select CODIGOCTA,NIT,SALDOANTCX,SALDOANTDX,CXMES13,DXMES13 from TERCEROS