SELECT     MONTH(A.FECHA) , A.TIPODCTO, A.NRODCTO, A.DCTOPRV, A.FECHA, A.NIT, C.NOMBRE, B.PRODUCTO, D.DESCRIPCIO, B.CANTIDAD, A.NOTA, B.BODEGA
FROM         TRADE A INNER JOIN
                      MVTRADE B ON A.TIPOMVTO = B.TIPOMVTO AND A.NRODCTO = B.NRODCTO INNER JOIN
                      MTPROCLI C ON A.NIT = C.NIT INNER JOIN
                      MTMERCIA D ON B.PRODUCTO = D.CODIGO
WHERE     (A.ORIGEN = 'INV')  AND (A.FECHA >= getdate() -180)
ORDER BY A.FECHA DESC, A.NRODCTO desc
