use SUPERTODO
SELECT     A.FECHAMVTO, A.CODIGOCTA, A.CODCOMPROB, A.DCTO, A.CODCC, A.NIT, B.NOMBRE, A.BASE, A.CREDITO, A.DEBITO, A.DESCRIPCIO, 
                      A.DETALLE, c.DESCRIPCIO
FROM         MVTO A INNER JOIN
             NIT B ON A.NIT = B.NRONIT inner join cuentas c on a.codigocta = c.CODIGOCTA
WHERE     (A.FECHAMVTO >= '01/01/2023') AND (A.FECHAMVTO <= '31/12/2023')