SELECT 
	A.DIR, A.CAJAREG, A.PASSWORDIN, 
	A.TIPODCTO, A.NRODCTO, A.FECHA, A.FECHA1, 
	A.HORA, A.TIPOVTA, C.DESCRIPCIO, 
	A.MEDIOPAG, A.NIT, B.NOMBRE, A.BRUTO, 
	A.IVABRUTO, A.BRUTO + A.IVABRUTO , A.DESCUENTO
FROM  
	Trade AS A INNER JOIN
	MtProcli AS B ON A.NIT = B.NIT INNER JOIN
	TipoVta AS C ON A.TIPOVTA = C.TIPOVTA 
WHERE 
	(A.FECHA >= getdate()-180) 
	AND (A.CAJAREG IN ('001','002','003')) 
	AND (A.ORIGEN = 'FAC')
	AND A.TIPODCTO NOT IN ('PD','F3')
ORDER BY A.NRODCTO


SELECT 
	Mvtrade.NUMFACTNC, Mvtrade.REMIFACT, Mvtrade.TIPODCTO, 
	Mvtrade.NRODCTO, Mvtrade.FECHA, Mvtrade.ORIGEN, 
	Mvtrade.BODEGA, Mvtrade.PRODUCTO, Mvtrade.NOMBRE, 
	Mvtrade.CANTIDAD, Mvtrade.COSTO, Mvtrade.VALORUNIT, 
	MVTRADE.VLRVENTA, MVTRADE.DESCUENTO, MVTRADE.CANTIDAD*MVTRADE.VLRVENTA
FROM BESTPRICE.dbo.Mvtrade Mvtrade
WHERE TIPODCTO IN ('NC','B4')
AND MVTRADE.FECHA >= getdate()-180
ORDER BY TIPODCTO, NRODCTO


SELECT 
	MvCuadre.BANCO, MvCuadre.BANCODEST, MvCuadre.BANCOORI, 
	MvCuadre.BENEF, MvCuadre.CODBANCO, MvCuadre.CODCHQDEV, 
	MvCuadre.CODESTADO, MvCuadre.CODPLAZA, MvCuadre.CODTARJETA, 
	MvCuadre.COMENTARIO, MvCuadre.CTACHEQUE, MvCuadre.CTADEST, 
	MvCuadre.CTAORI, MvCuadre.DCTO, MvCuadre.FACTURA, MvCuadre.FECHACHQ, 
	MvCuadre.FECHAMVTO, MvCuadre.FECING, MvCuadre.FECMOD, MvCuadre.IDINTEGRA, 
	MvCuadre.IDMVCUADRE, MvCuadre.IdTeletransporte, MvCuadre.INTBANCO, 
	MvCuadre.MEDIOPAG, MvCuadre.NIT, MvCuadre.NROAPROBA, MvCuadre.NROCHEQUE, 
	MvCuadre.ORIGEN, MvCuadre.PAGODATAF, MvCuadre.PASSWORDIN, MvCuadre.PASSWORDMO, 
	MvCuadre.STADSINCRO, MvCuadre.TIPODCTO, MvCuadre.TIPODCTOFA, MvCuadre.VALOR
FROM 
	BESTPRICE.dbo.MvCuadre MvCuadre
WHERE 
	(MvCuadre.FECING >=getdate()-180)
ORDER BY FECING DESC

SELECT MtMedPag.MEDIOPAG, MtMedPag.CONCEPTO, MtMedPag.DESCRIPCIO, MtMedPag.EFECTIVO, MtMedPag.TIPOMTVO, MtMedPag.TIPOMTVOPAGO
FROM BESTPRICE.dbo.MtMedPag MtMedPag