--VALORUNIT YA
USE SUPERTODO
SELECT 
	A.FECHA, A.TIPODCTO, A.NRODCTO, B.CAJAREG, A.BODEGA, 
	A.CODCC, A.CODINT, A.PRODUCTO, A.NOMBRE, A.CANTIDAD, 
	A.TARIVA, A.IVA,
	CASE
		WHEN A.TIPODCTO IN ('B4','NC') THEN A.VALORUNIT*-1
		ELSE A.VALORUNIT
	END AS VALORUNIT,

	CASE
		WHEN A.TIPODCTO IN ('B4','NC') THEN A.VLRVENTA*-1
		ELSE A.VLRVENTA
	END AS VLRVENTA,
	
	CASE
		WHEN A.TIPODCTO IN ('B4','NC') THEN (A.VLRVENTA*-1) * A.CANTIDAD 
		ELSE A.VLRVENTA * A.CANTIDAD
	END AS VLRVENT_X_CANT,

	CASE
		WHEN A.TIPODCTO IN ('B4','NC') THEN (A.VALORUNIT*-1) * A.CANTIDAD
		ELSE A.VALORUNIT * A.CANTIDAD
	END AS VLRUNIT_X_CANT,

	CASE
		WHEN A.TIPODCTO IN ('B4','NC') THEN (A.VLRVENTA*-1) * A.CANTIDAD - (A.VALORUNIT*-1) * A.CANTIDAD
		ELSE A.VLRVENTA * A.CANTIDAD - A.VALORUNIT * A.CANTIDAD
	END AS VLRVENTCANT_VLRUNITCANT,

	A.COSTO, A.HCOSTO, B.NIT, C.NOMBRE , B.TIPOVTA, D.DESCRIPCIO, 
	E.TIPOINV, F.NOMBRE, E.CODLINEA, G.NOMBRE , E.CODSBLIN, H.NOMBRE, 
	E.CODBARRAS, A.DESCUENTO
FROM            
	Mvtrade AS A INNER JOIN
	Trade AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO AND A.ORIGEN = B.ORIGEN INNER JOIN
	MtProcli AS C ON B.NIT = C.NIT INNER JOIN
	TipoVta AS D ON B.TIPOVTA = D.TIPOVTA INNER JOIN
	MtMercia AS E ON A.PRODUCTO = E.CODIGO INNER JOIN
	TipoInv AS F ON E.TIPOINV = F.CODIGO INNER JOIN
	MtLinea AS G ON E.CODLINEA = G.CODLINEA INNER JOIN
	MtSblin AS H ON E.CODSBLIN = H.CODSBLIN
WHERE        
	(A.FECHA >= '01/01/2023')
	AND (A.ORIGEN = 'FAC')
	AND A.TIPODCTO IN ('F4','B4','NC')
ORDER BY  
	A.FECHA DESC, A.TIPODCTO, A.NRODCTO
