USE SUPERTODO
SELECT        
	A.DIR, A.CAJAREG, A.PASSWORDIN, A.TIPODCTO, 
	A.NRODCTO, A.FECHA, A.FECHA1, A.HORA, 
	A.TIPOVTA, C.DESCRIPCIO, A.MEDIOPAG, A.NIT, 
	B.NOMBRE, A.BRUTO, A.IVABRUTO, A.BRUTO + A.IVABRUTO, 
	A.DESCUENTO
                         
FROM
	Trade AS A INNER JOIN
	MtProcli AS B ON A.NIT = B.NIT INNER JOIN
	TipoVta AS C ON A.TIPOVTA = C.TIPOVTA 

WHERE        
	(A.FECHA >=GETDATE()-180)
	AND (A.CAJAREG LIKE ('%00%')) 
	AND (A.ORIGEN = 'FAC')
	AND A.TIPODCTO IN ('F2')
ORDER BY 
	A.NRODCTO