--EJERCICIO 2 DENIFITIVO-------------------------------------------------
USE SUPERTODO;
SELECT 
    MtSblin.NOMBRE AS CATEGORIA,
    MtMercia.DESCRIPCIO,
    MtMercia.CODIGO,
    MtMercia.CODBARRAS,
    ROUND(SUM(B.ICANTIDAD), 0) - ROUND(SUM(B.OCANTIDAD), 0) AS SALD_STD,
    Precios.LPMAYOR_4,
    Precios.LISPRECIO_5 
FROM 
    SUPERTODO.dbo.MtMercia
INNER JOIN
    SUPERTODO.dbo.MtSblin ON SUPERTODO.dbo.MtSblin.CODSBLIN = SUPERTODO.dbo.MtMercia.CODSBLIN
INNER JOIN
    SUPERTODO.dbo.SALDOINV B ON B.CODIGO = SUPERTODO.dbo.MtMercia.CODIGO
INNER JOIN
    (SELECT 
        CODPRODUC,
        MAX(CASE WHEN STD_MVP.CODPRECIO = '4' THEN STD_MVP.PRECIO ELSE NULL END) AS LPMAYOR_4, -- Precio con CODPRECIO 4
        MAX(CASE WHEN STD_MVP.CODPRECIO = '5' THEN STD_MVP.PRECIO ELSE NULL END) AS LISPRECIO_5 -- Precio con CODPRECIO 5
     FROM  
        SUPERTODO.dbo.MvPrecio STD_MVP 
     WHERE 
        CODPRECIO IN ('4', '5') 
     GROUP BY  
        CODPRODUC) AS Precios ON Precios.CODPRODUC = SUPERTODO.dbo.MtMercia.CODIGO
WHERE 
    NOT (B.ANO = 2025 AND B.PERIODO = 4)
GROUP BY 
    MtSblin.NOMBRE,
    MtMercia.CODIGO,
    MtMercia.CODBARRAS,
    MtMercia.DESCRIPCIO,
    Precios.LPMAYOR_4,
    Precios.LISPRECIO_5;
--- QUITANDO MAYOR A 0 STD ---------------------------------------
USE SUPERTODO;
SELECT 
    MtSblin.NOMBRE AS CATEGORIA,
    MtMercia.DESCRIPCIO,
    MtMercia.CODIGO,
    MtMercia.CODBARRAS,
    ROUND(SUM(B.ICANTIDAD), 0) - ROUND(SUM(B.OCANTIDAD), 0) AS SALD_STD,
    MAX(CASE WHEN STD_MVP.CODPRECIO = '4' THEN STD_MVP.PRECIO ELSE NULL END) AS LPMAYOR_4, -- Precio con CODPRECIO 4
    MAX(CASE WHEN STD_MVP.CODPRECIO = '5' THEN STD_MVP.PRECIO ELSE NULL END) AS LISPRECIO_5 -- Precio con CODPRECIO 5
FROM 
    SUPERTODO.dbo.MtMercia
INNER JOIN
    SUPERTODO.dbo.MtSblin ON SUPERTODO.dbo.MtSblin.CODSBLIN = SUPERTODO.dbo.MtMercia.CODSBLIN
INNER JOIN
    SUPERTODO.dbo.SALDOINV B ON B.CODIGO = SUPERTODO.dbo.MtMercia.CODIGO
LEFT JOIN
    SUPERTODO.dbo.MvPrecio STD_MVP ON STD_MVP.CODPRODUC = SUPERTODO.dbo.MtMercia.CODIGO AND STD_MVP.CODPRECIO IN ('4','5')
WHERE 
    NOT (B.ANO = 2025 AND B.PERIODO = 4)
GROUP BY 
    MtSblin.NOMBRE,
    MtMercia.CODIGO,
    MtMercia.CODBARRAS,
    MtMercia.DESCRIPCIO;
-------- SONIA CAMBIOS ----------------------------------- FINAL
USE SUPERTODO;
SELECT 
    MtSblin.NOMBRE AS CATEGORIA,
    MtMercia.DESCRIPCIO,
    MtMercia.CODIGO,
    MtMercia.CODBARRAS,
    ROUND(SUM(B.ICANTIDAD), 0) - ROUND(SUM(B.OCANTIDAD), 0) AS SALD_STD,
    Precios.LPMAYOR_4, -- Precio con CODPRECIO 4
    Precios.LISPRECIO_5 -- Precio con CODPRECIO 5
FROM 
    SUPERTODO.dbo.MtMercia
INNER JOIN
    SUPERTODO.dbo.MtSblin ON SUPERTODO.dbo.MtSblin.CODSBLIN = SUPERTODO.dbo.MtMercia.CODSBLIN
INNER JOIN
    SUPERTODO.dbo.SALDOINV B ON B.CODIGO = SUPERTODO.dbo.MtMercia.CODIGO
INNER JOIN
    (SELECT 
        CODPRODUC,
        MAX(CASE WHEN STD_MVP.CODPRECIO = '4' THEN STD_MVP.PRECIO ELSE NULL END) AS LPMAYOR_4, -- Precio con CODPRECIO 4
        MAX(CASE WHEN STD_MVP.CODPRECIO = '5' THEN STD_MVP.PRECIO ELSE NULL END) AS LISPRECIO_5 -- Precio con CODPRECIO 5
     FROM  
        SUPERTODO.dbo.MvPrecio STD_MVP 
     WHERE 
        CODPRECIO IN ('4', '5') 
     GROUP BY  
        CODPRODUC) AS Precios ON Precios.CODPRODUC = SUPERTODO.dbo.MtMercia.CODIGO
WHERE 
    NOT (B.ANO = 2025 AND B.PERIODO = 4)
GROUP BY 
    MtSblin.NOMBRE,
    MtMercia.CODIGO,
    MtMercia.CODBARRAS,
    MtMercia.DESCRIPCIO,
    Precios.LPMAYOR_4,
    Precios.LISPRECIO_5;
-- CODIGO CREADO -----------------------------------------------
SELECT CODPRODUC,
    MAX(CASE WHEN STD_MVP.CODPRECIO = '4' THEN STD_MVP.PRECIO ELSE NULL END) AS LPMAYOR_4, -- Precio con CODPRECIO 4
    MAX(CASE WHEN STD_MVP.CODPRECIO = '5' THEN STD_MVP.PRECIO ELSE NULL END) AS LISPRECIO_5 -- Precio con CODPRECIO 5
	FROM  SUPERTODO.dbo.MvPrecio STD_MVP WHERE CODPRODUC='A-00018' AND CODPRECIO IN ('4','5') GROUP BY  CODPRODUC
-- EDITAR CATEGORIAS -------------------------------------------
USE SUPERTODO
select * from MtSblin;
select * from MtMercia WHERE CODIGO='11111111';
UPDATE MtMercia SET CODSBLIN='001' WHERE CODIGO='1111111111';
-- CODIGO DEFINITIVO -------------------------------------------
USE SUPERTODO;
SELECT 
	A.CODIGO,
	ROUND(SUM(A.ICANTIDAD), 0) AS ENTRADAS_STD,
	ROUND(SUM(A.OCANTIDAD), 0) AS SALIDAS_STD,
	ROUND(SUM(A.ICANTIDAD - A.OCANTIDAD), 0) AS SALDO_STD
FROM 
	SUPERTODO.dbo.SALDOINV A
WHERE 
	NOT (ANO = 2025 AND PERIODO = 4) AND A.CODIGO='A-00018'
GROUP�BY�
	A.CODIGO;
-- APARTE CODIGO -----------------------------------------------
USE BESTPRICE;
SELECT 
	A.CODIGO,
	ROUND(SUM(A.ICANTIDAD), 0) AS ENTRADAS_BRP,
	ROUND(SUM(A.OCANTIDAD), 0) AS SALIDAS_BRP,
    ROUND(SUM(A.ICANTIDAD - A.OCANTIDAD), 0) AS SALDO_BRP
FROM 
	BESTPRICE.dbo.SALDOINV A
WHERE 
	NOT (ANO = 2025 AND PERIODO = 4)
GROUP�BY�
	A.CODIGO;
--- QUITANDO MAYOR A 0 BRP -------------------------------------
USE BESTPRICE;
SELECT 
    CODIGO,
    SALDO_BRP
FROM (
    SELECT 
        A.CODIGO,
        ROUND(SUM(A.ICANTIDAD - A.OCANTIDAD), 0) AS SALDO_BRP
    FROM 
        BESTPRICE.dbo.SALDOINV A
    WHERE 
        NOT (ANO = 2025 AND PERIODO = 4)
    GROUP BY 
        A.CODIGO
) AS B
WHERE 
    B.SALDO_BRP > 0;
-- EJERCICIO 1 DEFINITIVO ---------------------------------------
SELECT 
    A.CODIGO,
    ROUND(SUM(A.ICANTIDAD), 0) AS ENTRADAS_STD,
    ROUND(SUM(A.OCANTIDAD), 0) AS SALIDAS_STD,
    ROUND(SUM(A.ICANTIDAD - A.OCANTIDAD), 0) AS SALDO_STD,
    B.ENTRADAS_BRP,
    B.SALIDAS_BRP,
    B.SALDO_BRP
FROM 
    SUPERTODO.dbo.SALDOINV A
LEFT JOIN (
    SELECT CODIGO, 
           ROUND(SUM(ICANTIDAD), 0) AS ENTRADAS_BRP, 
           ROUND(SUM(OCANTIDAD), 0) AS SALIDAS_BRP,
	   ROUND(SUM(ICANTIDAD - OCANTIDAD), 0) AS SALDO_BRP
    FROM BESTPRICE.dbo.SALDOINV
	WHERE NOT (ANO = 2025 AND PERIODO = 4)
    GROUP BY CODIGO
    ) B ON A.CODIGO = B.CODIGO
WHERE 
	NOT (A.ANO = 2025 AND A.PERIODO = 4)
GROUP BY A.CODIGO, B.ENTRADAS_BRP, B.SALIDAS_BRP,B.SALDO_BRP ORDER BY�A.CODIGO�ASC;
--UTILIZANDO CODIGO ANTERIOR X MES -----------------------------
USE SUPERTODO;
SELECT 
	A.ANO,
	A.Periodo,
	round(sum(ICANTIDAD),0) AS ENTRADAS,
	round(sum(OCANTIDAD),0) AS SALIDAS, 
	round(sum(ICANTIDAD),0) - round(sum(OCANTIDAD),0) AS SALDO_STD
FROM 
	SALDOINV A
WHERE 
	 NOT (A.ANO = 2025 AND A.PERIODO = 4) AND A.CODIGO='A-00018'
GROUP BY A.ANO,A.PERIODO
--EXPLICACION CODIGO -------------------------------------------
SELECT 
	ANO,PERIODO,CODIGO,SUM(OCANTIDAD) AS TOTAL,SUM(ICANTIDAD) AS TOTAL
FROM 
	SALDOINV 
WHERE 
	CODIGO='A-00001' 
GROUP BY CODIGO,ANO,PERIODO;
--PREUBA NO CUMPLE CON LA INFO EN OFIMATICA V1------------------
USE SUPERTODO;
SELECT 
    MtSblin.NOMBRE AS CATEGORIA,
    MtMercia.CODIGO,
    MtMercia.CODBARRAS,
    MtMercia.DESCRIPCIO,
	round(sum(SUPERTODO_SALDO.ICANTIDAD),0) - round(sum(SUPERTODO_SALDO.OCANTIDAD),0) AS SALDO_STD,
	round(sum(BESTPRICE_SALDO.ICANTIDAD),0) - round(sum(BESTPRICE_SALDO.OCANTIDAD),0) AS SALDO_BRP,
    (round(sum(SUPERTODO_SALDO.ICANTIDAD),0) - round(sum(SUPERTODO_SALDO.OCANTIDAD),0)+(round(sum(BESTPRICE_SALDO.ICANTIDAD),0) - round(sum(BESTPRICE_SALDO.OCANTIDAD),0))) AS TOTAL_SALDO
FROM 
    SUPERTODO.dbo.MtMercia
INNER JOIN
    SUPERTODO.dbo.MtSblin ON SUPERTODO.dbo.MtSblin.CODSBLIN = SUPERTODO.dbo.MtMercia.CODSBLIN
INNER JOIN
    SUPERTODO.dbo.SALDOINV SUPERTODO_SALDO ON SUPERTODO_SALDO.CODIGO = SUPERTODO.dbo.MtMercia.CODIGO
INNER JOIN
    BESTPRICE.dbo.SALDOINV BESTPRICE_SALDO ON BESTPRICE_SALDO.CODIGO = SUPERTODO.dbo.MtMercia.CODIGO
WHERE SUPERTODO_SALDO.ANO='2025' AND BESTPRICE_SALDO.ANO='2025' AND SUPERTODO_SALDO.PERIODO='1' AND BESTPRICE_SALDO.PERIODO='1'
GROUP BY 
    MtSblin.NOMBRE,
    MtMercia.CODIGO,
    MtMercia.CODBARRAS,
    MtMercia.DESCRIPCIO;