SELECT 
    A.PRODUCTO,
    B.NIT,
    MP.NOMBRE,
    MAX(B.FECHA) AS UltimaFecha,
    (
        SELECT TOP 1 C.HCOSTO
        FROM COSTOINV AS C
        WHERE C.CODIGO = A.PRODUCTO
        ORDER BY C.ANO DESC, C.PERIODO DESC
    ) AS UltimoCosto
FROM Mvtrade AS A
INNER JOIN Trade AS B 
    ON A.TIPODCTO = B.TIPODCTO 
    AND A.NRODCTO = B.NRODCTO 
    AND A.ORIGEN = B.ORIGEN
INNER JOIN MtProcli AS MP 
    ON MP.NIT = B.NIT
WHERE
    A.ORIGEN = 'COM'
    AND A.TIPODCTO IN ('F1', 'F4')
GROUP BY 
    A.PRODUCTO, 
    B.NIT, 
    MP.NOMBRE
ORDER BY 
    A.PRODUCTO ASC;
