USE SUPERTODO
SELECT VALORUNIT, PRODUCTO, FECHA
FROM (
    SELECT 
        A.VALORUNIT,
        A.PRODUCTO,
        A.FECHA,
        ROW_NUMBER() OVER (PARTITION BY A.PRODUCTO ORDER BY A.FECHA DESC) AS rn
    FROM Mvtrade A
    WHERE    
        A.FECHA >= '2023-01-01'
        AND A.ORIGEN = 'COM'
        AND A.TIPODCTO IN ('F1','F4')
	) t
WHERE rn = 1
ORDER BY FECHA DESC;