SELECT        
A.ORIGEN, A.TIPODCTO, A.NRODCTO, A.FECHA, A.NIT, 
A.BRUTO, 
	CASE 
		WHEN A.TIPODCTO = ('B4') THEN A.BRUTO*-1 
		ELSE A.BRUTO
		END AS BRUTO_PRUEBA,
B.PRODUCTO, C.CODBARRAS, c.DESCRIPCIO, b.CANTIDAD, 
	CASE 
		WHEN A.TIPODCTO = ('B4') THEN B.VALORUNIT*-1
		ELSE B.VALORUNIT
		END AS VALORUNIT
FROM            
	Trade AS A INNER JOIN
	Mvtrade AS b ON A.ORIGEN = b.ORIGEN AND A.TIPODCTO = b.TIPODCTO AND A.NRODCTO = b.NRODCTO INNER JOIN
	MtMercia AS c ON B.PRODUCTO = c.CODIGO
WHERE        
	(A.ORIGEN = 'FAC') AND (A.NIT = '132506911') AND (A.FECHA >= '01/01/2025')
ORDER BY 
	A.FECHA DESC, A.TIPODCTO, A.NRODCTO DESC