/*Forma 1 excluye 4 campos no aceptados por SQL*/
CREATE TRIGGER Tr_Traslada_Ref_STD_LPZ
ON SUPERTODO.dbo.MtMercia
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO BESTPRICE.dbo.MtMercia (
    ANO, ARANCEL, AREA, CLASIFICA1, CLASIFICA2, CLAVEPRSER, CODAGRUPA, CODBARRAS, CODDETRA, CODGRUPO, CODIGO, CODIGOINV, CODIGOPLU, CODIGOUEN, CODLINEA, CODRETE, CODSBLIN, 
    CODSUMIN, CODTARIVA, CODUBICA, CONVERSION, COSTO_ING, COSTO_UF, COSTO_UFR, COSTO_USD, COSTO_USDR, COSTOCOMPA, CTAAII, CTACOM, CTACOMDEV, CTACOMDIVA, CTACOMDRTE, CTACOMIVA, CTACOMRTE, 
    CTAVTA, CTAVTADEV, CTAVTADIVA, CTAVTADRTE, CTAVTAIVA, CTAVTARTE, CTDRIRCCOM, CTDRIRCVTA, CTDRIRSCOM, CTRIRCCOM, CTRIRCVTA, CTRIRSCOM, DESCRIP2, DESCRIPCIO, DESCUENTO1, 
    DESCUENTO2, DESPACHO, DETALLE, DIASREP, DIASVENCI, DTMFRCP, DTMFRSFPEP, DTMFRSPE, DTMLTCP, DTMLTPEP, ESBONO, ESCOMER, ESIMPOR, ESPRODUCTO, EXCBASIMP, FACTOR, FACTORR, FECHA_ING, 
    FECING, FECMOD, FORMATCANT, FORMATPREC, GRADOALCO, HABILITADO, HANCM, IDADJUNTOS, IMDCOLOR, IMDDCDSC, IMDDLDSC, IMDESTILO, IMDFFPF, IMDFRAGAN, IMDMANIPU1, IMDMANIPU2, 
    IMDMANIPU3, IMDMANIPU4, IMDMANIPU5, IMDMARCA, IMDNF, IMDNFABRI, IMDPA, IMDRS, IMDSABOR, IMDTALLA, IMDTT, IMDUC, IMDUCIO, IMDUD, IMDVALORVO, IMDVOLUMEN, IMPREG, INDPEDI, INDPRESU, INSUMO, 
    INVSEGUR, IPCMVALOR, IPCMVALORCIG, IPCMVALORRES, IPCMVALORSALU, IPCONSUMO, IVA, IVADIFER, LINTIPCOD, LOTEMIN, MANAIU, MATPRIMA, MAXIMO, MAYORFLE, MAYORIVA, MAYVALCOSCOM, MEAALTOUM, 
    MEAALTOVR, MEAANCHOUM, MEAANCHOVR, MEAAPROFVR, MEANMUAUM, MEANMUAVM, MEANTUM, MEANTVR, MEANUTUM, MEANUTUVR, MEAPBUM, MEAPBVR, MEAPNUN, MEAPROFUUM, MEAPSVR, MEATARAUM, 
    MEATARAVR, MEATEMPAM, MEATEMUM, MEATEMVRMA, MEATEMVRMI, MINIMO, NCTAAII, NCTACOM, NCTACOMDEV, NCTACOMDIV, NCTACOMDRT, NCTACOMIVA, NCTACOMRTE, NCTAVTA, NCTAVTADEV, NCTAVTADIV, 
    NCTAVTADRT, NCTAVTAIVA, NCTAVTARTE, NCTDRIRCCO, NCTDRIRCVT, NCTDRIRSCO, NCTRIRCCOM, NCTRIRCVTA, NCTRIRSCOM, PASSWORDIN, PASSWORDMO, PIACIFCDPR, PIACIFIDAD, PIAIACCDPR, PIAIACIDAD, 
    PIAICITEM, PIANAPCDPR, PIANAPIDAD, PMP, PORARANC, PORAYS, PORIPCMRES, PORIVADIF, PREDIAL, PRODTER, PRONOSTICO, PRUEBA, PVALLEJO, QTYCCEUM, QTYCCEVR, QTYNPUM, QTYNPVR, QTYNUCUIUM, 
    QTYNUCUIVR, REFERPROV, REQCALIDAD, REQSERIE, STADSINCRO, T_ALTO, T_ALTOUE, T_ANCHO, T_ANCHOUE, T_COSTEO, T_EMPAQUE, T_ENTREGA, T_FONDO, T_FONDOUE, T_PESOUE, TAMLOTE, TAXVLORIVA, 
    TIEMPROD, TIEMSEGU, TIPEMPAQUE, TIPOBEBIDA, TIPOINGRES, TIPOINV, TIPOTALLA, TOTALLOTE, UBICACION, UNDCONVERS, UNDEMPAQUE, UNDTIEMPOS, UNDTIESEGU, UNDTPREP, UNIDADMED, VALIPCMCIG, 
    VOLUMEN
    )
    SELECT 
    i.ANO, i.ARANCEL, i.AREA, i.CLASIFICA1, i.CLASIFICA2, i.CLAVEPRSER, i.CODAGRUPA, i.CODBARRAS, i.CODDETRA, i.CODGRUPO, i.CODIGO, i.CODIGOINV, i.CODIGOPLU, i.CODIGOUEN, i.CODLINEA, i.CODRETE, i.CODSBLIN,
    i.CODSUMIN, i.CODTARIVA, i.CODUBICA, i.CONVERSION, i.COSTO_ING, i.COSTO_UF, i.COSTO_UFR, i.COSTO_USD, i.COSTO_USDR, i.COSTOCOMPA, i.CTAAII, i.CTACOM, i.CTACOMDEV, i.CTACOMDIVA, i.CTACOMDRTE, i.CTACOMIVA, i.CTACOMRTE,
    i.CTAVTA, i.CTAVTADEV, i.CTAVTADIVA, i.CTAVTADRTE, i.CTAVTAIVA, i.CTAVTARTE, i.CTDRIRCCOM, i.CTDRIRCVTA, i.CTDRIRSCOM, i.CTRIRCCOM, i.CTRIRCVTA, i.CTRIRSCOM,i.DESCRIP2, i.DESCRIPCIO, i.DESCUENTO1,
    i.DESCUENTO2, i.DESPACHO, i.DETALLE, i.DIASREP, i.DIASVENCI, i.DTMFRCP, i.DTMFRSFPEP, i.DTMFRSPE, i.DTMLTCP, i.DTMLTPEP, i.ESBONO, i.ESCOMER, i.ESIMPOR, i.ESPRODUCTO, i.EXCBASIMP, i.FACTOR, i.FACTORR, i.FECHA_ING,
    i.FECING, i.FECMOD, i.FORMATCANT, i.FORMATPREC, i.GRADOALCO, i.HABILITADO, i.HANCM, i.IDADJUNTOS, i.IMDCOLOR, i.IMDDCDSC, i.IMDDLDSC, i.IMDESTILO, i.IMDFFPF, i.IMDFRAGAN, i.IMDMANIPU1, i.IMDMANIPU2,
    i.IMDMANIPU3, i.IMDMANIPU4, i.IMDMANIPU5, i.IMDMARCA, i.IMDNF, i.IMDNFABRI, i.IMDPA, i.IMDRS, i.IMDSABOR, i.IMDTALLA, i.IMDTT, i.IMDUC, i.IMDUCIO, i.IMDUD, i.IMDVALORVO, i.IMDVOLUMEN, i.IMPREG, i.INDPEDI, i.INDPRESU, i.INSUMO,
    i.INVSEGUR, i.IPCMVALOR, i.IPCMVALORCIG, i.IPCMVALORRES, i.IPCMVALORSALU, i.IPCONSUMO, i.IVA, i.IVADIFER, i.LINTIPCOD, i.LOTEMIN, i.MANAIU, i.MATPRIMA, i.MAXIMO, i.MAYORFLE, i.MAYORIVA, i.MAYVALCOSCOM, i.MEAALTOUM,
    i.MEAALTOVR, i.MEAANCHOUM, i.MEAANCHOVR, i.MEAAPROFVR, i.MEANMUAUM, i.MEANMUAVM, i.MEANTUM, i.MEANTVR, i.MEANUTUM, i.MEANUTUVR, i.MEAPBUM, i.MEAPBVR, i.MEAPNUN, i.MEAPROFUUM, i.MEAPSVR, i.MEATARAUM,
    i.MEATARAVR, i.MEATEMPAM, i.MEATEMUM, i.MEATEMVRMA, i.MEATEMVRMI, i.MINIMO, i.NCTAAII, i.NCTACOM, i.NCTACOMDEV, i.NCTACOMDIV, i.NCTACOMDRT, i.NCTACOMIVA, i.NCTACOMRTE, i.NCTAVTA, i.NCTAVTADEV, i.NCTAVTADIV,
    i.NCTAVTADRT, i.NCTAVTAIVA, i.NCTAVTARTE, i.NCTDRIRCCO, i.NCTDRIRCVT, i.NCTDRIRSCO, i.NCTRIRCCOM, i.NCTRIRCVTA, i.NCTRIRSCOM,i.PASSWORDIN, i.PASSWORDMO, i.PIACIFCDPR, i.PIACIFIDAD, i.PIAIACCDPR, i.PIAIACIDAD,
    i.PIAICITEM, i.PIANAPCDPR, i.PIANAPIDAD, i.PMP, i.PORARANC, i.PORAYS, i.PORIPCMRES, i.PORIVADIF, i.PREDIAL, i.PRODTER, i.PRONOSTICO, i.PRUEBA, i.PVALLEJO, i.QTYCCEUM, i.QTYCCEVR, i.QTYNPUM, i.QTYNPVR, i.QTYNUCUIUM,
    i.QTYNUCUIVR, i.REFERPROV, i.REQCALIDAD, i.REQSERIE, i.STADSINCRO, i.T_ALTO, i.T_ALTOUE, i.T_ANCHO, i.T_ANCHOUE, i.T_COSTEO, i.T_EMPAQUE, i.T_ENTREGA, i.T_FONDO, i.T_FONDOUE, i.T_PESOUE, i.TAMLOTE, i.TAXVLORIVA,
    i.TIEMPROD, i.TIEMSEGU, i.TIPEMPAQUE, i.TIPOBEBIDA, i.TIPOINGRES, i.TIPOINV, i.TIPOTALLA, i.TOTALLOTE, i.UBICACION, i.UNDCONVERS, i.UNDEMPAQUE, i.UNDTIEMPOS, i.UNDTIESEGU, i.UNDTPREP, i.UNIDADMED, i.VALIPCMCIG,
    i.VOLUMEN
    
FROM inserted i;
END;

/*FORMA 2 Realiza con Inner JOIN no recomendada porque  puede generar duplicidad
CREATE TRIGGER Tr_Traslada_Ref_STD_LPZ
ON SupertodoBackup.dbo.MtMercia
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;
    
    INSERT INTO Bestprice_Backup.dbo.MtMercia (
    ANO, ARANCEL, AREA, CLASIFICA1, CLASIFICA2, CLAVEPRSER, CLIENTE_PR, CODAGRUPA, CODBARRAS, CODDETRA, CODGRUPO, CODIGO, CODIGOINV, CODIGOPLU, CODIGOUEN, CODLINEA, CODRETE, CODSBLIN, 
    CODSUMIN, CODTARIVA, CODUBICA, CONVERSION, COSTO_ING, COSTO_UF, COSTO_UFR, COSTO_USD, COSTO_USDR, COSTOCOMPA, CTAAII, CTACOM, CTACOMDEV, CTACOMDIVA, CTACOMDRTE, CTACOMIVA, CTACOMRTE, 
    CTAVTA, CTAVTADEV, CTAVTADIVA, CTAVTADRTE, CTAVTAIVA, CTAVTARTE, CTDRIRCCOM, CTDRIRCVTA, CTDRIRSCOM, CTRIRCCOM, CTRIRCVTA, CTRIRSCOM, DESC_LAR, DESCRIP2, DESCRIPCIO, DESCUENTO1, 
    DESCUENTO2, DESPACHO, DETALLE, DIASREP, DIASVENCI, DTMFRCP, DTMFRSFPEP, DTMFRSPE, DTMLTCP, DTMLTPEP, ESBONO, ESCOMER, ESIMPOR, ESPRODUCTO, EXCBASIMP, FACTOR, FACTORR, FECHA_ING, 
    FECING, FECMOD, FORMATCANT, FORMATPREC, FOTO, FOTOPRODUC, GRADOALCO, HABILITADO, HANCM, IDADJUNTOS, IMDCOLOR, IMDDCDSC, IMDDLDSC, IMDESTILO, IMDFFPF, IMDFRAGAN, IMDMANIPU1, IMDMANIPU2, 
    IMDMANIPU3, IMDMANIPU4, IMDMANIPU5, IMDMARCA, IMDNF, IMDNFABRI, IMDPA, IMDRS, IMDSABOR, IMDTALLA, IMDTT, IMDUC, IMDUCIO, IMDUD, IMDVALORVO, IMDVOLUMEN, IMPREG, INDPEDI, INDPRESU, INSUMO, 
    INVSEGUR, IPCMVALOR, IPCMVALORCIG, IPCMVALORRES, IPCMVALORSALU, IPCONSUMO, IVA, IVADIFER, LINTIPCOD, LOTEMIN, MANAIU, MATPRIMA, MAXIMO, MAYORFLE, MAYORIVA, MAYVALCOSCOM, MEAALTOUM, 
    MEAALTOVR, MEAANCHOUM, MEAANCHOVR, MEAAPROFVR, MEANMUAUM, MEANMUAVM, MEANTUM, MEANTVR, MEANUTUM, MEANUTUVR, MEAPBUM, MEAPBVR, MEAPNUN, MEAPROFUUM, MEAPSVR, MEATARAUM, 
    MEATARAVR, MEATEMPAM, MEATEMUM, MEATEMVRMA, MEATEMVRMI, MINIMO, NCTAAII, NCTACOM, NCTACOMDEV, NCTACOMDIV, NCTACOMDRT, NCTACOMIVA, NCTACOMRTE, NCTAVTA, NCTAVTADEV, NCTAVTADIV, 
    NCTAVTADRT, NCTAVTAIVA, NCTAVTARTE, NCTDRIRCCO, NCTDRIRCVT, NCTDRIRSCO, NCTRIRCCOM, NCTRIRCVTA, NCTRIRSCOM, NOTA, PASSWORDIN, PASSWORDMO, PIACIFCDPR, PIACIFIDAD, PIAIACCDPR, PIAIACIDAD, 
    PIAICITEM, PIANAPCDPR, PIANAPIDAD, PMP, PORARANC, PORAYS, PORIPCMRES, PORIVADIF, PREDIAL, PRODTER, PRONOSTICO, PRUEBA, PVALLEJO, QTYCCEUM, QTYCCEVR, QTYNPUM, QTYNPVR, QTYNUCUIUM, 
    QTYNUCUIVR, REFERPROV, REQCALIDAD, REQSERIE, STADSINCRO, T_ALTO, T_ALTOUE, T_ANCHO, T_ANCHOUE, T_COSTEO, T_EMPAQUE, T_ENTREGA, T_FONDO, T_FONDOUE, T_PESOUE, TAMLOTE, TAXVLORIVA, 
    TIEMPROD, TIEMSEGU, TIPEMPAQUE, TIPOBEBIDA, TIPOINGRES, TIPOINV, TIPOTALLA, TOTALLOTE, UBICACION, UNDCONVERS, UNDEMPAQUE, UNDTIEMPOS, UNDTIESEGU, UNDTPREP, UNIDADMED, VALIPCMCIG, 
    VOLUMEN
    )
    SELECT 
    t.ANO, t.ARANCEL,t.AREA,t.CLASIFICA1,t.CLASIFICA2,t.CLAVEPRSER,t.CLIENTE_PR,t.CODAGRUPA,t.CODBARRAS,t.CODDETRA,t.CODGRUPO,t.CODIGO,t.CODIGOINV,t.CODIGOPLU,t.CODIGOUEN,t.CODLINEA,t.CODRETE,t.CODSBLIN,
	t.CODSUMIN,t.CODTARIVA,t.CODUBICA,t.CONVERSION,t.COSTO_ING,t.COSTO_UF,t.COSTO_UFR,t.COSTO_USD,t.COSTO_USDR,t.COSTOCOMPA,t.CTAAII,t.CTACOM,t.CTACOMDEV,t.CTACOMDIVA,t.CTACOMDRTE,t.CTACOMIVA,t.CTACOMRTE,
    t.CTAVTA,t.CTAVTADEV,t.CTAVTADIVA,t.CTAVTADRTE,t.CTAVTAIVA,t.CTAVTARTE,t.CTDRIRCCOM,t.CTDRIRCVTA,t.CTDRIRSCOM,t.CTRIRCCOM,t.CTRIRCVTA,t.CTRIRSCOM,t.DESC_LAR,t.DESCRIP2,t.DESCRIPCIO,t.DESCUENTO1,
    t.DESCUENTO2,t.DESPACHO,t.DETALLE,t.DIASREP,t.DIASVENCI,t.DTMFRCP,t.DTMFRSFPEP,t.DTMFRSPE,t.DTMLTCP,t.DTMLTPEP,t.ESBONO,t.ESCOMER,t.ESIMPOR,t.ESPRODUCTO,t.EXCBASIMP,t.FACTOR,t.FACTORR,t.FECHA_ING,
    t.FECING,t.FECMOD,t.FORMATCANT,t.FORMATPREC,t.FOTO,t.FOTOPRODUC,t.GRADOALCO,t.HABILITADO,t.HANCM,t.IDADJUNTOS,t.IMDCOLOR,t.IMDDCDSC,t.IMDDLDSC,t.IMDESTILO,t.IMDFFPF,t.IMDFRAGAN,t.IMDMANIPU1,t.IMDMANIPU2,
    t.IMDMANIPU3,t.IMDMANIPU4,t.IMDMANIPU5,t.IMDMARCA,t.IMDNF,t.IMDNFABRI,t.IMDPA,t.IMDRS,t.IMDSABOR,t.IMDTALLA,t.IMDTT,t.IMDUC,t.IMDUCIO,t.IMDUD,t.IMDVALORVO,t.IMDVOLUMEN,t.IMPREG,t.INDPEDI,t.INDPRESU,
    t.INSUMO,t.INVSEGUR,t.IPCMVALOR,t.IPCMVALORCIG,t.IPCMVALORRES,t.IPCMVALORSALU,t.IPCONSUMO,t.IVA,t.IVADIFER,t.LINTIPCOD,t.LOTEMIN,t.MANAIU,t.MATPRIMA,t.MAXIMO,t.MAYORFLE,t.MAYORIVA,t.MAYVALCOSCOM,t.MEAALTOUM,
    t.MEAALTOVR,t.MEAANCHOUM,t.MEAANCHOVR,t.MEAAPROFVR,t.MEANMUAUM,t.MEANMUAVM,t.MEANTUM,t.MEANTVR,t.MEANUTUM,t.MEANUTUVR,t.MEAPBUM,t.MEAPBVR,t.MEAPNUN,t.MEAPROFUUM,t.MEAPSVR,t.MEATARAUM,
    t.MEATARAVR,t.MEATEMPAM,t.MEATEMUM,t.MEATEMVRMA,t.MEATEMVRMI,t.MINIMO,t.NCTAAII,t.NCTACOM,t.NCTACOMDEV,t.NCTACOMDIV,t.NCTACOMDRT,t.NCTACOMIVA,t.NCTACOMRTE,t.NCTAVTA,t.NCTAVTADEV,t.NCTAVTADIV,
    t.NCTAVTADRT,t.NCTAVTAIVA,t.NCTAVTARTE,t.NCTDRIRCCO,t.NCTDRIRCVT,t.NCTDRIRSCO,t.NCTRIRCCOM,t.NCTRIRCVTA,t.NCTRIRSCOM,t.NOTA,t.PASSWORDIN,t.PASSWORDMO,t.PIACIFCDPR,t.PIACIFIDAD,t.PIAIACCDPR,t.PIAIACIDAD,
    t.PIAICITEM,t.PIANAPCDPR,t.PIANAPIDAD,t.PMP,t.PORARANC,t.PORAYS,t.PORIPCMRES,t.PORIVADIF,t.PREDIAL,t.PRODTER,t.PRONOSTICO,t.PRUEBA,t.PVALLEJO,t.QTYCCEUM,t.QTYCCEVR,t.QTYNPUM,t.QTYNPVR,t.QTYNUCUIUM,
    t.QTYNUCUIVR,t.REFERPROV,t.REQCALIDAD,t.REQSERIE,t.STADSINCRO,t.T_ALTO,t.T_ALTOUE,t.T_ANCHO,t.T_ANCHOUE,t.T_COSTEO,t.T_EMPAQUE,t.T_ENTREGA,t.T_FONDO,t.T_FONDOUE,t.T_PESOUE,t.TAMLOTE,t.TAXVLORIVA,t.TIEMPROD,
    t.TIEMSEGU,t.TIPEMPAQUE,t.TIPOBEBIDA,t.TIPOINGRES,t.TIPOINV,t.TIPOTALLA,t.TOTALLOTE,t.UBICACION,t.UNDCONVERS,t.UNDEMPAQUE,t.UNDTIEMPOS,t.UNDTIESEGU,t.UNDTPREP,t.UNIDADMED,t.VALIPCMCIG,t.VOLUMEN
    FROM SupertodoBackup.dbo.MtMercia t
    INNER JOIN inserted i ON t.CODIGO = i.CODIGO;
END;
*/