/*Seleccionar Menu Administrac.Usuarios Menu 1-2, Cuando se Marca Sucede lo siguiente:
(CONSECUT,MTMEDPAG,ALERTA)="SI" TENDRA PERMISO 
(MTCAJAREG)="NO" TENDRA PERMISO 
(CENTCOS,VBODEGAS)=NO AFECTA EN NADA
*/

/*ENTRE MAS REGISTROS ALLA EN MVCLASIFICACION SIGNIFICA QUE MAS ACCESO TENDRA*/
USE CONTROL_OFIMAEnterprise
select CODCLASIFICA,CODUSUARIO from MVCLASIFICACION WHERE CODCLASIFICA='MTCAJAREG' GROUP BY CODUSUARIO,CODCLASIFICA ORDER BY CODUSUARIO

select MTc.CODIGO,MTc.NOMBRE,MTc.* from MVCLASIFICACION M INNER JOIN
SUPERTODO.dbo.MtCajaReg MTc ON M.VALORCLASIFICA=MTc.CODIGO AND MTc.CODIGO <> '0' 
WHERE CODUSUARIO='YESICAS'

select * from SUPERTODO.dbo.MtCajaReg

select * from MVCLASIFICACION WHERE CODUSUARIO='JOSEA' AND CODCLASIFICA='MTCAJAREG'

SELECT
	CODUSUARIO,
--LPZ
   1- MAX(CASE WHEN VALORCLASIFICA = 'B01' THEN 1 ELSE 0 END) AS B01,
   1- MAX(CASE WHEN VALORCLASIFICA = 'B02' THEN 1 ELSE 0 END) AS B02,
   1- MAX(CASE WHEN VALORCLASIFICA = 'B04' THEN 1 ELSE 0 END) AS B04,
   CODEMPRESA
FROM MVCLASIFICACION
GROUP BY CODUSUARIO,CODEMPRESA


USE CONTROL_OFIMAEnterprise
select CODCLASIFICA,CODUSUARIO,CODEMPRESA from MVCLASIFICACION WHERE CODCLASIFICA='MTCAJAREG' AND CODEMPRESA IN ('SUPERTODO','BESTPRICE') ORDER BY CODUSUARIO

--DEFINITIVO TRAE TODOS LOS CAJEROS Y SUS PERMISOS RESPECTIVOS
SELECT *
FROM MVCLASIFICACION
WHERE CODCLASIFICA IN ('MTCAJAREG')
  AND CODEMPRESA IN ('SUPERTODO','BESTPRICE')
  AND CODUSUARIO IN (
        SELECT CODUSUARIO
        FROM MVCLASIFICACION
        WHERE CODCLASIFICA = 'MTCAJAREG'
          AND CODEMPRESA IN ('SUPERTODO','BESTPRICE')
        GROUP BY CODUSUARIO
        HAVING COUNT(CODUSUARIO) <= 2
  )
ORDER BY CODUSUARIO;
--2 DEFINITIVO TRAE LOS DIFERENTES MEDIOS DE PAGO ASIGNADO
SELECT
    CODUSUARIO,--MTC.NOMBRE,
   1-MAX(CASE WHEN VALORCLASIFICA = '0'  THEN 1 ELSE 0 END) AS VARIOS,
   1-MAX(CASE WHEN VALORCLASIFICA = '01' THEN 1 ELSE 0 END) AS EFECTIVO,
   1-MAX(CASE WHEN VALORCLASIFICA = '03' THEN 1 ELSE 0 END) AS TAR_DEBITO,
   1-MAX(CASE WHEN VALORCLASIFICA = '04' THEN 1 ELSE 0 END) AS TAR_CREDITO,
   1-MAX(CASE WHEN VALORCLASIFICA = '06' THEN 1 ELSE 0 END) AS BONOPROMO,
   1-MAX(CASE WHEN VALORCLASIFICA = '09' THEN 1 ELSE 0 END) AS CRUCE_SALDOFAVOR,
   1-MAX(CASE WHEN VALORCLASIFICA = '10' THEN 1 ELSE 0 END) AS TRANS_ELECTRONICA,
   1-MAX(CASE WHEN VALORCLASIFICA = '11' THEN 1 ELSE 0 END) AS VENT_CREDITO,
   1-MAX(CASE WHEN VALORCLASIFICA = '12' THEN 1 ELSE 0 END) AS PAG_WHATSAPP,
   1-MAX(CASE WHEN VALORCLASIFICA = '13' THEN 1 ELSE 0 END) AS TAR_KOMIDA,
   1-MAX(CASE WHEN VALORCLASIFICA = '14' THEN 1 ELSE 0 END) AS KOMIDA_EFECTIVO,
   1-MAX(CASE WHEN VALORCLASIFICA = '15' THEN 1 ELSE 0 END) AS GANADOR_HAPPY,
   1-MAX(CASE WHEN VALORCLASIFICA = '97' THEN 1 ELSE 0 END) AS DEVOLUCIONES,
   1-MAX(CASE WHEN VALORCLASIFICA = 'B01' THEN 1 ELSE 0 END) AS B01,
   1-MAX(CASE WHEN VALORCLASIFICA = 'B02' THEN 1 ELSE 0 END) AS B02,
   1-MAX(CASE WHEN VALORCLASIFICA = 'B04' THEN 1 ELSE 0 END) AS B04,
	CODEMPRESA
FROM MVCLASIFICACION --LEFT JOIN
--SUPERTODO.dbo.MtCajaReg MTC ON VALORCLASIFICA=MTC.CODIGO AND MTC.CODIGO <> '0' 
WHERE CODCLASIFICA IN ('MTMEDPAG','CONSECUT','MTCAJAREG') AND CODEMPRESA IN ('SUPERTODO','BESTPRICE') 
  AND CODUSUARIO IN (
        SELECT CODUSUARIO
        FROM MVCLASIFICACION
        WHERE CODCLASIFICA = 'MTCAJAREG'
          AND CODEMPRESA IN ('SUPERTODO','BESTPRICE')
        GROUP BY CODUSUARIO
        HAVING COUNT(CODUSUARIO) <= 2
  )
GROUP BY CODUSUARIO,CODEMPRESA--,MTC.NOMBRE
ORDER BY CODUSUARIO
--TRAE TODOS LOS CAJEROS MAXIMO 2 CAJAS POR USUARIO WHERE
SELECT
    CODUSUARIO,
    COUNT(CODUSUARIO) AS TOTALCAJAS
FROM MVCLASIFICACION
WHERE CODCLASIFICA = 'MTCAJAREG' AND CODEMPRESA IN ('SUPERTODO','BESTPRICE')
GROUP BY CODUSUARIO
HAVING COUNT(CODUSUARIO) <= 2;

--delete from MVCLASIFICACION WHERE CODUSUARIO='JUANS'