/*Seleccionar Menu Administrac.Usuarios Menu 1-2, Cuando se Marca Sucede lo siguiente:
(CONSECUT,MTMEDPAG,ALERTA)="SI" TENDRA PERMISO 
(MTCAJAREG)="NO" TENDRA PERMISO 
(CENTCOS,VBODEGAS)=NO AFECTA EN NADA*/

/*ENTRE MAS REGISTROS ALLA EN MVCLASIFICACION SIGNIFICA QUE MAS ACCESO TENDRA*/
USE CONTROL_OFIMAEnterprise
select CODCLASIFICA,CODUSUARIO from MVCLASIFICACION WHERE CODCLASIFICA='MTCAJAREG' GROUP BY CODUSUARIO,CODCLASIFICA ORDER BY CODUSUARIO

USE CONTROL_OFIMAEnterprise
select CODCLASIFICA,CODUSUARIO,CODEMPRESA from MVCLASIFICACION WHERE CODCLASIFICA='MTCAJAREG' AND CODEMPRESA IN ('SUPERTODO','BESTPRICE') ORDER BY CODUSUARIO
--DEFINITIVO TRAE TODOS LOS CAJEROS Y SUS PERMISOS RESPECTIVOS
SELECT *
FROM MVCLASIFICACION
WHERE CODCLASIFICA IN ('MTCAJAREG')
  AND CODEMPRESA IN ('SUPERTODO','BESTPRICE')
  AND CODUSUARIO IN (
        SELECT CODUSUARIO
        FROM MVCLASIFICACION
        WHERE CODCLASIFICA = 'MTCAJAREG'
          AND CODEMPRESA IN ('SUPERTODO','BESTPRICE')
        GROUP BY CODUSUARIO
        HAVING COUNT(CODUSUARIO) <= 2
  )
ORDER BY CODUSUARIO;
--2 DEFINITIVO TRAE LOS DIFERENTES MEDIOS DE PAGO ASIGNADO
SELECT
    CODUSUARIO,
    MAX(CASE WHEN VALORCLASIFICA = '0'  THEN 1 ELSE 0 END) AS VARIOS,
    MAX(CASE WHEN VALORCLASIFICA = '01' THEN 1 ELSE 0 END) AS EFECTIVO,
    MAX(CASE WHEN VALORCLASIFICA = '03' THEN 1 ELSE 0 END) AS TAR_DEBITO,
    MAX(CASE WHEN VALORCLASIFICA = '04' THEN 1 ELSE 0 END) AS TAR_CREDITO,
    MAX(CASE WHEN VALORCLASIFICA = '06' THEN 1 ELSE 0 END) AS BONOPROMO,
    MAX(CASE WHEN VALORCLASIFICA = '09' THEN 1 ELSE 0 END) AS CRUCE_SALDOFAVOR,
	MAX(CASE WHEN VALORCLASIFICA = '10' THEN 1 ELSE 0 END) AS TRANS_ELECTRONICA,
	MAX(CASE WHEN VALORCLASIFICA = '11' THEN 1 ELSE 0 END) AS VENT_CREDITO,
	MAX(CASE WHEN VALORCLASIFICA = '12' THEN 1 ELSE 0 END) AS PAG_WHATSAPP,
	MAX(CASE WHEN VALORCLASIFICA = '13' THEN 1 ELSE 0 END) AS TAR_KOMIDA,
	MAX(CASE WHEN VALORCLASIFICA = '14' THEN 1 ELSE 0 END) AS KOMIDA_EFECTIVO,
	MAX(CASE WHEN VALORCLASIFICA = '15' THEN 1 ELSE 0 END) AS GANADOR_HAPPY,
	MAX(CASE WHEN VALORCLASIFICA = '97' THEN 1 ELSE 0 END) AS DEVOLUCIONES,
	CODEMPRESA
FROM MVCLASIFICACION
WHERE CODCLASIFICA = 'MTMEDPAG'
  AND CODUSUARIO IN (
        SELECT CODUSUARIO
        FROM MVCLASIFICACION
        WHERE CODCLASIFICA = 'MTCAJAREG'
          AND CODEMPRESA IN ('SUPERTODO','BESTPRICE')
        GROUP BY CODUSUARIO
        HAVING COUNT(CODUSUARIO) = 1
  )
GROUP BY CODUSUARIO,CODEMPRESA
ORDER BY CODUSUARIO

--TRAE TODOS LOS CAJEROS MAXIMO 2 CAJAS POR USUARIO WHERE
SELECT
    CODUSUARIO,
    COUNT(CODUSUARIO) AS TOTALCAJAS
FROM MVCLASIFICACION
WHERE CODCLASIFICA = 'MTCAJAREG' AND CODEMPRESA IN ('SUPERTODO','BESTPRICE')
GROUP BY CODUSUARIO
HAVING COUNT(CODUSUARIO) <= 2;

--delete from MVCLASIFICACION WHERE CODUSUARIO='JUANS'