SELECT 
    CAST(M.FECHAMVTO AS DATE) AS Dia, 
	SUM(M.VALOR) AS TRANSFERENCIAS,
	MONTH(M.FECHAMVTO) AS Mes
FROM 
	MvCuadre AS M
	WHERE M.MEDIOPAG IN ('54','55','56','57','58','59') AND M.TIPODCTO in('25') and M.FECHAMVTO >'01-01-2026'
GROUP BY 
    CAST(M.FECHAMVTO AS DATE),M.FECHAMVTO 
ORDER BY 
    Dia;