SELECT   A.NRODCTO, A.FECHA, A.NIT, B.BODEGA, B.PRODUCTO, SUM(B.CANVENTA) 
FROM         MVTRADE B, TRADE A
WHERE     (B.TIPODCTO = 'PD') AND (B.BODEGA in ('099.ROMELIO', '100.NEW.YORK', '101.SUPERGAN', '102.CARULLA', '103.RETREPO', '104.SINCELE1', '105.SINCELE3', 
                         '106.SINCELE4', '107.SINCELE5', '108.QUINTA', '109.MONTERIA', '110.CALNORTE', '111.COSMCEN', '112.CALI6', '113.TULUA', '114.CARTAGO', '115.BUGA', '116.POPAYAN', '117.MULTIF. VIA 40', '118.MULTIF. CALI', 
                         '119.MULTIF. CALLE 77', '120.MULTIT. SINCELEJ', '130.BPRINCIPALVERONA', '137.SINCELE6VR')) AND (B.CANVENTA >= '0')
AND A.FECHA >= getdate()-60
AND A.NRODCTO = B.NRODCTO
AND A.TIPODCTO = B.TIPODCTO
GROUP BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA
ORDER BY A.NRODCTO, A.FECHA,A.NIT, B.BODEGA, B.PRODUCTO, B.CANVENTA