SELECT     A.PRODUCTO, B.DESCRIPCIO, B.FECHA_ING, B.TIPOINV, C.NOMBRE , D.NOMBRE  , E.NOMBRE , F.NOMBRE , 
                      A.TIPOMVTO, G.ENTRADA, A.TIPODCTO, A.BODEGA, A.CANTIDAD, A.FECHA, A.NRODCTO, A.ORIGEN
FROM         MVTRADE A INNER JOIN
                      MTMERCIA B ON A.PRODUCTO = B.CODIGO INNER JOIN
                      TIPOINV C ON B.TIPOINV = C.CODIGO INNER JOIN
                      MTLINEA D ON B.CODLINEA = D.CODLINEA INNER JOIN
                      MTSBLIN E ON B.CODSBLIN = E.CODSBLIN INNER JOIN
                      MTGRUINV F ON B.CODGRUPO = F.CODGRUPO INNER JOIN
                      TIPOMVTO G ON A.TIPOMVTO = G.TIPOMVTO
WHERE     (A.BODEGA IN ('099.ROMELIO', '100.NEW.YORK', '101.SUPERGAN', '102.CARULLA', '103.RETREPO', '104.SINCELE1', '105.SINCELE3', 
                         '106.SINCELE4', '107.SINCELE5', '108.QUINTA', '109.MONTERIA', '110.CALNORTE', '111.COSMCEN', '112.CALI6', '113.TULUA', '114.CARTAGO', '115.BUGA', '116.POPAYAN', '117.MULTIF. VIA 40', '118.MULTIF. CALI', 
                         '119.MULTIF. CALLE 77', '120.MULTIT. SINCELEJ', '130.BPRINCIPALVERONA', '137.SINCELE6VR'))

AND (A.TIPOMVTO NOT IN ('SIF','SI','ECG', 'SC','STL','SRN', 'STN','EDG', 'SDG')) 
--AND (B.TIPOINV IN ('TL025')) 
AND (A.TIPODCTO NOT IN ('P1', 'P2', 'P3','RE','PD','OR')) 
AND  A.FECHA >= '1/1/2026'  AND  A.FECHA <= '31/12/2026' 
ORDER BY A.PRODUCTO