SELECT 
    CAST(M.FECHAMVTO AS DATE) AS Dia, 
	SUM(M.VALOR) AS EFECTIVO,
                MONTH(M.FECHAMVTO) AS Mes
FROM 
	MvCuadre AS M
	WHERE M.MEDIOPAG='61' AND M.TIPODCTO in('25') and M.FECHAMVTO >'01-01-2026'
GROUP BY 
    CAST(M.FECHAMVTO AS DATE) , M.FECHAMVTO
ORDER BY 
    Dia;