SELECT         A.PRODUCTO, A.NOMBRE, A.FECHA
FROM            MVTRADE AS A INNER JOIN
                         TRADE AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO INNER JOIN
                         MTMERCIA AS C ON A.PRODUCTO = C.CODIGO
WHERE        (A.FECHA >= '01/01/2000') AND (A.TIPODCTO in ('g1','f2','f3','f1'))
--AND C.TIPOINV IN ('TL025')

ORDER BY A.FECHA DESC