--CLIENTE X DEFECTO
SELECT 
    CODUSUARIO,
    VALOR,
    CODEMPRESA
FROM BESTPRICE.dbo.MVGLOUSR
WHERE CAMPO = 'CLIENTECONTADO'

UNION ALL
SELECT 
    CODUSUARIO,
    VALOR,
    CODEMPRESA
FROM SUPERTODO.dbo.MVGLOUSR
WHERE CAMPO = 'CLIENTECONTADO';