USE CONTROL_OFIMAEnterprise
select * from MVCLASIFICACION
select * from MVGRUPO
select * from MTUSUARIO WHERE NOMBRE LIKE '%YEMER%'
select * from MVEMPRESA WHERE CODGRUPO like 'SIST06'

select MT.CODGRUPO,MT.NOMBRE,MVE.CODEMPRESA AS BODEGA,MV.CODUSUARIO from MTGRUPO MT 
INNER JOIN
MVGRUPO MV ON MV.CODGRUPO=MT.CODGRUPO 
INNER JOIN
MVEMPRESA MVE ON MVE.CODGRUPO=MT.CODGRUPO 
WHERE MV.CODUSUARIO like '%GISSAB%'