USE CONTROL_OFIMAENTERPRISE
SELECT
	A.CODGRUPO,
	A.NOMBRE AS GRUPO,
	B.IDMENU,
	C.NOMBREOPC,
	B.CONSULTA,
	B.INGRESO,
	B.RETIRO,
	B.MODIFICA
FROM
	MTGRUPO A
	INNER JOIN MVMENU B ON A.CODGRUPO = B.CODGRUPO
	INNER JOIN MTMENU C ON B.IDMENU = C.IDMENU WHERE A.CODGRUPO='SIST06'
--GRUPO
select MM.IDMENU,MP.NOMBRE AS MODULO,MM.IDMENU,MM.POSMENU AS POSICION,MM.NOMBREOPC AS OPCION
from MTMENU MM INNER JOIN
MTPROGRAMA MP ON MP.CODPROGRAM = MM.CODPROGRAM
WHERE MM.IDMENU='ACT_AYUDA_LINEA'

--SI SE DESMARCA LA CASILLA SE QUITA EL PERMISO Y BORRA REGISTRO TABLA MVMENU
select MV.CODGRUPO,MG.NOMBRE AS GRUPO,MP.NOMBRE AS MODULO,MM.IDMENU,MM.POSMENU AS POSICION,MM.NOMBREOPC AS OPCION,MV.INGRESO,MV.MODIFICA,MV.RETIRO,MV.CONSULTA from MVMENU MV
INNER JOIN MTMENU MM ON MM.IDMENU=MV.IDMENU
INNER JOIN MTPROGRAMA MP ON MP.CODPROGRAM = MM.CODPROGRAM
INNER JOIN MTGRUPO MG ON MG.CODGRUPO = MV.CODGRUPO