USE COLNOTEXSA;
SELECT * from trade;
select * from trade WHERE NRODCTO='119937' and TIPODCTO='FA';
--CONSULTA ENCABEZADO FACTURA YA
select NRODCTO,NIT,FECING,FECMOD,TIPOVTA,CODCC,CODVEN,TIPODCTO from trade WHERE NRODCTO='119937' and TIPODCTO='FA';
---- CONSULTA PARA DATOS GENERALES ----
--1 Cliente YA
select TIPOCAR,TIPOMVTO,MEDIOPAG,FORMAPAGO,CODCTACXP,CODIGOCTA,CODINT,DSCTOCOM from trade WHERE NRODCTO='119937' and TIPODCTO='FA';
--2 Triutarios YA
select CODRETE,XRETIVA,PORAIU,CODICA,XRETICA,TASAINTERE,PRETECREE from trade WHERE NRODCTO='119937' and TIPODCTO='FA';
--4 Generales YA
select REMISION,FECHANIF,ENVIADOA,DIR,CIUDADCLI,TRANSPORTA,NOTA from trade WHERE NRODCTO='119937' and TIPODCTO='FA';
--5 Moneda de Negociacion YA
select TIPOMONEDA,CODMONEDA,TCAMBIO,DESCUENTO from trade WHERE NRODCTO='119937' and TIPODCTO='FA';
--6 Descuentos Financieros YA
select FECHA1,FECHA2,FECHA3,XDESCUENTO from trade WHERE NRODCTO='119937' and TIPODCTO='FA';
--7 Totales SUBTOTAL y TOTAL FACT no son columnas, se calcula YA
select BRUTO,DESCUENTO,DSCTOCOM,XFLETES,DESCTOPP,CONIVA,IVABRUTO,SINIVA,VLRETFTE,VLRETCREE,XDESFINANC,XBASEIVA,DESCFINANC,BASEIVA from trade WHERE NRODCTO='119937' and TIPODCTO='FA';
--(SubTotal+DESCUENTO) as Total
select bruto,descuento,(BRUTO-DESCUENTO) as SubTotal FROM TRADE WHERE NRODCTO='119937' and TIPODCTO='FA';
--(BRUTO DESCUENTO SUBTOTAL y TOTAL
select BRUTO,DESCUENTO,(BRUTO-DESCUENTO) as SUBTOTAL ,((BRUTO-DESCUENTO)+((BRUTO-DESCUENTO)*19)/100) as TOTAL FROM TRADE WHERE NRODCTO='119937' and TIPODCTO='FA';