USE [COLNOTEXSA]
GO

/****** Object:  View [dbo].[V_ActAuxilioEmple]    Script Date: 25/04/2024 10:06:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Drop View dbo.V_ActAuxilioEmple
CREATE View [dbo].[v_cancidesrod]
As
	SELECT CODIGO, CODBARRAS, DESCRIPCIO, TIPOINV, CODLINEA, CODSBLIN, CODGRUPO, FECHA_ING, CLASIFICA1 as clasifica, CTACOM, CTACOMDEV, CTACOMDIVA, CTACOMDRTE, CTACOMIVA,CTACOMRTE, CTAVTA, CTAVTADEV, CTAVTADIVA, CTAVTADRTE, CTAVTAIVA, CTAVTARTE, CTACOM AS Gastos,CTACOMDEV as DevoGastos,CTACOMDIVA AS Gastoscta1,CTACOMIVA AS Gastoscta2, CTACOMDRTE as Gastoscta3,  CTACOMRTE as Gastoscta4, CTDRIRCCOM AS RegiComun, CTRIRCCOM AS DevRegComun,CLIENTE_PR, CLASIFICA1
FROM  MTMERCIA
WHERE HABILITADO='1' AND ESPRODUCTO='1' AND TIPOINV In ('0','PT005','PT010','PT015','PT020','TPB00','PT040','PT001','TL027','TL045','SM001')

GO


