USE SUPERTODO
SELECT        
	A.FECHA, A.TIPODCTO, A.NRODCTO,E.CODIGO,E.CODBARRAS,D.DESCRIPCIO,E.COSTO_ING,A.CANTIDAD,A.BODEGA,
	A.CODCC,B.NIT,C.NOMBRE AS PROVEEDOR,F.NOMBRE AS LINEA,G.NOMBRE AS SUBLINEA,B.NOTA
FROM            
	Mvtrade AS A INNER JOIN
	Trade AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO AND A.ORIGEN = B.ORIGEN INNER JOIN
	MtProcli AS C ON B.NIT = C.NIT INNER JOIN
	TipoVta AS D ON B.TIPOVTA = D.TIPOVTA INNER JOIN
	MtMercia AS E ON A.PRODUCTO = E.CODIGO INNER JOIN
	MtLinea AS F ON E.CODLINEA = F.CODLINEA INNER JOIN
	MtSblin AS G ON E.CODSBLIN = G.CODSBLIN
WHERE        
A.TIPODCTO IN ('K7','G1','K8','G2')
ORDER BY  
	A.PRODUCTO, A.FECHA DESC