USE BESTPRICE
SELECT
	TI.NOMBRE AS LINEA,
	S.BODEGA,
	S.CODIGO,
	MM.DESCRIPCIO,
	MM.FECHA_ING,
	MM.COSTO_ING,
	ROUND(SUM(S.ICANTIDAD), 0) AS ENTRADAS_STD,
	ROUND(SUM(S.OCANTIDAD), 0) AS SALIDAS_STD,
	ROUND(SUM(S.ICANTIDAD - S.OCANTIDAD), 0) AS SALDO_STD
FROM 
	SALDOINV S 
INNER JOIN
	MTMERCIA MM ON MM.CODIGO=S.CODIGO 
INNER JOIN
	TIPOINV TI ON MM.TIPOINV=TI.CODIGO
GROUP BY
	TI.NOMBRE,S.BODEGA,S.CODIGO,MM.DESCRIPCIO,MM.FECHA_ING,MM.COSTO_ING
ORDER BY
	S.CODIGO
