SELECT 
	A.PRODUCTO,A.FECHA, A.TIPODCTO, A.NRODCTO, A.BODEGA, A.CODINT, 
	A.NOMBRE, A.CANTIDAD, A.IVA, A.VALORUNIT, A.VLRVENTA, A.VLRVENTA * A.CANTIDAD AS VLR_CANT, 
	A.VALORUNIT * A.CANTIDAD AS VLRUNI_CANT , A.VLRVENTA * A.CANTIDAD - A.VALORUNIT * A.CANTIDAD , 
	A.COSTO, A.HCOSTO, B.NIT, D.DESCRIPCIO, E.TIPOINV, F.NOMBRE , 
	E.CODLINEA, G.NOMBRE , E.CODSBLIN, E.CODBARRAS, A.DESCUENTO
FROM 
	Mvtrade AS A INNER JOIN
	Trade AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO AND A.ORIGEN = B.ORIGEN INNER JOIN
	MtProcli AS C ON B.NIT = C.NIT INNER JOIN
	TipoVta AS D ON B.TIPOVTA = D.TIPOVTA INNER JOIN
	MtMercia AS E ON A.PRODUCTO = E.CODIGO INNER JOIN
	TipoInv AS F ON E.TIPOINV = F.CODIGO INNER JOIN
	MtLinea AS G ON E.CODLINEA = G.CODLINEA INNER JOIN
	MtSblin AS H ON E.CODSBLIN = H.CODSBLIN
WHERE    
	(A.FECHA >= '01/01/2023')
	AND (A.ORIGEN = 'COM')
	AND A.TIPODCTO IN ('F1','F3','F4')
	AND B.NIT NOT IN ('132506911')
ORDER BY  A.PRODUCTO, A.FECHA DESC

SELECT 
	A.PRODUCTO,A.FECHA, A.TIPODCTO, A.NRODCTO, A.BODEGA, A.CODINT, 
	A.NOMBRE, A.CANTIDAD, A.IVA, A.VALORUNIT,A.VLRVENTA * A.CANTIDAD AS VLR_CANT, 
	A.VLRVENTA * A.CANTIDAD - A.VALORUNIT * A.CANTIDAD , 
	B.NIT, D.DESCRIPCIO, E.TIPOINV, F.NOMBRE , 
	E.CODLINEA, G.NOMBRE , E.CODSBLIN, E.CODBARRAS
FROM 
	Mvtrade AS A INNER JOIN
	Trade AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO AND A.ORIGEN = B.ORIGEN INNER JOIN
	MtProcli AS C ON B.NIT = C.NIT INNER JOIN
	TipoVta AS D ON B.TIPOVTA = D.TIPOVTA INNER JOIN
	MtMercia AS E ON A.PRODUCTO = E.CODIGO INNER JOIN
	TipoInv AS F ON E.TIPOINV = F.CODIGO INNER JOIN
	MtLinea AS G ON E.CODLINEA = G.CODLINEA INNER JOIN
	MtSblin AS H ON E.CODSBLIN = H.CODSBLIN
WHERE    
	(A.FECHA >= '01/01/2023')
	AND (A.ORIGEN = 'COM')
	AND A.TIPODCTO IN ('F1','F3','F4')
	AND B.NIT NOT IN ('132506911')
ORDER BY  A.PRODUCTO, A.FECHA DESC