USE SUPERTODO
SELECT        
	A.FECHA, A.TIPODCTO,H.DESCRIPCIO, A.NRODCTO,E.CODIGO,E.CODBARRAS,E.DESCRIPCIO,E.COSTO_ING,A.CANTIDAD,A.BODEGA,
	A.CODCC,B.NIT,C.NOMBRE AS PROVEEDOR,F.NOMBRE AS LINEA,G.NOMBRE AS SUBLINEA,B.NOTA
FROM            
	Mvtrade AS A INNER JOIN
	Trade AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO AND A.ORIGEN = B.ORIGEN INNER JOIN
	MtProcli AS C ON B.NIT = C.NIT INNER JOIN
	TipoVta AS D ON B.TIPOVTA = D.TIPOVTA INNER JOIN
	MtMercia AS E ON A.PRODUCTO = E.CODIGO INNER JOIN
	MtLinea AS F ON E.CODLINEA = F.CODLINEA INNER JOIN
	MtSblin AS G ON E.CODSBLIN = G.CODSBLIN INNER JOIN
	CONSECUT AS H ON A.TIPODCTO = H.TIPODCTO AND A.ORIGEN= H.ORIGEN
WHERE        
A.TIPODCTO IN ('SR','H6','B7','15','16','17','18')
ORDER BY  
	A.PRODUCTO, A.FECHA DESC