USE SUPERTODO;
SELECT 
    MM.CODIGO,MM.CODBARRAS,MM.DESCRIPCIO,MS.NOMBRE AS CATEGORIA,LISTPRECIO_1,LISTPRECIO_2,LISTPRECIO_3,
    LISTPRECIO_4,LISTPRECIO_5,LISTPRECIO_6,LISTPRECIO_7
FROM MtMercia AS MM
INNER JOIN MtSblin AS MS 
    ON MS.CODSBLIN = MM.CODSBLIN
INNER JOIN (
    SELECT 
        CODPRODUC,
        MAX(CASE WHEN CODPRECIO = '1' THEN PRECIO END) AS LISTPRECIO_1,
        MAX(CASE WHEN CODPRECIO = '2' THEN PRECIO END) AS LISTPRECIO_2,
        MAX(CASE WHEN CODPRECIO = '3' THEN PRECIO END) AS LISTPRECIO_3,
        MAX(CASE WHEN CODPRECIO = '4' THEN PRECIO END) AS LISTPRECIO_4,
        MAX(CASE WHEN CODPRECIO = '5' THEN PRECIO END) AS LISTPRECIO_5,
        MAX(CASE WHEN CODPRECIO = '6' THEN PRECIO END) AS LISTPRECIO_6,
        MAX(CASE WHEN CODPRECIO = '7' THEN PRECIO END) AS LISTPRECIO_7
    FROM SUPERTODO.dbo.MvPrecio
    WHERE CODPRECIO IN ('1','2','3','4','5','6','7')
    GROUP BY CODPRODUC
) AS Precios 
    ON Precios.CODPRODUC = MM.CODIGO
ORDER BY MM.CODIGO ASC;
