SELECT 
--PRODUCTO
	CODIGO,CODBARRAS,DESCRIPCIO,
	IVA,FECING,CODTARIVA,
--1. CUENTA DE VENTA
	CTAVTA AS VENTA,
	CTAVTADEV AS DEVOL_VTA,
	CTAVTADIVA AS VENTA_CTA1,
	CTAVTAIVA AS VENTA_CTA2,
--3. CUENTAS DE GASTO
	CTACOM AS GASTOS,
	CTACOMDEV AS DEV_GTO,
	CTACOMDIVA AS GASTO_CTA1,
	CTACOMIVA AS GASTO_CTA2,
	CTACOMDRTE AS GASTO_CTA3,
	CTACOMRTE AS GASTO_CTA4,
--4. GASTOS RETENCION EN IVA
	CTDRIRCCOM AS REGIMEN_COMUN,
	CTRIRCCOM AS DEV_REG_COMUN 
FROM 
	MtMercia 