USE SUPERTODO
--VALIDACION DE TAR CUENTAS CONTABLES

/*select TOP(10)CODIGO,MVTRADE.IVA,CODTARIVA from Mvtrade INNER JOIN
MtMercia ON CODIGO=PRODUCTO
where FECHA='01/01/2026' AND ORIGEN='FAC' AND TIPODCTO <>'F2' 
*/

SELECT
	NRODCTO,
    CODIGO,
    MVTRADE.IVA AS IVA_ACTUAL,
    CODTARIVA,
    CASE CODTARIVA
        WHEN 'TAR0' THEN 0
        WHEN 'TAR1' THEN 16
        WHEN 'TAR2' THEN 18
    END AS IVA_ESPERADO,
    MVTRADE.IVA -
    CASE CODTARIVA
        WHEN 'TAR0' THEN 0
        WHEN 'TAR1' THEN 16
        WHEN 'TAR2' THEN 18
    END AS DIFERENCIA
FROM Mvtrade
INNER JOIN MtMercia
    ON CODIGO = PRODUCTO
WHERE FECHA = '01/01/2026'
  AND ORIGEN = 'FAC'
  AND TIPODCTO <> 'F2'
  AND MVTRADE.IVA <>
      CASE CODTARIVA
          WHEN 'TAR0' THEN 0
          WHEN 'TAR1' THEN 16
          WHEN 'TAR2' THEN 18
      END;