--COLNOTEX
SELECT   'COLNOTEX' AS EMPRESA,A.NIT, B.NOMBRE
FROM         COLNOTEXSA.dbo.MVTO A INNER JOIN
             COLNOTEXSA.dbo.NIT B ON A.NIT = B.NRONIT INNER JOIN
			 COLNOTEXSA.dbo.MTPROCLI AS D ON D.NIT=A.NIT
WHERE A.CODCC='0110' AND A.CODCOMPROB<>'CC' AND D.ESPROVEE='S' AND D.ESCLIENTE NOT IN('S') AND D.HABILITADO='S'
group by   A.NIT, B.NOMBRE
UNION ALL
--VERGONA
SELECT   'VERONA' AS EMPRESA, A.NIT, B.NOMBRE
FROM         VERONASAS.dbo.MVTO A INNER JOIN
             VERONASAS.dbo.NIT B ON A.NIT = B.NRONIT INNER JOIN
			 VERONASAS.dbo.MTPROCLI AS D ON D.NIT=A.NIT

WHERE A.CODCOMPROB<>'CC' AND D.ESPROVEE='S' AND D.ESCLIENTE NOT IN('S') AND D.HABILITADO='S'
group by     A.NIT, B.NOMBRE
UNION ALL
--REPUBLICA
select 'REPUBLICA' AS EMPRESA,NIT,NOMBRE from SUPERTODO.dbo.MtProcli where NOMBRE like '%TELENO%' OR NOMBRE like '%COMPU%' OR NOMBRE like '%FACTORY%' OR NOMBRE like '%TECH%' 

--update MTPROCLI set HABILITADO='S' where NIT IN ('800153993-7')
--select ESPROVEE,ESCLIENTE,NIT,NOMBRE from MTPROCLI WHERE ESPROVEE='S' AND ESCLIENTE NOT IN('S') 