USE SUPERTODO
select 
	B.DESCRIPCIO,B.CODBARRAS,B.CODIGO,B.CODLINEA,
	G.NOMBRE AS CATEGORIA,B.CODSBLIN,D.NOMBRE AS SUB_CATEGORIA,IVA,
	UNIDADMED,HABILITADO AS HABILITADO,PRODTER AS COMERCIAL,MATPRIMA AS COMPRAS,REFERPROV
from 
	MtMercia B INNER JOIN
	MtLinea AS G ON B.CODLINEA = G.CODLINEA INNER JOIN
	MTSBLIN D ON B.CODSBLIN = D.CODSBLIN
WHERE 
	B.CODIGO LIKE 'A-%' OR B.CODIGO LIKE 'B-%'