USE SUPERTODO
SELECT 
--0.DATOS GENERALES
	E.CODIGO,E.CODBARRAS,
	CASE E.ESPRODUCTO WHEN 1 THEN 'PRODUCTO' ELSE 'SERVICIO' END AS PRODUC_SERVICIO,E.DESCRIPCIO,
	E.DESCRIP2 AS DESCRIP_ALTERNA,
	CASE E.HABILITADO WHEN 1 THEN 'SI' ELSE 'NO' END AS HABILITADO,
    CASE E.PRODTER    WHEN 1 THEN 'SI' ELSE 'NO' END AS COMERCIAL,
    CASE E.MATPRIMA   WHEN 1 THEN 'SI' ELSE 'NO' END AS COMPRAS,
	G.NOMBRE AS LINEA,H.NOMBRE AS SUBLINEA,CODGRUPO,E.UNIDADMED,E.UNDEMPAQUE,E.FECHA_ING,
	E.PASSWORDIN,E.FECMOD,E.PASSWORDMO,
--1. CUENTA DE VENTA
	CTAVTA AS VENTA,
	CTAVTADEV AS DEVOL_VTA,
	CTAVTAIVA AS VENTA_CTA1,
	CTAVTADIVA AS VENTA_CTA2,
--3. CUENTAS DE GASTO
	CTACOM AS GASTOS,
	CTACOMDEV AS DEV_GTO,
	CTACOMDIVA AS GASTO_CTA1,
	CTACOMIVA AS GASTO_CTA2,
	CTACOMDRTE AS GASTO_CTA3,
	CTACOMRTE AS GASTO_CTA4,
--4. GASTOS RETENCION EN IVA
	CTDRIRCCOM AS REGIMEN_COMUN,
	CTRIRCCOM AS DEV_REG_COMUN 
FROM 
	MtMercia E INNER JOIN
	MtLinea AS G ON E.CODLINEA = G.CODLINEA INNER JOIN
	MtSblin AS H ON E.CODSBLIN = H.CODSBLIN