USE COLNOTEXSA
select * from COSTOINV WHERE CODIGO='96100' AND ANO>='2025'; --ESTE ES COSTO
select CODLOTE from SALDOINV WHERE CODIGO='97590' --CODLOTE

select * from MTLOTE WHERE PRODUCTO='97590'--Num LOTE 

--QUERY DEFINITIVA
SELECT
	S.BODEGA,
	S.CODIGO,
	MM.DESCRIPCIO,
	S.ICANTIDAD AS SALDO,
	MM.FECHA_ING,
	MM.COSTO_ING,
	S.CODLOTE,
	S.ICANTIDAD * MM.COSTO_ING AS TOTAL
FROM 
	SALDOINV S 
INNER JOIN
	MTMERCIA MM ON MM.CODIGO=S.CODIGO 
WHERE 
	S.ANO >= '2025' AND
	S.BODEGA IN('09.PT.VENB','34.CONSMAXI','85.MPTAP.CUA','86.MPTAP.APR','87.MPTAP.RECH',
	'88.PPTAP.APR','89.PTTAP.CUA','90.PTTAP.APR','92.TELASBIOS','93.TELASBIOS2','94.PTTAP.DESP',
	'95.MPTAP.APR2','96.PTTAP.CALID')

--QUERY MAL
SELECT 
	ML.FECHAC,
	S.BODEGA,
	M.CODIGO,    
	M.DESCRIPCIO,
	ROUND(SUM(ICANTIDAD), 0) - ROUND(SUM(OCANTIDAD), 0) AS CANTIDAD_SALDO,
	M.FECHA_ING,
	S.ANO,
	S.PERIODO,
	M.COSTO_ING,
	S.CODLOTE,
	(ROUND(SUM(ICANTIDAD), 0) - ROUND(SUM(OCANTIDAD), 0))*M.COSTO_ING AS TOTAL
FROM
	SALDOINV S
INNER JOIN
	MTMERCIA M ON M.CODIGO=S.CODIGO
INNER JOIN
	MTLOTE ML ON ML.CODLOTE=S.CODLOTE AND ML.PRODUCTO=S.CODIGO
WHERE
	M.CODIGO='93250' AND 
	S.BODEGA IN('09.PT.VENB','34.CONSMAXI','85.MPTAP.CUA','86.MPTAP.APR','87.MPTAP.RECH',
	'88.PPTAP.APR','89.PTTAP.CUA','90.PTTAP.APR','92.TELASBIOS','93.TELASBIOS2','94.PTTAP.DESP',
	'95.MPTAP.APR2','96.PTTAP.CALID') 
GROUP BY
	ML.FECHAC,BODEGA,M.CODIGO,M.DESCRIPCIO,M.FECHA_ING,S.ANO,S.PERIODO,S.CODLOTE,M.COSTO_ING 
