SELECT
	E.CODIGO,
	E.CODBARRAS,
	E.DESCRIPCIO,
	H.NOMBRE AS CATEGORIA,
	C.NOMBRE AS PROVEEDOR,
	A.FECHA AS ULT_FECHA,
	TBCOSTO.HCOSTO AS ULT_COSTO,
	LISTPRECIO_1,
	LISTPRECIO_2,
	LISTPRECIO_3,
	LISTPRECIO_4,
	LISTPRECIO_5,
	LISTPRECIO_6,
	LISTPRECIO_7
FROM
	Mvtrade AS A INNER JOIN
	Trade AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO AND A.ORIGEN = B.ORIGEN INNER JOIN
	MtProcli AS C ON B.NIT = C.NIT INNER JOIN
	MtMercia AS E ON A.PRODUCTO = E.CODIGO INNER JOIN
	MtSblin AS H ON E.CODSBLIN = H.CODSBLIN 
	INNER JOIN
    (SELECT 
        CODPRODUC,
        MAX(CASE WHEN STD_MVP.CODPRECIO = '1' THEN STD_MVP.PRECIO ELSE NULL END) AS LISTPRECIO_1, -- Precio con CODPRECIO 4
        MAX(CASE WHEN STD_MVP.CODPRECIO = '2' THEN STD_MVP.PRECIO ELSE NULL END) AS LISTPRECIO_2, -- Precio con CODPRECIO 5
		MAX(CASE WHEN STD_MVP.CODPRECIO = '3' THEN STD_MVP.PRECIO ELSE NULL END) AS LISTPRECIO_3, -- Precio con CODPRECIO 5
		MAX(CASE WHEN STD_MVP.CODPRECIO = '4' THEN STD_MVP.PRECIO ELSE NULL END) AS LISTPRECIO_4, -- Precio con CODPRECIO 5
		MAX(CASE WHEN STD_MVP.CODPRECIO = '5' THEN STD_MVP.PRECIO ELSE NULL END) AS LISTPRECIO_5, -- Precio con CODPRECIO 5
		MAX(CASE WHEN STD_MVP.CODPRECIO = '6' THEN STD_MVP.PRECIO ELSE NULL END) AS LISTPRECIO_6, -- Precio con CODPRECIO 5
		MAX(CASE WHEN STD_MVP.CODPRECIO = '7' THEN STD_MVP.PRECIO ELSE NULL END) AS LISTPRECIO_7 -- Precio con CODPRECIO 5
     FROM  
        SUPERTODO.dbo.MvPrecio STD_MVP 
     WHERE 
        CODPRECIO IN ('1','2','3','4', '5','6','7')
     GROUP BY  
        CODPRODUC) AS Precios ON Precios.CODPRODUC = E.CODIGO
	INNER JOIN
    (SELECT 
		CODIGO,
		HCOSTO
     FROM  
        SUPERTODO.dbo.COSTOINV 
     WHERE 
        ANO='2025' AND PERIODO='7') AS TBCOSTO ON TBCOSTO.CODIGO = E.CODIGO

WHERE
	A.ORIGEN = 'COM'
	AND A.TIPODCTO IN ('F1','F4')
ORDER BY E.CODIGO ASC