USE SUPERTODO
SELECT
	A.BODEGA,  A.CODIGO, B.CODBARRAS, B.DESCRIPCIO as DESCRIPCION, E.NOMBRE AS GRUPO, C.NOMBRE AS LINEA , 
	D.NOMBRE AS SUBLINEA, SUM(A.ICANTIDAD - A.OCANTIDAD) as SALDO,B.COSTO_ING, B.HABILITADO
FROM
	SALDOINV A INNER JOIN
	MTMERCIA B ON A.CODIGO = B.CODIGO INNER JOIN
	MTLINEA C ON B.CODLINEA = C.CODLINEA INNER JOIN
	MTSBLIN D ON B.CODSBLIN = D.CODSBLIN  INNER JOIN
	MT2CLAF E ON B.CLASIFICA2 = E.CODIGO
WHERE     (A.BODEGA IN ('06.RNYBODEGA','05.STBODEGA','04.BDEVOLUCI','02.BALMACEN','01.BPRINCIPAL'))
GROUP BY A.BODEGA, E.NOMBRE, D.NOMBRE, B.CODLINEA, C.NOMBRE, A.CODIGO, B.DESCRIPCIO, B.CODBARRAS,B.COSTO_ING, B.HABILITADO
ORDER BY C.NOMBRE, B.DESCRIPCIO

USE BESTPRICE
SELECT
	A.BODEGA,  A.CODIGO, B.CODBARRAS, B.DESCRIPCIO as DESCRIPCION, E.NOMBRE AS GRUPO, C.NOMBRE AS LINEA , 
	D.NOMBRE AS SUBLINEA, SUM(A.ICANTIDAD - A.OCANTIDAD) as SALDO,B.COSTO_ING, B.HABILITADO
FROM
	SALDOINV A INNER JOIN
	MTMERCIA B ON A.CODIGO = B.CODIGO INNER JOIN
	MTLINEA C ON B.CODLINEA = C.CODLINEA INNER JOIN
	MTSBLIN D ON B.CODSBLIN = D.CODSBLIN  INNER JOIN
	MT2CLAF E ON B.CLASIFICA2 = E.CODIGO
WHERE     (A.BODEGA IN ('33.BGASTOS','32.BEERPUB','02.BALMACEN'))
GROUP BY A.BODEGA, E.NOMBRE, D.NOMBRE, B.CODLINEA, C.NOMBRE, A.CODIGO, B.DESCRIPCIO, B.CODBARRAS,B.COSTO_ING, B.HABILITADO
ORDER BY C.NOMBRE, B.DESCRIPCIO