USE SUPERTODO
SELECT        
	A.FECHA,B.HORA,A.TIPODCTO, A.NRODCTO,E.CODIGO,E.CODBARRAS,E.DESCRIPCIO,A.CANTIDAD,A.VLRVENTA AS VLRUNIT,(A.VLRVENTA*A.CANTIDAD) AS TOTAL,A.BODEGA,
	A.CODINT,B.NIT,C.NOMBRE AS PROVEEDOR,B.NOTA
FROM            
	Mvtrade AS A INNER JOIN
	Trade AS B ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO AND A.ORIGEN = B.ORIGEN INNER JOIN
	MtProcli AS C ON B.NIT = C.NIT INNER JOIN
	TipoVta AS D ON B.TIPOVTA = D.TIPOVTA INNER JOIN
	MtMercia AS E ON A.PRODUCTO = E.CODIGO
WHERE        
A.TIPODCTO IN ('SR')
ORDER BY  
	A.FECHA DESC,A.NRODCTO DESC