USE COLNOTEXSA
SELECT
	TI.NOMBRE AS LINEA,
	S.BODEGA,
	S.CODIGO,
	MM.DESCRIPCIO,
	S.ICANTIDAD ,
	MM.FECHA_ING,
	MM.COSTO_ING,
	S.CODLOTE,
	S.ICANTIDAD * MM.COSTO_ING  AS TOTAL
FROM 
	SALDOINV S 
INNER JOIN
	MTMERCIA MM ON MM.CODIGO=S.CODIGO 
INNER JOIN
	TIPOINV TI ON MM.TIPOINV=TI.CODIGO
WHERE 
	S.ANO >= '2025' AND
	S.BODEGA IN('09.PT.VENB','34.CONSMAXI','85.MPTAP.CUA','86.MPTAP.APR','87.MPTAP.RECH',
	'88.PPTAP.APR','89.PTTAP.CUA','90.PTTAP.APR','92.TELASBIOS','93.TELASBIOS2','94.PTTAP.DESP',
	'95.MPTAP.APR2','96.PTTAP.CALID')
