--INFORME ABCEDAF
USE SUPERTODO
select * from MtLinea
select * from MtSblin
select s.ANO,s.PERIODO,a.CODIGO,c.CODSBLIN,b.CODLINEA,SUM(ICANTIDAD) AS SALIDA,SUM(OCANTIDAD) AS ENTRADA from SALDOINV s 
INNER JOIN MtMercia a ON a.CODIGO=s.CODIGO
INNER JOIN MtLinea b ON b.CODLINEA=a.CODLINEA 
INNER JOIN MtSblin c ON c.CODSBLIN=a.CODSBLIN
group by
s.ANO,s.PERIODO,a.CODIGO,c.CODSBLIN,b.CODLINEA
ORDER BY s.ANO DESC,s.PERIODO DESC

select b.CODLINEA,b.NOMBRE AS NOMLINEA,c.CODSBLIN,c.NOMBRE AS NOMSUBLINEA,a.CODIGO,a.DESCRIPCIO from MtMercia a
INNER JOIN MtLinea b ON b.CODLINEA=a.CODLINEA 
INNER JOIN MtSblin c ON c.CODSBLIN=a.CODSBLIN