USE BESTPRICE

SELECT
    A.FECHA, YEAR (a.fecha) AS ANO, MONTH (a.fecha) AS MES, C.NOMBRE, C.CODPRECIO, A.TIPODCTO, A.NRODCTO,
    B.BODEGA, D.CODSBLIN, E.NOMBRE AS SUBLINEA, B.PRODUCTO, B.NOMBRE AS DESCRIPCION,
    B.CANVENTA, B.COSTO, B.IVA, B.VLRVENTA, A.DSCTOCOM,
	ROUND(B.VLRVENTA/((B.IVA/100)+1),2) AS PRECIO_SIN_ITBIS,
	(ROUND(B.VLRVENTA/((B.IVA/100)+1),2))*B.CANVENTA AS BRUTO,
	ROUND(B.VLRVENTA/((B.IVA/100)+1),2)*A.DSCTOCOM/100 AS DSCTO,
	(ROUND(B.VLRVENTA/((B.IVA/100)+1),2))-(ROUND(B.VLRVENTA/((B.IVA/100)+1),2)*A.DSCTOCOM/100) AS BRUTO_UNIT,
	((ROUND(B.VLRVENTA/((B.IVA/100)+1),2))-(ROUND(B.VLRVENTA/((B.IVA/100)+1),2)*A.DSCTOCOM/100))*B.CANVENTA AS TOTAL_VENTA,
	ROUND((((ROUND(B.VLRVENTA/((B.IVA/100)+1),2))-(ROUND(B.VLRVENTA/((B.IVA/100)+1),2)*A.DSCTOCOM/100))*B.CANVENTA)*B.IVA/100,2) AS ITBIS,
	ROUND((ROUND((((ROUND(B.VLRVENTA/((B.IVA/100)+1),2))-(ROUND(B.VLRVENTA/((B.IVA/100)+1),2)*A.DSCTOCOM/100))*B.CANVENTA)*B.IVA/100,2))+(((ROUND(B.VLRVENTA/((B.IVA/100)+1),2))-(ROUND(B.VLRVENTA/((B.IVA/100)+1),2)*A.DSCTOCOM/100))*B.CANVENTA),1) AS TOTAL_VTA_NETA2,
	ROUND(B.COSTO*B.CANVENTA,2) AS TOTAL_COSTO,
	1 - (
    ROUND(B.COSTO*B.CANVENTA,2) / 
    NULLIF(
        ((ROUND(B.VLRVENTA/((B.IVA/100)+1),2))
        -(ROUND(B.VLRVENTA/((B.IVA/100)+1),2)*A.DSCTOCOM/100)
        ) * B.CANVENTA
    ,0)
) AS MB_PORCENTAJE,
	(((ROUND(B.VLRVENTA/((B.IVA/100)+1),2))-(ROUND(B.VLRVENTA/((B.IVA/100)+1),2)*A.DSCTOCOM/100))*B.CANVENTA)-ROUND(B.COSTO*B.CANVENTA,2) AS MB$
FROM
    TRADE A
    INNER JOIN MVTRADE B ON A.NRODCTO = B.NRODCTO
    AND A.TIPODCTO = B.TIPODCTO
    AND A.ORIGEN = B.ORIGEN
    INNER JOIN MTPROCLI C ON C.NIT = A.NIT
    INNER JOIN MTMERCIA D ON B.PRODUCTO = D.CODIGO
    INNER JOIN MTSBLIN E ON D.CODSBLIN = E.CODSBLIN
WHERE
    A.TIPODCTO in ('F2', 'B2', 'B1', 'B4', 'F4', 'NC')
    and B.ORIGEN = 'FAC'
    AND B.PRODUCTO NOT IN ('01', '02')
    AND A.FECHA >= getdate () -90
ORDER BY
    A.NRODCTO,B.PRODUCTO DESC