USE SUPERTODO;
SELECT 
    44000 + ROW_NUMBER() OVER (ORDER BY CAST(NRODCTO AS INT)) AS Consecutivo,NRODCTO,
	(CASE WHEN NRODCTO=Consecutivo THEN 'EXISTE' ELSE 'NO COINCIDE') AS VALIDO
FROM Trade
WHERE TIPODCTO = 'R2';

SELECT NRODCTO,TIPODCTO,NOTA,FECHA
FROM Trade
WHERE TIPODCTO = 'R2'
ORDER BY CAST(NRODCTO AS INT);


WITH CTE AS (
    SELECT 
        44000 + ROW_NUMBER() OVER (ORDER BY CAST(NRODCTO AS INT)) AS Consecutivo,
        NRODCTO
    FROM Trade
    WHERE TIPODCTO = 'R2'
)

SELECT 
    Consecutivo,
    NRODCTO,
    CASE 
        WHEN EXISTS (
            SELECT 1 
            FROM Trade T2 
            WHERE T2.TIPODCTO = 'R2'
              AND CAST(T2.NRODCTO AS INT) = Consecutivo
        )
        THEN 'EXISTE'
        ELSE 'NO EXISTE'
    END AS VALIDO
FROM CTE
ORDER BY Consecutivo;

select TIPODCTO,NRODCTO,NOTA,* from Trade where NRODCTO='259318' AND TIPODCTO='R2'