USE SUPERTODO
--TRADE
select (BRUTO+IVABRUTO),FECHA,NOTA,BRUTO,IVABRUTO,DESCUENTO,DSCTOCOM,NOTA,CODINT,* from Trade where NRODCTO='48149' AND TIPODCTO='R2'
--MVTRADE
select PRODUCTO,(CANTIDAD*VALORUNIT),(CANTIDAD*VALORUNIT)-((CANTIDAD*VALORUNIT)*(DESCUENTO/100))AS VENTA,DESCUENTO,CANTIDAD,VALORUNIT,VLRVENTA,FECHA,IVA,(VALORUNIT)*(IVA/100) from Mvtrade where NRODCTO='48149' AND TIPODCTO='R2'
--MVCUADRE
select VALOR,FECING,* from MvCuadre where DCTO='48149' AND TIPODCTO='R2'

--update mvtrade set DESCUENTO='0' where TIPODCTO IN ('R2','R1')
select * from Mvtrade where DESCUENTO<>'0' AND TIPODCTO IN ('R2','R1')

--DESCUENTO TRADE
select NRODCTO,(BRUTO+IVABRUTO),FECHA,NOTA,BRUTO,IVABRUTO,DESCUENTO,DSCTOCOM,NOTA,* from Trade 
where TIPODCTO IN ('R2','R1') AND DESCUENTO<>'0' AND FECHA BETWEEN '01-06-2025' AND '30-06-2025' AND NRODCTO='48149'

--update trade set BRUTO='1477.72'  where TIPODCTO IN ('R2','R1') AND DESCUENTO<>'0' AND FECHA BETWEEN '01-06-2025' AND '30-06-2025' AND NRODCTO='48149'

select (BRUTO+DESCUENTO) AS BRUTO_DEF,FECHA,NOTA,BRUTO,IVABRUTO,DESCUENTO,DSCTOCOM,NOTA,* from Trade where NRODCTO='48149' AND TIPODCTO='R2'

select ((BRUTO+IVABRUTO)-DESCUENTO) AS BRUTO_DEF,FECHA,NOTA,BRUTO,IVABRUTO,DESCUENTO,DSCTOCOM,NOTA,* from Trade where NRODCTO='48149' AND TIPODCTO='R2'