USE SUPERTODO;
SELECT 
    MM.CODIGO,
    MM.CODBARRAS,
    MM.DESCRIPCIO,
    MS.NOMBRE AS CATEGORIA,
	-- Datos de cliente y transacciones
    DatosVenta.NIT,
    DatosVenta.NOMBRE AS PROVEEDOR,
    DatosVenta.ULT_FECHA_ING,
    DatosVenta.ULT_COSTO_ING,
    -- Datos de precios
    Precios.LISTPRECIO_1,
    Precios.LISTPRECIO_2,
    Precios.LISTPRECIO_3,
    Precios.LISTPRECIO_4,
    Precios.LISTPRECIO_5,
    Precios.LISTPRECIO_6,
    Precios.LISTPRECIO_7

FROM MtMercia AS MM
INNER JOIN MtSblin AS MS 
    ON MS.CODSBLIN = MM.CODSBLIN

-- JOIN precios
LEFT JOIN (
    SELECT 
        CODPRODUC,
        MAX(CASE WHEN CODPRECIO = '1' THEN PRECIO END) AS LISTPRECIO_1,
        MAX(CASE WHEN CODPRECIO = '2' THEN PRECIO END) AS LISTPRECIO_2,
        MAX(CASE WHEN CODPRECIO = '3' THEN PRECIO END) AS LISTPRECIO_3,
        MAX(CASE WHEN CODPRECIO = '4' THEN PRECIO END) AS LISTPRECIO_4,
        MAX(CASE WHEN CODPRECIO = '5' THEN PRECIO END) AS LISTPRECIO_5,
        MAX(CASE WHEN CODPRECIO = '6' THEN PRECIO END) AS LISTPRECIO_6,
        MAX(CASE WHEN CODPRECIO = '7' THEN PRECIO END) AS LISTPRECIO_7
    FROM SUPERTODO.dbo.MvPrecio
    WHERE CODPRECIO IN ('1','2','3','4','5','6','7')
    GROUP BY CODPRODUC
) AS Precios 
    ON Precios.CODPRODUC = MM.CODIGO

-- JOIN datos de ventas
LEFT JOIN (
    SELECT 
        A.PRODUCTO,
        B.NIT,
        MP.NOMBRE,
        MAX(B.FECHA) AS ULT_FECHA_ING,
        (SELECT TOP 1 C.HCOSTO
         FROM COSTOINV AS C
         WHERE C.CODIGO = A.PRODUCTO
         ORDER BY C.ANO DESC, C.PERIODO DESC) AS ULT_COSTO_ING
    FROM Mvtrade AS A
    INNER JOIN Trade AS B 
        ON A.TIPODCTO = B.TIPODCTO AND A.NRODCTO = B.NRODCTO AND A.ORIGEN = B.ORIGEN
    INNER JOIN MtProcli AS MP 
        ON MP.NIT = B.NIT
    WHERE A.ORIGEN = 'COM'
        AND A.TIPODCTO IN ('F1','F4')
    GROUP BY A.PRODUCTO, B.NIT, MP.NOMBRE
) AS DatosVenta 
    ON DatosVenta.PRODUCTO = MM.CODIGO

ORDER BY MM.CODIGO ASC;
