/*Inserta Datos MTCAMBIO de una tabla a otra*/
USE SUPERTODO
select MS.FECHA,MB.FECHA from MTCAMBIO MS 
LEFT JOIN BESTPRICE.dbo.MTCAMBIO MB ON MS.FECHA=MB.FECHA
WHERE MB.FECHA IS NULL

INSERT INTO BESTPRICE.dbo.MTCAMBIO (DIA, FECHA, TASAVEN, VALOR)
SELECT 
    MS.DIA,
    MS.FECHA,
    MS.TASAVEN,
    MS.VALOR
FROM SUPERTODO.dbo.MTCAMBIO MS
LEFT JOIN BESTPRICE.dbo.MTCAMBIO MB 
    ON MS.FECHA = MB.FECHA
WHERE MB.FECHA IS NULL;

USE SUPERTODO
select COUNT(*) from MTCAMBIO
USE BESTPRICE
select COUNT(*) from MTCAMBIO